// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-study/app/database/account/internal/data/ent/accountwallet"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountWalletCreate is the builder for creating a AccountWallet entity.
type AccountWalletCreate struct {
	config
	mutation *AccountWalletMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (awc *AccountWalletCreate) SetTenantID(i int32) *AccountWalletCreate {
	awc.mutation.SetTenantID(i)
	return awc
}

// SetAccountID sets the "account_id" field.
func (awc *AccountWalletCreate) SetAccountID(i int32) *AccountWalletCreate {
	awc.mutation.SetAccountID(i)
	return awc
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (awc *AccountWalletCreate) SetNillableAccountID(i *int32) *AccountWalletCreate {
	if i != nil {
		awc.SetAccountID(*i)
	}
	return awc
}

// SetAccountIntegral sets the "account_integral" field.
func (awc *AccountWalletCreate) SetAccountIntegral(i int32) *AccountWalletCreate {
	awc.mutation.SetAccountIntegral(i)
	return awc
}

// SetNillableAccountIntegral sets the "account_integral" field if the given value is not nil.
func (awc *AccountWalletCreate) SetNillableAccountIntegral(i *int32) *AccountWalletCreate {
	if i != nil {
		awc.SetAccountIntegral(*i)
	}
	return awc
}

// SetAccountBalance sets the "account_balance" field.
func (awc *AccountWalletCreate) SetAccountBalance(f float64) *AccountWalletCreate {
	awc.mutation.SetAccountBalance(f)
	return awc
}

// SetNillableAccountBalance sets the "account_balance" field if the given value is not nil.
func (awc *AccountWalletCreate) SetNillableAccountBalance(f *float64) *AccountWalletCreate {
	if f != nil {
		awc.SetAccountBalance(*f)
	}
	return awc
}

// SetFreezeBalance sets the "freeze_balance" field.
func (awc *AccountWalletCreate) SetFreezeBalance(f float64) *AccountWalletCreate {
	awc.mutation.SetFreezeBalance(f)
	return awc
}

// SetFreezeIntegral sets the "freeze_integral" field.
func (awc *AccountWalletCreate) SetFreezeIntegral(i int32) *AccountWalletCreate {
	awc.mutation.SetFreezeIntegral(i)
	return awc
}

// SetNillableFreezeIntegral sets the "freeze_integral" field if the given value is not nil.
func (awc *AccountWalletCreate) SetNillableFreezeIntegral(i *int32) *AccountWalletCreate {
	if i != nil {
		awc.SetFreezeIntegral(*i)
	}
	return awc
}

// SetOpenInstallment sets the "open_installment" field.
func (awc *AccountWalletCreate) SetOpenInstallment(i int8) *AccountWalletCreate {
	awc.mutation.SetOpenInstallment(i)
	return awc
}

// SetNillableOpenInstallment sets the "open_installment" field if the given value is not nil.
func (awc *AccountWalletCreate) SetNillableOpenInstallment(i *int8) *AccountWalletCreate {
	if i != nil {
		awc.SetOpenInstallment(*i)
	}
	return awc
}

// SetStatus sets the "status" field.
func (awc *AccountWalletCreate) SetStatus(i int8) *AccountWalletCreate {
	awc.mutation.SetStatus(i)
	return awc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (awc *AccountWalletCreate) SetNillableStatus(i *int8) *AccountWalletCreate {
	if i != nil {
		awc.SetStatus(*i)
	}
	return awc
}

// SetState sets the "state" field.
func (awc *AccountWalletCreate) SetState(i int8) *AccountWalletCreate {
	awc.mutation.SetState(i)
	return awc
}

// SetNillableState sets the "state" field if the given value is not nil.
func (awc *AccountWalletCreate) SetNillableState(i *int8) *AccountWalletCreate {
	if i != nil {
		awc.SetState(*i)
	}
	return awc
}

// SetCreatedAt sets the "created_at" field.
func (awc *AccountWalletCreate) SetCreatedAt(t time.Time) *AccountWalletCreate {
	awc.mutation.SetCreatedAt(t)
	return awc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (awc *AccountWalletCreate) SetNillableCreatedAt(t *time.Time) *AccountWalletCreate {
	if t != nil {
		awc.SetCreatedAt(*t)
	}
	return awc
}

// SetUpdatedAt sets the "updated_at" field.
func (awc *AccountWalletCreate) SetUpdatedAt(t time.Time) *AccountWalletCreate {
	awc.mutation.SetUpdatedAt(t)
	return awc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (awc *AccountWalletCreate) SetNillableUpdatedAt(t *time.Time) *AccountWalletCreate {
	if t != nil {
		awc.SetUpdatedAt(*t)
	}
	return awc
}

// SetID sets the "id" field.
func (awc *AccountWalletCreate) SetID(i int32) *AccountWalletCreate {
	awc.mutation.SetID(i)
	return awc
}

// Mutation returns the AccountWalletMutation object of the builder.
func (awc *AccountWalletCreate) Mutation() *AccountWalletMutation {
	return awc.mutation
}

// Save creates the AccountWallet in the database.
func (awc *AccountWalletCreate) Save(ctx context.Context) (*AccountWallet, error) {
	awc.defaults()
	return withHooks(ctx, awc.sqlSave, awc.mutation, awc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (awc *AccountWalletCreate) SaveX(ctx context.Context) *AccountWallet {
	v, err := awc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (awc *AccountWalletCreate) Exec(ctx context.Context) error {
	_, err := awc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (awc *AccountWalletCreate) ExecX(ctx context.Context) {
	if err := awc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (awc *AccountWalletCreate) defaults() {
	if _, ok := awc.mutation.AccountIntegral(); !ok {
		v := accountwallet.DefaultAccountIntegral
		awc.mutation.SetAccountIntegral(v)
	}
	if _, ok := awc.mutation.FreezeIntegral(); !ok {
		v := accountwallet.DefaultFreezeIntegral
		awc.mutation.SetFreezeIntegral(v)
	}
	if _, ok := awc.mutation.OpenInstallment(); !ok {
		v := accountwallet.DefaultOpenInstallment
		awc.mutation.SetOpenInstallment(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (awc *AccountWalletCreate) check() error {
	if _, ok := awc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "AccountWallet.tenant_id"`)}
	}
	if _, ok := awc.mutation.FreezeBalance(); !ok {
		return &ValidationError{Name: "freeze_balance", err: errors.New(`ent: missing required field "AccountWallet.freeze_balance"`)}
	}
	if _, ok := awc.mutation.OpenInstallment(); !ok {
		return &ValidationError{Name: "open_installment", err: errors.New(`ent: missing required field "AccountWallet.open_installment"`)}
	}
	return nil
}

func (awc *AccountWalletCreate) sqlSave(ctx context.Context) (*AccountWallet, error) {
	if err := awc.check(); err != nil {
		return nil, err
	}
	_node, _spec := awc.createSpec()
	if err := sqlgraph.CreateNode(ctx, awc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int32(id)
	}
	awc.mutation.id = &_node.ID
	awc.mutation.done = true
	return _node, nil
}

func (awc *AccountWalletCreate) createSpec() (*AccountWallet, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountWallet{config: awc.config}
		_spec = sqlgraph.NewCreateSpec(accountwallet.Table, sqlgraph.NewFieldSpec(accountwallet.FieldID, field.TypeInt32))
	)
	_spec.OnConflict = awc.conflict
	if id, ok := awc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := awc.mutation.TenantID(); ok {
		_spec.SetField(accountwallet.FieldTenantID, field.TypeInt32, value)
		_node.TenantID = value
	}
	if value, ok := awc.mutation.AccountID(); ok {
		_spec.SetField(accountwallet.FieldAccountID, field.TypeInt32, value)
		_node.AccountID = value
	}
	if value, ok := awc.mutation.AccountIntegral(); ok {
		_spec.SetField(accountwallet.FieldAccountIntegral, field.TypeInt32, value)
		_node.AccountIntegral = value
	}
	if value, ok := awc.mutation.AccountBalance(); ok {
		_spec.SetField(accountwallet.FieldAccountBalance, field.TypeFloat64, value)
		_node.AccountBalance = value
	}
	if value, ok := awc.mutation.FreezeBalance(); ok {
		_spec.SetField(accountwallet.FieldFreezeBalance, field.TypeFloat64, value)
		_node.FreezeBalance = value
	}
	if value, ok := awc.mutation.FreezeIntegral(); ok {
		_spec.SetField(accountwallet.FieldFreezeIntegral, field.TypeInt32, value)
		_node.FreezeIntegral = value
	}
	if value, ok := awc.mutation.OpenInstallment(); ok {
		_spec.SetField(accountwallet.FieldOpenInstallment, field.TypeInt8, value)
		_node.OpenInstallment = value
	}
	if value, ok := awc.mutation.Status(); ok {
		_spec.SetField(accountwallet.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := awc.mutation.State(); ok {
		_spec.SetField(accountwallet.FieldState, field.TypeInt8, value)
		_node.State = value
	}
	if value, ok := awc.mutation.CreatedAt(); ok {
		_spec.SetField(accountwallet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := awc.mutation.UpdatedAt(); ok {
		_spec.SetField(accountwallet.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountWallet.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountWalletUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (awc *AccountWalletCreate) OnConflict(opts ...sql.ConflictOption) *AccountWalletUpsertOne {
	awc.conflict = opts
	return &AccountWalletUpsertOne{
		create: awc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountWallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (awc *AccountWalletCreate) OnConflictColumns(columns ...string) *AccountWalletUpsertOne {
	awc.conflict = append(awc.conflict, sql.ConflictColumns(columns...))
	return &AccountWalletUpsertOne{
		create: awc,
	}
}

type (
	// AccountWalletUpsertOne is the builder for "upsert"-ing
	//  one AccountWallet node.
	AccountWalletUpsertOne struct {
		create *AccountWalletCreate
	}

	// AccountWalletUpsert is the "OnConflict" setter.
	AccountWalletUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *AccountWalletUpsert) SetTenantID(v int32) *AccountWalletUpsert {
	u.Set(accountwallet.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateTenantID() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldTenantID)
	return u
}

// AddTenantID adds v to the "tenant_id" field.
func (u *AccountWalletUpsert) AddTenantID(v int32) *AccountWalletUpsert {
	u.Add(accountwallet.FieldTenantID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountWalletUpsert) SetAccountID(v int32) *AccountWalletUpsert {
	u.Set(accountwallet.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateAccountID() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountWalletUpsert) AddAccountID(v int32) *AccountWalletUpsert {
	u.Add(accountwallet.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *AccountWalletUpsert) ClearAccountID() *AccountWalletUpsert {
	u.SetNull(accountwallet.FieldAccountID)
	return u
}

// SetAccountIntegral sets the "account_integral" field.
func (u *AccountWalletUpsert) SetAccountIntegral(v int32) *AccountWalletUpsert {
	u.Set(accountwallet.FieldAccountIntegral, v)
	return u
}

// UpdateAccountIntegral sets the "account_integral" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateAccountIntegral() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldAccountIntegral)
	return u
}

// AddAccountIntegral adds v to the "account_integral" field.
func (u *AccountWalletUpsert) AddAccountIntegral(v int32) *AccountWalletUpsert {
	u.Add(accountwallet.FieldAccountIntegral, v)
	return u
}

// ClearAccountIntegral clears the value of the "account_integral" field.
func (u *AccountWalletUpsert) ClearAccountIntegral() *AccountWalletUpsert {
	u.SetNull(accountwallet.FieldAccountIntegral)
	return u
}

// SetAccountBalance sets the "account_balance" field.
func (u *AccountWalletUpsert) SetAccountBalance(v float64) *AccountWalletUpsert {
	u.Set(accountwallet.FieldAccountBalance, v)
	return u
}

// UpdateAccountBalance sets the "account_balance" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateAccountBalance() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldAccountBalance)
	return u
}

// AddAccountBalance adds v to the "account_balance" field.
func (u *AccountWalletUpsert) AddAccountBalance(v float64) *AccountWalletUpsert {
	u.Add(accountwallet.FieldAccountBalance, v)
	return u
}

// ClearAccountBalance clears the value of the "account_balance" field.
func (u *AccountWalletUpsert) ClearAccountBalance() *AccountWalletUpsert {
	u.SetNull(accountwallet.FieldAccountBalance)
	return u
}

// SetFreezeBalance sets the "freeze_balance" field.
func (u *AccountWalletUpsert) SetFreezeBalance(v float64) *AccountWalletUpsert {
	u.Set(accountwallet.FieldFreezeBalance, v)
	return u
}

// UpdateFreezeBalance sets the "freeze_balance" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateFreezeBalance() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldFreezeBalance)
	return u
}

// AddFreezeBalance adds v to the "freeze_balance" field.
func (u *AccountWalletUpsert) AddFreezeBalance(v float64) *AccountWalletUpsert {
	u.Add(accountwallet.FieldFreezeBalance, v)
	return u
}

// SetFreezeIntegral sets the "freeze_integral" field.
func (u *AccountWalletUpsert) SetFreezeIntegral(v int32) *AccountWalletUpsert {
	u.Set(accountwallet.FieldFreezeIntegral, v)
	return u
}

// UpdateFreezeIntegral sets the "freeze_integral" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateFreezeIntegral() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldFreezeIntegral)
	return u
}

// AddFreezeIntegral adds v to the "freeze_integral" field.
func (u *AccountWalletUpsert) AddFreezeIntegral(v int32) *AccountWalletUpsert {
	u.Add(accountwallet.FieldFreezeIntegral, v)
	return u
}

// ClearFreezeIntegral clears the value of the "freeze_integral" field.
func (u *AccountWalletUpsert) ClearFreezeIntegral() *AccountWalletUpsert {
	u.SetNull(accountwallet.FieldFreezeIntegral)
	return u
}

// SetOpenInstallment sets the "open_installment" field.
func (u *AccountWalletUpsert) SetOpenInstallment(v int8) *AccountWalletUpsert {
	u.Set(accountwallet.FieldOpenInstallment, v)
	return u
}

// UpdateOpenInstallment sets the "open_installment" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateOpenInstallment() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldOpenInstallment)
	return u
}

// AddOpenInstallment adds v to the "open_installment" field.
func (u *AccountWalletUpsert) AddOpenInstallment(v int8) *AccountWalletUpsert {
	u.Add(accountwallet.FieldOpenInstallment, v)
	return u
}

// SetStatus sets the "status" field.
func (u *AccountWalletUpsert) SetStatus(v int8) *AccountWalletUpsert {
	u.Set(accountwallet.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateStatus() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *AccountWalletUpsert) AddStatus(v int8) *AccountWalletUpsert {
	u.Add(accountwallet.FieldStatus, v)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *AccountWalletUpsert) ClearStatus() *AccountWalletUpsert {
	u.SetNull(accountwallet.FieldStatus)
	return u
}

// SetState sets the "state" field.
func (u *AccountWalletUpsert) SetState(v int8) *AccountWalletUpsert {
	u.Set(accountwallet.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateState() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldState)
	return u
}

// AddState adds v to the "state" field.
func (u *AccountWalletUpsert) AddState(v int8) *AccountWalletUpsert {
	u.Add(accountwallet.FieldState, v)
	return u
}

// ClearState clears the value of the "state" field.
func (u *AccountWalletUpsert) ClearState() *AccountWalletUpsert {
	u.SetNull(accountwallet.FieldState)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *AccountWalletUpsert) SetCreatedAt(v time.Time) *AccountWalletUpsert {
	u.Set(accountwallet.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateCreatedAt() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldCreatedAt)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *AccountWalletUpsert) ClearCreatedAt() *AccountWalletUpsert {
	u.SetNull(accountwallet.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountWalletUpsert) SetUpdatedAt(v time.Time) *AccountWalletUpsert {
	u.Set(accountwallet.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountWalletUpsert) UpdateUpdatedAt() *AccountWalletUpsert {
	u.SetExcluded(accountwallet.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AccountWalletUpsert) ClearUpdatedAt() *AccountWalletUpsert {
	u.SetNull(accountwallet.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AccountWallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accountwallet.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountWalletUpsertOne) UpdateNewValues() *AccountWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(accountwallet.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountWallet.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountWalletUpsertOne) Ignore() *AccountWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountWalletUpsertOne) DoNothing() *AccountWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountWalletCreate.OnConflict
// documentation for more info.
func (u *AccountWalletUpsertOne) Update(set func(*AccountWalletUpsert)) *AccountWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountWalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *AccountWalletUpsertOne) SetTenantID(v int32) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *AccountWalletUpsertOne) AddTenantID(v int32) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateTenantID() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateTenantID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountWalletUpsertOne) SetAccountID(v int32) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountWalletUpsertOne) AddAccountID(v int32) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateAccountID() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *AccountWalletUpsertOne) ClearAccountID() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearAccountID()
	})
}

// SetAccountIntegral sets the "account_integral" field.
func (u *AccountWalletUpsertOne) SetAccountIntegral(v int32) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetAccountIntegral(v)
	})
}

// AddAccountIntegral adds v to the "account_integral" field.
func (u *AccountWalletUpsertOne) AddAccountIntegral(v int32) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddAccountIntegral(v)
	})
}

// UpdateAccountIntegral sets the "account_integral" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateAccountIntegral() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateAccountIntegral()
	})
}

// ClearAccountIntegral clears the value of the "account_integral" field.
func (u *AccountWalletUpsertOne) ClearAccountIntegral() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearAccountIntegral()
	})
}

// SetAccountBalance sets the "account_balance" field.
func (u *AccountWalletUpsertOne) SetAccountBalance(v float64) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetAccountBalance(v)
	})
}

// AddAccountBalance adds v to the "account_balance" field.
func (u *AccountWalletUpsertOne) AddAccountBalance(v float64) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddAccountBalance(v)
	})
}

// UpdateAccountBalance sets the "account_balance" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateAccountBalance() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateAccountBalance()
	})
}

// ClearAccountBalance clears the value of the "account_balance" field.
func (u *AccountWalletUpsertOne) ClearAccountBalance() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearAccountBalance()
	})
}

// SetFreezeBalance sets the "freeze_balance" field.
func (u *AccountWalletUpsertOne) SetFreezeBalance(v float64) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetFreezeBalance(v)
	})
}

// AddFreezeBalance adds v to the "freeze_balance" field.
func (u *AccountWalletUpsertOne) AddFreezeBalance(v float64) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddFreezeBalance(v)
	})
}

// UpdateFreezeBalance sets the "freeze_balance" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateFreezeBalance() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateFreezeBalance()
	})
}

// SetFreezeIntegral sets the "freeze_integral" field.
func (u *AccountWalletUpsertOne) SetFreezeIntegral(v int32) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetFreezeIntegral(v)
	})
}

// AddFreezeIntegral adds v to the "freeze_integral" field.
func (u *AccountWalletUpsertOne) AddFreezeIntegral(v int32) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddFreezeIntegral(v)
	})
}

// UpdateFreezeIntegral sets the "freeze_integral" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateFreezeIntegral() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateFreezeIntegral()
	})
}

// ClearFreezeIntegral clears the value of the "freeze_integral" field.
func (u *AccountWalletUpsertOne) ClearFreezeIntegral() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearFreezeIntegral()
	})
}

// SetOpenInstallment sets the "open_installment" field.
func (u *AccountWalletUpsertOne) SetOpenInstallment(v int8) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetOpenInstallment(v)
	})
}

// AddOpenInstallment adds v to the "open_installment" field.
func (u *AccountWalletUpsertOne) AddOpenInstallment(v int8) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddOpenInstallment(v)
	})
}

// UpdateOpenInstallment sets the "open_installment" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateOpenInstallment() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateOpenInstallment()
	})
}

// SetStatus sets the "status" field.
func (u *AccountWalletUpsertOne) SetStatus(v int8) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *AccountWalletUpsertOne) AddStatus(v int8) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateStatus() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *AccountWalletUpsertOne) ClearStatus() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearStatus()
	})
}

// SetState sets the "state" field.
func (u *AccountWalletUpsertOne) SetState(v int8) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetState(v)
	})
}

// AddState adds v to the "state" field.
func (u *AccountWalletUpsertOne) AddState(v int8) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateState() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *AccountWalletUpsertOne) ClearState() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearState()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AccountWalletUpsertOne) SetCreatedAt(v time.Time) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateCreatedAt() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *AccountWalletUpsertOne) ClearCreatedAt() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountWalletUpsertOne) SetUpdatedAt(v time.Time) *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountWalletUpsertOne) UpdateUpdatedAt() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AccountWalletUpsertOne) ClearUpdatedAt() *AccountWalletUpsertOne {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountWalletUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountWalletCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountWalletUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountWalletUpsertOne) ID(ctx context.Context) (id int32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountWalletUpsertOne) IDX(ctx context.Context) int32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountWalletCreateBulk is the builder for creating many AccountWallet entities in bulk.
type AccountWalletCreateBulk struct {
	config
	err      error
	builders []*AccountWalletCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountWallet entities in the database.
func (awcb *AccountWalletCreateBulk) Save(ctx context.Context) ([]*AccountWallet, error) {
	if awcb.err != nil {
		return nil, awcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(awcb.builders))
	nodes := make([]*AccountWallet, len(awcb.builders))
	mutators := make([]Mutator, len(awcb.builders))
	for i := range awcb.builders {
		func(i int, root context.Context) {
			builder := awcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountWalletMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, awcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = awcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, awcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, awcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (awcb *AccountWalletCreateBulk) SaveX(ctx context.Context) []*AccountWallet {
	v, err := awcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (awcb *AccountWalletCreateBulk) Exec(ctx context.Context) error {
	_, err := awcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (awcb *AccountWalletCreateBulk) ExecX(ctx context.Context) {
	if err := awcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountWallet.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountWalletUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (awcb *AccountWalletCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountWalletUpsertBulk {
	awcb.conflict = opts
	return &AccountWalletUpsertBulk{
		create: awcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountWallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (awcb *AccountWalletCreateBulk) OnConflictColumns(columns ...string) *AccountWalletUpsertBulk {
	awcb.conflict = append(awcb.conflict, sql.ConflictColumns(columns...))
	return &AccountWalletUpsertBulk{
		create: awcb,
	}
}

// AccountWalletUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountWallet nodes.
type AccountWalletUpsertBulk struct {
	create *AccountWalletCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountWallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accountwallet.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountWalletUpsertBulk) UpdateNewValues() *AccountWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(accountwallet.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountWallet.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountWalletUpsertBulk) Ignore() *AccountWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountWalletUpsertBulk) DoNothing() *AccountWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountWalletCreateBulk.OnConflict
// documentation for more info.
func (u *AccountWalletUpsertBulk) Update(set func(*AccountWalletUpsert)) *AccountWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountWalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *AccountWalletUpsertBulk) SetTenantID(v int32) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *AccountWalletUpsertBulk) AddTenantID(v int32) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateTenantID() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateTenantID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountWalletUpsertBulk) SetAccountID(v int32) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountWalletUpsertBulk) AddAccountID(v int32) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateAccountID() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *AccountWalletUpsertBulk) ClearAccountID() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearAccountID()
	})
}

// SetAccountIntegral sets the "account_integral" field.
func (u *AccountWalletUpsertBulk) SetAccountIntegral(v int32) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetAccountIntegral(v)
	})
}

// AddAccountIntegral adds v to the "account_integral" field.
func (u *AccountWalletUpsertBulk) AddAccountIntegral(v int32) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddAccountIntegral(v)
	})
}

// UpdateAccountIntegral sets the "account_integral" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateAccountIntegral() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateAccountIntegral()
	})
}

// ClearAccountIntegral clears the value of the "account_integral" field.
func (u *AccountWalletUpsertBulk) ClearAccountIntegral() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearAccountIntegral()
	})
}

// SetAccountBalance sets the "account_balance" field.
func (u *AccountWalletUpsertBulk) SetAccountBalance(v float64) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetAccountBalance(v)
	})
}

// AddAccountBalance adds v to the "account_balance" field.
func (u *AccountWalletUpsertBulk) AddAccountBalance(v float64) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddAccountBalance(v)
	})
}

// UpdateAccountBalance sets the "account_balance" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateAccountBalance() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateAccountBalance()
	})
}

// ClearAccountBalance clears the value of the "account_balance" field.
func (u *AccountWalletUpsertBulk) ClearAccountBalance() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearAccountBalance()
	})
}

// SetFreezeBalance sets the "freeze_balance" field.
func (u *AccountWalletUpsertBulk) SetFreezeBalance(v float64) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetFreezeBalance(v)
	})
}

// AddFreezeBalance adds v to the "freeze_balance" field.
func (u *AccountWalletUpsertBulk) AddFreezeBalance(v float64) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddFreezeBalance(v)
	})
}

// UpdateFreezeBalance sets the "freeze_balance" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateFreezeBalance() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateFreezeBalance()
	})
}

// SetFreezeIntegral sets the "freeze_integral" field.
func (u *AccountWalletUpsertBulk) SetFreezeIntegral(v int32) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetFreezeIntegral(v)
	})
}

// AddFreezeIntegral adds v to the "freeze_integral" field.
func (u *AccountWalletUpsertBulk) AddFreezeIntegral(v int32) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddFreezeIntegral(v)
	})
}

// UpdateFreezeIntegral sets the "freeze_integral" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateFreezeIntegral() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateFreezeIntegral()
	})
}

// ClearFreezeIntegral clears the value of the "freeze_integral" field.
func (u *AccountWalletUpsertBulk) ClearFreezeIntegral() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearFreezeIntegral()
	})
}

// SetOpenInstallment sets the "open_installment" field.
func (u *AccountWalletUpsertBulk) SetOpenInstallment(v int8) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetOpenInstallment(v)
	})
}

// AddOpenInstallment adds v to the "open_installment" field.
func (u *AccountWalletUpsertBulk) AddOpenInstallment(v int8) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddOpenInstallment(v)
	})
}

// UpdateOpenInstallment sets the "open_installment" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateOpenInstallment() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateOpenInstallment()
	})
}

// SetStatus sets the "status" field.
func (u *AccountWalletUpsertBulk) SetStatus(v int8) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *AccountWalletUpsertBulk) AddStatus(v int8) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateStatus() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *AccountWalletUpsertBulk) ClearStatus() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearStatus()
	})
}

// SetState sets the "state" field.
func (u *AccountWalletUpsertBulk) SetState(v int8) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetState(v)
	})
}

// AddState adds v to the "state" field.
func (u *AccountWalletUpsertBulk) AddState(v int8) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.AddState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateState() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *AccountWalletUpsertBulk) ClearState() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearState()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AccountWalletUpsertBulk) SetCreatedAt(v time.Time) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateCreatedAt() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *AccountWalletUpsertBulk) ClearCreatedAt() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountWalletUpsertBulk) SetUpdatedAt(v time.Time) *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountWalletUpsertBulk) UpdateUpdatedAt() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AccountWalletUpsertBulk) ClearUpdatedAt() *AccountWalletUpsertBulk {
	return u.Update(func(s *AccountWalletUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountWalletUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountWalletCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountWalletCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountWalletUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
