// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-study/app/database/account/internal/data/ent/accountwallet"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AccountWallet is the model entity for the AccountWallet schema.
type AccountWallet struct {
	config `json:"-"`
	// ID of the ent.
	// 用户id
	ID int32 `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int32 `json:"tenant_id,omitempty"`
	// 用户ID
	AccountID int32 `json:"account_id,omitempty"`
	// 当前积分
	AccountIntegral int32 `json:"account_integral,omitempty"`
	// 当前余额
	AccountBalance float64 `json:"account_balance,omitempty"`
	// 冻结资金
	FreezeBalance float64 `json:"freeze_balance,omitempty"`
	// 冻结积分
	FreezeIntegral int32 `json:"freeze_integral,omitempty"`
	// 分期付款
	OpenInstallment int8 `json:"open_installment,omitempty"`
	// Status holds the value of the "status" field.
	Status int8 `json:"status,omitempty"`
	// State holds the value of the "state" field.
	State int8 `json:"state,omitempty"`
	// 注册时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新信息时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountWallet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountwallet.FieldAccountBalance, accountwallet.FieldFreezeBalance:
			values[i] = new(sql.NullFloat64)
		case accountwallet.FieldID, accountwallet.FieldTenantID, accountwallet.FieldAccountID, accountwallet.FieldAccountIntegral, accountwallet.FieldFreezeIntegral, accountwallet.FieldOpenInstallment, accountwallet.FieldStatus, accountwallet.FieldState:
			values[i] = new(sql.NullInt64)
		case accountwallet.FieldCreatedAt, accountwallet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountWallet fields.
func (aw *AccountWallet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountwallet.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			aw.ID = int32(value.Int64)
		case accountwallet.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				aw.TenantID = int32(value.Int64)
			}
		case accountwallet.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				aw.AccountID = int32(value.Int64)
			}
		case accountwallet.FieldAccountIntegral:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_integral", values[i])
			} else if value.Valid {
				aw.AccountIntegral = int32(value.Int64)
			}
		case accountwallet.FieldAccountBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field account_balance", values[i])
			} else if value.Valid {
				aw.AccountBalance = value.Float64
			}
		case accountwallet.FieldFreezeBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field freeze_balance", values[i])
			} else if value.Valid {
				aw.FreezeBalance = value.Float64
			}
		case accountwallet.FieldFreezeIntegral:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field freeze_integral", values[i])
			} else if value.Valid {
				aw.FreezeIntegral = int32(value.Int64)
			}
		case accountwallet.FieldOpenInstallment:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field open_installment", values[i])
			} else if value.Valid {
				aw.OpenInstallment = int8(value.Int64)
			}
		case accountwallet.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				aw.Status = int8(value.Int64)
			}
		case accountwallet.FieldState:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				aw.State = int8(value.Int64)
			}
		case accountwallet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				aw.CreatedAt = value.Time
			}
		case accountwallet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				aw.UpdatedAt = value.Time
			}
		default:
			aw.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountWallet.
// This includes values selected through modifiers, order, etc.
func (aw *AccountWallet) Value(name string) (ent.Value, error) {
	return aw.selectValues.Get(name)
}

// Update returns a builder for updating this AccountWallet.
// Note that you need to call AccountWallet.Unwrap() before calling this method if this AccountWallet
// was returned from a transaction, and the transaction was committed or rolled back.
func (aw *AccountWallet) Update() *AccountWalletUpdateOne {
	return NewAccountWalletClient(aw.config).UpdateOne(aw)
}

// Unwrap unwraps the AccountWallet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (aw *AccountWallet) Unwrap() *AccountWallet {
	_tx, ok := aw.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountWallet is not a transactional entity")
	}
	aw.config.driver = _tx.drv
	return aw
}

// String implements the fmt.Stringer.
func (aw *AccountWallet) String() string {
	var builder strings.Builder
	builder.WriteString("AccountWallet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", aw.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", aw.TenantID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", aw.AccountID))
	builder.WriteString(", ")
	builder.WriteString("account_integral=")
	builder.WriteString(fmt.Sprintf("%v", aw.AccountIntegral))
	builder.WriteString(", ")
	builder.WriteString("account_balance=")
	builder.WriteString(fmt.Sprintf("%v", aw.AccountBalance))
	builder.WriteString(", ")
	builder.WriteString("freeze_balance=")
	builder.WriteString(fmt.Sprintf("%v", aw.FreezeBalance))
	builder.WriteString(", ")
	builder.WriteString("freeze_integral=")
	builder.WriteString(fmt.Sprintf("%v", aw.FreezeIntegral))
	builder.WriteString(", ")
	builder.WriteString("open_installment=")
	builder.WriteString(fmt.Sprintf("%v", aw.OpenInstallment))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", aw.Status))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", aw.State))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(aw.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(aw.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountWallets is a parsable slice of AccountWallet.
type AccountWallets []*AccountWallet
