// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-study/app/database/account/internal/data/ent/account"
	"go-study/app/database/account/internal/data/ent/accountwallet"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 2)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   account.Table,
			Columns: account.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: account.FieldID,
			},
		},
		Type: "Account",
		Fields: map[string]*sqlgraph.FieldSpec{
			account.FieldTenantID:        {Type: field.TypeInt32, Column: account.FieldTenantID},
			account.FieldUpdatedAt:       {Type: field.TypeTime, Column: account.FieldUpdatedAt},
			account.FieldCreatedAt:       {Type: field.TypeTime, Column: account.FieldCreatedAt},
			account.FieldAccountIntegral: {Type: field.TypeInt32, Column: account.FieldAccountIntegral},
			account.FieldAccountBalance:  {Type: field.TypeFloat64, Column: account.FieldAccountBalance},
			account.FieldUserIdentity:    {Type: field.TypeInt8, Column: account.FieldUserIdentity},
			account.FieldFreezeBalance:   {Type: field.TypeFloat64, Column: account.FieldFreezeBalance},
			account.FieldFreezeIntegral:  {Type: field.TypeInt32, Column: account.FieldFreezeIntegral},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   accountwallet.Table,
			Columns: accountwallet.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: accountwallet.FieldID,
			},
		},
		Type: "AccountWallet",
		Fields: map[string]*sqlgraph.FieldSpec{
			accountwallet.FieldTenantID:        {Type: field.TypeInt32, Column: accountwallet.FieldTenantID},
			accountwallet.FieldAccountID:       {Type: field.TypeInt32, Column: accountwallet.FieldAccountID},
			accountwallet.FieldAccountIntegral: {Type: field.TypeInt32, Column: accountwallet.FieldAccountIntegral},
			accountwallet.FieldAccountBalance:  {Type: field.TypeFloat64, Column: accountwallet.FieldAccountBalance},
			accountwallet.FieldFreezeBalance:   {Type: field.TypeFloat64, Column: accountwallet.FieldFreezeBalance},
			accountwallet.FieldFreezeIntegral:  {Type: field.TypeInt32, Column: accountwallet.FieldFreezeIntegral},
			accountwallet.FieldOpenInstallment: {Type: field.TypeInt8, Column: accountwallet.FieldOpenInstallment},
			accountwallet.FieldStatus:          {Type: field.TypeInt8, Column: accountwallet.FieldStatus},
			accountwallet.FieldState:           {Type: field.TypeInt8, Column: accountwallet.FieldState},
			accountwallet.FieldCreatedAt:       {Type: field.TypeTime, Column: accountwallet.FieldCreatedAt},
			accountwallet.FieldUpdatedAt:       {Type: field.TypeTime, Column: accountwallet.FieldUpdatedAt},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (aq *AccountQuery) addPredicate(pred func(s *sql.Selector)) {
	aq.predicates = append(aq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the AccountQuery builder.
func (aq *AccountQuery) Filter() *AccountFilter {
	return &AccountFilter{config: aq.config, predicateAdder: aq}
}

// addPredicate implements the predicateAdder interface.
func (m *AccountMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the AccountMutation builder.
func (m *AccountMutation) Filter() *AccountFilter {
	return &AccountFilter{config: m.config, predicateAdder: m}
}

// AccountFilter provides a generic filtering capability at runtime for AccountQuery.
type AccountFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *AccountFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int32 predicate on the id field.
func (f *AccountFilter) WhereID(p entql.Int32P) {
	f.Where(p.Field(account.FieldID))
}

// WhereTenantID applies the entql int32 predicate on the tenant_id field.
func (f *AccountFilter) WhereTenantID(p entql.Int32P) {
	f.Where(p.Field(account.FieldTenantID))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *AccountFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(account.FieldUpdatedAt))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *AccountFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(account.FieldCreatedAt))
}

// WhereAccountIntegral applies the entql int32 predicate on the account_integral field.
func (f *AccountFilter) WhereAccountIntegral(p entql.Int32P) {
	f.Where(p.Field(account.FieldAccountIntegral))
}

// WhereAccountBalance applies the entql float64 predicate on the account_balance field.
func (f *AccountFilter) WhereAccountBalance(p entql.Float64P) {
	f.Where(p.Field(account.FieldAccountBalance))
}

// WhereUserIdentity applies the entql int8 predicate on the user_identity field.
func (f *AccountFilter) WhereUserIdentity(p entql.Int8P) {
	f.Where(p.Field(account.FieldUserIdentity))
}

// WhereFreezeBalance applies the entql float64 predicate on the freeze_balance field.
func (f *AccountFilter) WhereFreezeBalance(p entql.Float64P) {
	f.Where(p.Field(account.FieldFreezeBalance))
}

// WhereFreezeIntegral applies the entql int32 predicate on the freeze_integral field.
func (f *AccountFilter) WhereFreezeIntegral(p entql.Int32P) {
	f.Where(p.Field(account.FieldFreezeIntegral))
}

// addPredicate implements the predicateAdder interface.
func (awq *AccountWalletQuery) addPredicate(pred func(s *sql.Selector)) {
	awq.predicates = append(awq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the AccountWalletQuery builder.
func (awq *AccountWalletQuery) Filter() *AccountWalletFilter {
	return &AccountWalletFilter{config: awq.config, predicateAdder: awq}
}

// addPredicate implements the predicateAdder interface.
func (m *AccountWalletMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the AccountWalletMutation builder.
func (m *AccountWalletMutation) Filter() *AccountWalletFilter {
	return &AccountWalletFilter{config: m.config, predicateAdder: m}
}

// AccountWalletFilter provides a generic filtering capability at runtime for AccountWalletQuery.
type AccountWalletFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *AccountWalletFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int32 predicate on the id field.
func (f *AccountWalletFilter) WhereID(p entql.Int32P) {
	f.Where(p.Field(accountwallet.FieldID))
}

// WhereTenantID applies the entql int32 predicate on the tenant_id field.
func (f *AccountWalletFilter) WhereTenantID(p entql.Int32P) {
	f.Where(p.Field(accountwallet.FieldTenantID))
}

// WhereAccountID applies the entql int32 predicate on the account_id field.
func (f *AccountWalletFilter) WhereAccountID(p entql.Int32P) {
	f.Where(p.Field(accountwallet.FieldAccountID))
}

// WhereAccountIntegral applies the entql int32 predicate on the account_integral field.
func (f *AccountWalletFilter) WhereAccountIntegral(p entql.Int32P) {
	f.Where(p.Field(accountwallet.FieldAccountIntegral))
}

// WhereAccountBalance applies the entql float64 predicate on the account_balance field.
func (f *AccountWalletFilter) WhereAccountBalance(p entql.Float64P) {
	f.Where(p.Field(accountwallet.FieldAccountBalance))
}

// WhereFreezeBalance applies the entql float64 predicate on the freeze_balance field.
func (f *AccountWalletFilter) WhereFreezeBalance(p entql.Float64P) {
	f.Where(p.Field(accountwallet.FieldFreezeBalance))
}

// WhereFreezeIntegral applies the entql int32 predicate on the freeze_integral field.
func (f *AccountWalletFilter) WhereFreezeIntegral(p entql.Int32P) {
	f.Where(p.Field(accountwallet.FieldFreezeIntegral))
}

// WhereOpenInstallment applies the entql int8 predicate on the open_installment field.
func (f *AccountWalletFilter) WhereOpenInstallment(p entql.Int8P) {
	f.Where(p.Field(accountwallet.FieldOpenInstallment))
}

// WhereStatus applies the entql int8 predicate on the status field.
func (f *AccountWalletFilter) WhereStatus(p entql.Int8P) {
	f.Where(p.Field(accountwallet.FieldStatus))
}

// WhereState applies the entql int8 predicate on the state field.
func (f *AccountWalletFilter) WhereState(p entql.Int8P) {
	f.Where(p.Field(accountwallet.FieldState))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *AccountWalletFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(accountwallet.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *AccountWalletFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(accountwallet.FieldUpdatedAt))
}
