// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-study/app/database/account/internal/data/ent/account"
	"go-study/app/database/account/internal/data/ent/accountwallet"
	"go-study/app/database/account/internal/data/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAccount       = "Account"
	TypeAccountWallet = "AccountWallet"
)

// AccountMutation represents an operation that mutates the Account nodes in the graph.
type AccountMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int32
	tenant_id           *int32
	addtenant_id        *int32
	updated_at          *time.Time
	created_at          *time.Time
	account_integral    *int32
	addaccount_integral *int32
	account_balance     *float64
	addaccount_balance  *float64
	user_identity       *int8
	adduser_identity    *int8
	freeze_balance      *float64
	addfreeze_balance   *float64
	freeze_integral     *int32
	addfreeze_integral  *int32
	clearedFields       map[string]struct{}
	done                bool
	oldValue            func(context.Context) (*Account, error)
	predicates          []predicate.Account
}

var _ ent.Mutation = (*AccountMutation)(nil)

// accountOption allows management of the mutation configuration using functional options.
type accountOption func(*AccountMutation)

// newAccountMutation creates new mutation for the Account entity.
func newAccountMutation(c config, op Op, opts ...accountOption) *AccountMutation {
	m := &AccountMutation{
		config:        c,
		op:            op,
		typ:           TypeAccount,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAccountID sets the ID field of the mutation.
func withAccountID(id int32) accountOption {
	return func(m *AccountMutation) {
		var (
			err   error
			once  sync.Once
			value *Account
		)
		m.oldValue = func(ctx context.Context) (*Account, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Account.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAccount sets the old Account of the mutation.
func withAccount(node *Account) accountOption {
	return func(m *AccountMutation) {
		m.oldValue = func(context.Context) (*Account, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AccountMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AccountMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Account entities.
func (m *AccountMutation) SetID(id int32) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AccountMutation) ID() (id int32, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AccountMutation) IDs(ctx context.Context) ([]int32, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int32{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Account.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTenantID sets the "tenant_id" field.
func (m *AccountMutation) SetTenantID(i int32) {
	m.tenant_id = &i
	m.addtenant_id = nil
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *AccountMutation) TenantID() (r int32, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the Account entity.
// If the Account object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountMutation) OldTenantID(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// AddTenantID adds i to the "tenant_id" field.
func (m *AccountMutation) AddTenantID(i int32) {
	if m.addtenant_id != nil {
		*m.addtenant_id += i
	} else {
		m.addtenant_id = &i
	}
}

// AddedTenantID returns the value that was added to the "tenant_id" field in this mutation.
func (m *AccountMutation) AddedTenantID() (r int32, exists bool) {
	v := m.addtenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *AccountMutation) ResetTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AccountMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AccountMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Account entity.
// If the Account object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (m *AccountMutation) ClearUpdatedAt() {
	m.updated_at = nil
	m.clearedFields[account.FieldUpdatedAt] = struct{}{}
}

// UpdatedAtCleared returns if the "updated_at" field was cleared in this mutation.
func (m *AccountMutation) UpdatedAtCleared() bool {
	_, ok := m.clearedFields[account.FieldUpdatedAt]
	return ok
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AccountMutation) ResetUpdatedAt() {
	m.updated_at = nil
	delete(m.clearedFields, account.FieldUpdatedAt)
}

// SetCreatedAt sets the "created_at" field.
func (m *AccountMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AccountMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Account entity.
// If the Account object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ClearCreatedAt clears the value of the "created_at" field.
func (m *AccountMutation) ClearCreatedAt() {
	m.created_at = nil
	m.clearedFields[account.FieldCreatedAt] = struct{}{}
}

// CreatedAtCleared returns if the "created_at" field was cleared in this mutation.
func (m *AccountMutation) CreatedAtCleared() bool {
	_, ok := m.clearedFields[account.FieldCreatedAt]
	return ok
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AccountMutation) ResetCreatedAt() {
	m.created_at = nil
	delete(m.clearedFields, account.FieldCreatedAt)
}

// SetAccountIntegral sets the "account_integral" field.
func (m *AccountMutation) SetAccountIntegral(i int32) {
	m.account_integral = &i
	m.addaccount_integral = nil
}

// AccountIntegral returns the value of the "account_integral" field in the mutation.
func (m *AccountMutation) AccountIntegral() (r int32, exists bool) {
	v := m.account_integral
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountIntegral returns the old "account_integral" field's value of the Account entity.
// If the Account object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountMutation) OldAccountIntegral(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountIntegral is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountIntegral requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountIntegral: %w", err)
	}
	return oldValue.AccountIntegral, nil
}

// AddAccountIntegral adds i to the "account_integral" field.
func (m *AccountMutation) AddAccountIntegral(i int32) {
	if m.addaccount_integral != nil {
		*m.addaccount_integral += i
	} else {
		m.addaccount_integral = &i
	}
}

// AddedAccountIntegral returns the value that was added to the "account_integral" field in this mutation.
func (m *AccountMutation) AddedAccountIntegral() (r int32, exists bool) {
	v := m.addaccount_integral
	if v == nil {
		return
	}
	return *v, true
}

// ClearAccountIntegral clears the value of the "account_integral" field.
func (m *AccountMutation) ClearAccountIntegral() {
	m.account_integral = nil
	m.addaccount_integral = nil
	m.clearedFields[account.FieldAccountIntegral] = struct{}{}
}

// AccountIntegralCleared returns if the "account_integral" field was cleared in this mutation.
func (m *AccountMutation) AccountIntegralCleared() bool {
	_, ok := m.clearedFields[account.FieldAccountIntegral]
	return ok
}

// ResetAccountIntegral resets all changes to the "account_integral" field.
func (m *AccountMutation) ResetAccountIntegral() {
	m.account_integral = nil
	m.addaccount_integral = nil
	delete(m.clearedFields, account.FieldAccountIntegral)
}

// SetAccountBalance sets the "account_balance" field.
func (m *AccountMutation) SetAccountBalance(f float64) {
	m.account_balance = &f
	m.addaccount_balance = nil
}

// AccountBalance returns the value of the "account_balance" field in the mutation.
func (m *AccountMutation) AccountBalance() (r float64, exists bool) {
	v := m.account_balance
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountBalance returns the old "account_balance" field's value of the Account entity.
// If the Account object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountMutation) OldAccountBalance(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountBalance is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountBalance requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountBalance: %w", err)
	}
	return oldValue.AccountBalance, nil
}

// AddAccountBalance adds f to the "account_balance" field.
func (m *AccountMutation) AddAccountBalance(f float64) {
	if m.addaccount_balance != nil {
		*m.addaccount_balance += f
	} else {
		m.addaccount_balance = &f
	}
}

// AddedAccountBalance returns the value that was added to the "account_balance" field in this mutation.
func (m *AccountMutation) AddedAccountBalance() (r float64, exists bool) {
	v := m.addaccount_balance
	if v == nil {
		return
	}
	return *v, true
}

// ClearAccountBalance clears the value of the "account_balance" field.
func (m *AccountMutation) ClearAccountBalance() {
	m.account_balance = nil
	m.addaccount_balance = nil
	m.clearedFields[account.FieldAccountBalance] = struct{}{}
}

// AccountBalanceCleared returns if the "account_balance" field was cleared in this mutation.
func (m *AccountMutation) AccountBalanceCleared() bool {
	_, ok := m.clearedFields[account.FieldAccountBalance]
	return ok
}

// ResetAccountBalance resets all changes to the "account_balance" field.
func (m *AccountMutation) ResetAccountBalance() {
	m.account_balance = nil
	m.addaccount_balance = nil
	delete(m.clearedFields, account.FieldAccountBalance)
}

// SetUserIdentity sets the "user_identity" field.
func (m *AccountMutation) SetUserIdentity(i int8) {
	m.user_identity = &i
	m.adduser_identity = nil
}

// UserIdentity returns the value of the "user_identity" field in the mutation.
func (m *AccountMutation) UserIdentity() (r int8, exists bool) {
	v := m.user_identity
	if v == nil {
		return
	}
	return *v, true
}

// OldUserIdentity returns the old "user_identity" field's value of the Account entity.
// If the Account object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountMutation) OldUserIdentity(ctx context.Context) (v int8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserIdentity is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserIdentity requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserIdentity: %w", err)
	}
	return oldValue.UserIdentity, nil
}

// AddUserIdentity adds i to the "user_identity" field.
func (m *AccountMutation) AddUserIdentity(i int8) {
	if m.adduser_identity != nil {
		*m.adduser_identity += i
	} else {
		m.adduser_identity = &i
	}
}

// AddedUserIdentity returns the value that was added to the "user_identity" field in this mutation.
func (m *AccountMutation) AddedUserIdentity() (r int8, exists bool) {
	v := m.adduser_identity
	if v == nil {
		return
	}
	return *v, true
}

// ResetUserIdentity resets all changes to the "user_identity" field.
func (m *AccountMutation) ResetUserIdentity() {
	m.user_identity = nil
	m.adduser_identity = nil
}

// SetFreezeBalance sets the "freeze_balance" field.
func (m *AccountMutation) SetFreezeBalance(f float64) {
	m.freeze_balance = &f
	m.addfreeze_balance = nil
}

// FreezeBalance returns the value of the "freeze_balance" field in the mutation.
func (m *AccountMutation) FreezeBalance() (r float64, exists bool) {
	v := m.freeze_balance
	if v == nil {
		return
	}
	return *v, true
}

// OldFreezeBalance returns the old "freeze_balance" field's value of the Account entity.
// If the Account object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountMutation) OldFreezeBalance(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFreezeBalance is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFreezeBalance requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFreezeBalance: %w", err)
	}
	return oldValue.FreezeBalance, nil
}

// AddFreezeBalance adds f to the "freeze_balance" field.
func (m *AccountMutation) AddFreezeBalance(f float64) {
	if m.addfreeze_balance != nil {
		*m.addfreeze_balance += f
	} else {
		m.addfreeze_balance = &f
	}
}

// AddedFreezeBalance returns the value that was added to the "freeze_balance" field in this mutation.
func (m *AccountMutation) AddedFreezeBalance() (r float64, exists bool) {
	v := m.addfreeze_balance
	if v == nil {
		return
	}
	return *v, true
}

// ClearFreezeBalance clears the value of the "freeze_balance" field.
func (m *AccountMutation) ClearFreezeBalance() {
	m.freeze_balance = nil
	m.addfreeze_balance = nil
	m.clearedFields[account.FieldFreezeBalance] = struct{}{}
}

// FreezeBalanceCleared returns if the "freeze_balance" field was cleared in this mutation.
func (m *AccountMutation) FreezeBalanceCleared() bool {
	_, ok := m.clearedFields[account.FieldFreezeBalance]
	return ok
}

// ResetFreezeBalance resets all changes to the "freeze_balance" field.
func (m *AccountMutation) ResetFreezeBalance() {
	m.freeze_balance = nil
	m.addfreeze_balance = nil
	delete(m.clearedFields, account.FieldFreezeBalance)
}

// SetFreezeIntegral sets the "freeze_integral" field.
func (m *AccountMutation) SetFreezeIntegral(i int32) {
	m.freeze_integral = &i
	m.addfreeze_integral = nil
}

// FreezeIntegral returns the value of the "freeze_integral" field in the mutation.
func (m *AccountMutation) FreezeIntegral() (r int32, exists bool) {
	v := m.freeze_integral
	if v == nil {
		return
	}
	return *v, true
}

// OldFreezeIntegral returns the old "freeze_integral" field's value of the Account entity.
// If the Account object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountMutation) OldFreezeIntegral(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFreezeIntegral is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFreezeIntegral requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFreezeIntegral: %w", err)
	}
	return oldValue.FreezeIntegral, nil
}

// AddFreezeIntegral adds i to the "freeze_integral" field.
func (m *AccountMutation) AddFreezeIntegral(i int32) {
	if m.addfreeze_integral != nil {
		*m.addfreeze_integral += i
	} else {
		m.addfreeze_integral = &i
	}
}

// AddedFreezeIntegral returns the value that was added to the "freeze_integral" field in this mutation.
func (m *AccountMutation) AddedFreezeIntegral() (r int32, exists bool) {
	v := m.addfreeze_integral
	if v == nil {
		return
	}
	return *v, true
}

// ResetFreezeIntegral resets all changes to the "freeze_integral" field.
func (m *AccountMutation) ResetFreezeIntegral() {
	m.freeze_integral = nil
	m.addfreeze_integral = nil
}

// Where appends a list predicates to the AccountMutation builder.
func (m *AccountMutation) Where(ps ...predicate.Account) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AccountMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AccountMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Account, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AccountMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AccountMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Account).
func (m *AccountMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AccountMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.tenant_id != nil {
		fields = append(fields, account.FieldTenantID)
	}
	if m.updated_at != nil {
		fields = append(fields, account.FieldUpdatedAt)
	}
	if m.created_at != nil {
		fields = append(fields, account.FieldCreatedAt)
	}
	if m.account_integral != nil {
		fields = append(fields, account.FieldAccountIntegral)
	}
	if m.account_balance != nil {
		fields = append(fields, account.FieldAccountBalance)
	}
	if m.user_identity != nil {
		fields = append(fields, account.FieldUserIdentity)
	}
	if m.freeze_balance != nil {
		fields = append(fields, account.FieldFreezeBalance)
	}
	if m.freeze_integral != nil {
		fields = append(fields, account.FieldFreezeIntegral)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AccountMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case account.FieldTenantID:
		return m.TenantID()
	case account.FieldUpdatedAt:
		return m.UpdatedAt()
	case account.FieldCreatedAt:
		return m.CreatedAt()
	case account.FieldAccountIntegral:
		return m.AccountIntegral()
	case account.FieldAccountBalance:
		return m.AccountBalance()
	case account.FieldUserIdentity:
		return m.UserIdentity()
	case account.FieldFreezeBalance:
		return m.FreezeBalance()
	case account.FieldFreezeIntegral:
		return m.FreezeIntegral()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AccountMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case account.FieldTenantID:
		return m.OldTenantID(ctx)
	case account.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case account.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case account.FieldAccountIntegral:
		return m.OldAccountIntegral(ctx)
	case account.FieldAccountBalance:
		return m.OldAccountBalance(ctx)
	case account.FieldUserIdentity:
		return m.OldUserIdentity(ctx)
	case account.FieldFreezeBalance:
		return m.OldFreezeBalance(ctx)
	case account.FieldFreezeIntegral:
		return m.OldFreezeIntegral(ctx)
	}
	return nil, fmt.Errorf("unknown Account field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AccountMutation) SetField(name string, value ent.Value) error {
	switch name {
	case account.FieldTenantID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case account.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case account.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case account.FieldAccountIntegral:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountIntegral(v)
		return nil
	case account.FieldAccountBalance:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountBalance(v)
		return nil
	case account.FieldUserIdentity:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserIdentity(v)
		return nil
	case account.FieldFreezeBalance:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFreezeBalance(v)
		return nil
	case account.FieldFreezeIntegral:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFreezeIntegral(v)
		return nil
	}
	return fmt.Errorf("unknown Account field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AccountMutation) AddedFields() []string {
	var fields []string
	if m.addtenant_id != nil {
		fields = append(fields, account.FieldTenantID)
	}
	if m.addaccount_integral != nil {
		fields = append(fields, account.FieldAccountIntegral)
	}
	if m.addaccount_balance != nil {
		fields = append(fields, account.FieldAccountBalance)
	}
	if m.adduser_identity != nil {
		fields = append(fields, account.FieldUserIdentity)
	}
	if m.addfreeze_balance != nil {
		fields = append(fields, account.FieldFreezeBalance)
	}
	if m.addfreeze_integral != nil {
		fields = append(fields, account.FieldFreezeIntegral)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AccountMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case account.FieldTenantID:
		return m.AddedTenantID()
	case account.FieldAccountIntegral:
		return m.AddedAccountIntegral()
	case account.FieldAccountBalance:
		return m.AddedAccountBalance()
	case account.FieldUserIdentity:
		return m.AddedUserIdentity()
	case account.FieldFreezeBalance:
		return m.AddedFreezeBalance()
	case account.FieldFreezeIntegral:
		return m.AddedFreezeIntegral()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AccountMutation) AddField(name string, value ent.Value) error {
	switch name {
	case account.FieldTenantID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTenantID(v)
		return nil
	case account.FieldAccountIntegral:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAccountIntegral(v)
		return nil
	case account.FieldAccountBalance:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAccountBalance(v)
		return nil
	case account.FieldUserIdentity:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUserIdentity(v)
		return nil
	case account.FieldFreezeBalance:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFreezeBalance(v)
		return nil
	case account.FieldFreezeIntegral:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFreezeIntegral(v)
		return nil
	}
	return fmt.Errorf("unknown Account numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AccountMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(account.FieldUpdatedAt) {
		fields = append(fields, account.FieldUpdatedAt)
	}
	if m.FieldCleared(account.FieldCreatedAt) {
		fields = append(fields, account.FieldCreatedAt)
	}
	if m.FieldCleared(account.FieldAccountIntegral) {
		fields = append(fields, account.FieldAccountIntegral)
	}
	if m.FieldCleared(account.FieldAccountBalance) {
		fields = append(fields, account.FieldAccountBalance)
	}
	if m.FieldCleared(account.FieldFreezeBalance) {
		fields = append(fields, account.FieldFreezeBalance)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AccountMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AccountMutation) ClearField(name string) error {
	switch name {
	case account.FieldUpdatedAt:
		m.ClearUpdatedAt()
		return nil
	case account.FieldCreatedAt:
		m.ClearCreatedAt()
		return nil
	case account.FieldAccountIntegral:
		m.ClearAccountIntegral()
		return nil
	case account.FieldAccountBalance:
		m.ClearAccountBalance()
		return nil
	case account.FieldFreezeBalance:
		m.ClearFreezeBalance()
		return nil
	}
	return fmt.Errorf("unknown Account nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AccountMutation) ResetField(name string) error {
	switch name {
	case account.FieldTenantID:
		m.ResetTenantID()
		return nil
	case account.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case account.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case account.FieldAccountIntegral:
		m.ResetAccountIntegral()
		return nil
	case account.FieldAccountBalance:
		m.ResetAccountBalance()
		return nil
	case account.FieldUserIdentity:
		m.ResetUserIdentity()
		return nil
	case account.FieldFreezeBalance:
		m.ResetFreezeBalance()
		return nil
	case account.FieldFreezeIntegral:
		m.ResetFreezeIntegral()
		return nil
	}
	return fmt.Errorf("unknown Account field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AccountMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AccountMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AccountMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AccountMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AccountMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AccountMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AccountMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Account unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AccountMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Account edge %s", name)
}

// AccountWalletMutation represents an operation that mutates the AccountWallet nodes in the graph.
type AccountWalletMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int32
	tenant_id           *int32
	addtenant_id        *int32
	account_id          *int32
	addaccount_id       *int32
	account_integral    *int32
	addaccount_integral *int32
	account_balance     *float64
	addaccount_balance  *float64
	freeze_balance      *float64
	addfreeze_balance   *float64
	freeze_integral     *int32
	addfreeze_integral  *int32
	open_installment    *int8
	addopen_installment *int8
	status              *int8
	addstatus           *int8
	state               *int8
	addstate            *int8
	created_at          *time.Time
	updated_at          *time.Time
	clearedFields       map[string]struct{}
	done                bool
	oldValue            func(context.Context) (*AccountWallet, error)
	predicates          []predicate.AccountWallet
}

var _ ent.Mutation = (*AccountWalletMutation)(nil)

// accountwalletOption allows management of the mutation configuration using functional options.
type accountwalletOption func(*AccountWalletMutation)

// newAccountWalletMutation creates new mutation for the AccountWallet entity.
func newAccountWalletMutation(c config, op Op, opts ...accountwalletOption) *AccountWalletMutation {
	m := &AccountWalletMutation{
		config:        c,
		op:            op,
		typ:           TypeAccountWallet,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAccountWalletID sets the ID field of the mutation.
func withAccountWalletID(id int32) accountwalletOption {
	return func(m *AccountWalletMutation) {
		var (
			err   error
			once  sync.Once
			value *AccountWallet
		)
		m.oldValue = func(ctx context.Context) (*AccountWallet, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AccountWallet.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAccountWallet sets the old AccountWallet of the mutation.
func withAccountWallet(node *AccountWallet) accountwalletOption {
	return func(m *AccountWalletMutation) {
		m.oldValue = func(context.Context) (*AccountWallet, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AccountWalletMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AccountWalletMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AccountWallet entities.
func (m *AccountWalletMutation) SetID(id int32) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AccountWalletMutation) ID() (id int32, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AccountWalletMutation) IDs(ctx context.Context) ([]int32, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int32{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AccountWallet.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTenantID sets the "tenant_id" field.
func (m *AccountWalletMutation) SetTenantID(i int32) {
	m.tenant_id = &i
	m.addtenant_id = nil
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *AccountWalletMutation) TenantID() (r int32, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldTenantID(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// AddTenantID adds i to the "tenant_id" field.
func (m *AccountWalletMutation) AddTenantID(i int32) {
	if m.addtenant_id != nil {
		*m.addtenant_id += i
	} else {
		m.addtenant_id = &i
	}
}

// AddedTenantID returns the value that was added to the "tenant_id" field in this mutation.
func (m *AccountWalletMutation) AddedTenantID() (r int32, exists bool) {
	v := m.addtenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *AccountWalletMutation) ResetTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
}

// SetAccountID sets the "account_id" field.
func (m *AccountWalletMutation) SetAccountID(i int32) {
	m.account_id = &i
	m.addaccount_id = nil
}

// AccountID returns the value of the "account_id" field in the mutation.
func (m *AccountWalletMutation) AccountID() (r int32, exists bool) {
	v := m.account_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountID returns the old "account_id" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldAccountID(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountID: %w", err)
	}
	return oldValue.AccountID, nil
}

// AddAccountID adds i to the "account_id" field.
func (m *AccountWalletMutation) AddAccountID(i int32) {
	if m.addaccount_id != nil {
		*m.addaccount_id += i
	} else {
		m.addaccount_id = &i
	}
}

// AddedAccountID returns the value that was added to the "account_id" field in this mutation.
func (m *AccountWalletMutation) AddedAccountID() (r int32, exists bool) {
	v := m.addaccount_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearAccountID clears the value of the "account_id" field.
func (m *AccountWalletMutation) ClearAccountID() {
	m.account_id = nil
	m.addaccount_id = nil
	m.clearedFields[accountwallet.FieldAccountID] = struct{}{}
}

// AccountIDCleared returns if the "account_id" field was cleared in this mutation.
func (m *AccountWalletMutation) AccountIDCleared() bool {
	_, ok := m.clearedFields[accountwallet.FieldAccountID]
	return ok
}

// ResetAccountID resets all changes to the "account_id" field.
func (m *AccountWalletMutation) ResetAccountID() {
	m.account_id = nil
	m.addaccount_id = nil
	delete(m.clearedFields, accountwallet.FieldAccountID)
}

// SetAccountIntegral sets the "account_integral" field.
func (m *AccountWalletMutation) SetAccountIntegral(i int32) {
	m.account_integral = &i
	m.addaccount_integral = nil
}

// AccountIntegral returns the value of the "account_integral" field in the mutation.
func (m *AccountWalletMutation) AccountIntegral() (r int32, exists bool) {
	v := m.account_integral
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountIntegral returns the old "account_integral" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldAccountIntegral(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountIntegral is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountIntegral requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountIntegral: %w", err)
	}
	return oldValue.AccountIntegral, nil
}

// AddAccountIntegral adds i to the "account_integral" field.
func (m *AccountWalletMutation) AddAccountIntegral(i int32) {
	if m.addaccount_integral != nil {
		*m.addaccount_integral += i
	} else {
		m.addaccount_integral = &i
	}
}

// AddedAccountIntegral returns the value that was added to the "account_integral" field in this mutation.
func (m *AccountWalletMutation) AddedAccountIntegral() (r int32, exists bool) {
	v := m.addaccount_integral
	if v == nil {
		return
	}
	return *v, true
}

// ClearAccountIntegral clears the value of the "account_integral" field.
func (m *AccountWalletMutation) ClearAccountIntegral() {
	m.account_integral = nil
	m.addaccount_integral = nil
	m.clearedFields[accountwallet.FieldAccountIntegral] = struct{}{}
}

// AccountIntegralCleared returns if the "account_integral" field was cleared in this mutation.
func (m *AccountWalletMutation) AccountIntegralCleared() bool {
	_, ok := m.clearedFields[accountwallet.FieldAccountIntegral]
	return ok
}

// ResetAccountIntegral resets all changes to the "account_integral" field.
func (m *AccountWalletMutation) ResetAccountIntegral() {
	m.account_integral = nil
	m.addaccount_integral = nil
	delete(m.clearedFields, accountwallet.FieldAccountIntegral)
}

// SetAccountBalance sets the "account_balance" field.
func (m *AccountWalletMutation) SetAccountBalance(f float64) {
	m.account_balance = &f
	m.addaccount_balance = nil
}

// AccountBalance returns the value of the "account_balance" field in the mutation.
func (m *AccountWalletMutation) AccountBalance() (r float64, exists bool) {
	v := m.account_balance
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountBalance returns the old "account_balance" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldAccountBalance(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountBalance is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountBalance requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountBalance: %w", err)
	}
	return oldValue.AccountBalance, nil
}

// AddAccountBalance adds f to the "account_balance" field.
func (m *AccountWalletMutation) AddAccountBalance(f float64) {
	if m.addaccount_balance != nil {
		*m.addaccount_balance += f
	} else {
		m.addaccount_balance = &f
	}
}

// AddedAccountBalance returns the value that was added to the "account_balance" field in this mutation.
func (m *AccountWalletMutation) AddedAccountBalance() (r float64, exists bool) {
	v := m.addaccount_balance
	if v == nil {
		return
	}
	return *v, true
}

// ClearAccountBalance clears the value of the "account_balance" field.
func (m *AccountWalletMutation) ClearAccountBalance() {
	m.account_balance = nil
	m.addaccount_balance = nil
	m.clearedFields[accountwallet.FieldAccountBalance] = struct{}{}
}

// AccountBalanceCleared returns if the "account_balance" field was cleared in this mutation.
func (m *AccountWalletMutation) AccountBalanceCleared() bool {
	_, ok := m.clearedFields[accountwallet.FieldAccountBalance]
	return ok
}

// ResetAccountBalance resets all changes to the "account_balance" field.
func (m *AccountWalletMutation) ResetAccountBalance() {
	m.account_balance = nil
	m.addaccount_balance = nil
	delete(m.clearedFields, accountwallet.FieldAccountBalance)
}

// SetFreezeBalance sets the "freeze_balance" field.
func (m *AccountWalletMutation) SetFreezeBalance(f float64) {
	m.freeze_balance = &f
	m.addfreeze_balance = nil
}

// FreezeBalance returns the value of the "freeze_balance" field in the mutation.
func (m *AccountWalletMutation) FreezeBalance() (r float64, exists bool) {
	v := m.freeze_balance
	if v == nil {
		return
	}
	return *v, true
}

// OldFreezeBalance returns the old "freeze_balance" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldFreezeBalance(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFreezeBalance is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFreezeBalance requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFreezeBalance: %w", err)
	}
	return oldValue.FreezeBalance, nil
}

// AddFreezeBalance adds f to the "freeze_balance" field.
func (m *AccountWalletMutation) AddFreezeBalance(f float64) {
	if m.addfreeze_balance != nil {
		*m.addfreeze_balance += f
	} else {
		m.addfreeze_balance = &f
	}
}

// AddedFreezeBalance returns the value that was added to the "freeze_balance" field in this mutation.
func (m *AccountWalletMutation) AddedFreezeBalance() (r float64, exists bool) {
	v := m.addfreeze_balance
	if v == nil {
		return
	}
	return *v, true
}

// ResetFreezeBalance resets all changes to the "freeze_balance" field.
func (m *AccountWalletMutation) ResetFreezeBalance() {
	m.freeze_balance = nil
	m.addfreeze_balance = nil
}

// SetFreezeIntegral sets the "freeze_integral" field.
func (m *AccountWalletMutation) SetFreezeIntegral(i int32) {
	m.freeze_integral = &i
	m.addfreeze_integral = nil
}

// FreezeIntegral returns the value of the "freeze_integral" field in the mutation.
func (m *AccountWalletMutation) FreezeIntegral() (r int32, exists bool) {
	v := m.freeze_integral
	if v == nil {
		return
	}
	return *v, true
}

// OldFreezeIntegral returns the old "freeze_integral" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldFreezeIntegral(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFreezeIntegral is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFreezeIntegral requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFreezeIntegral: %w", err)
	}
	return oldValue.FreezeIntegral, nil
}

// AddFreezeIntegral adds i to the "freeze_integral" field.
func (m *AccountWalletMutation) AddFreezeIntegral(i int32) {
	if m.addfreeze_integral != nil {
		*m.addfreeze_integral += i
	} else {
		m.addfreeze_integral = &i
	}
}

// AddedFreezeIntegral returns the value that was added to the "freeze_integral" field in this mutation.
func (m *AccountWalletMutation) AddedFreezeIntegral() (r int32, exists bool) {
	v := m.addfreeze_integral
	if v == nil {
		return
	}
	return *v, true
}

// ClearFreezeIntegral clears the value of the "freeze_integral" field.
func (m *AccountWalletMutation) ClearFreezeIntegral() {
	m.freeze_integral = nil
	m.addfreeze_integral = nil
	m.clearedFields[accountwallet.FieldFreezeIntegral] = struct{}{}
}

// FreezeIntegralCleared returns if the "freeze_integral" field was cleared in this mutation.
func (m *AccountWalletMutation) FreezeIntegralCleared() bool {
	_, ok := m.clearedFields[accountwallet.FieldFreezeIntegral]
	return ok
}

// ResetFreezeIntegral resets all changes to the "freeze_integral" field.
func (m *AccountWalletMutation) ResetFreezeIntegral() {
	m.freeze_integral = nil
	m.addfreeze_integral = nil
	delete(m.clearedFields, accountwallet.FieldFreezeIntegral)
}

// SetOpenInstallment sets the "open_installment" field.
func (m *AccountWalletMutation) SetOpenInstallment(i int8) {
	m.open_installment = &i
	m.addopen_installment = nil
}

// OpenInstallment returns the value of the "open_installment" field in the mutation.
func (m *AccountWalletMutation) OpenInstallment() (r int8, exists bool) {
	v := m.open_installment
	if v == nil {
		return
	}
	return *v, true
}

// OldOpenInstallment returns the old "open_installment" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldOpenInstallment(ctx context.Context) (v int8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOpenInstallment is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOpenInstallment requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOpenInstallment: %w", err)
	}
	return oldValue.OpenInstallment, nil
}

// AddOpenInstallment adds i to the "open_installment" field.
func (m *AccountWalletMutation) AddOpenInstallment(i int8) {
	if m.addopen_installment != nil {
		*m.addopen_installment += i
	} else {
		m.addopen_installment = &i
	}
}

// AddedOpenInstallment returns the value that was added to the "open_installment" field in this mutation.
func (m *AccountWalletMutation) AddedOpenInstallment() (r int8, exists bool) {
	v := m.addopen_installment
	if v == nil {
		return
	}
	return *v, true
}

// ResetOpenInstallment resets all changes to the "open_installment" field.
func (m *AccountWalletMutation) ResetOpenInstallment() {
	m.open_installment = nil
	m.addopen_installment = nil
}

// SetStatus sets the "status" field.
func (m *AccountWalletMutation) SetStatus(i int8) {
	m.status = &i
	m.addstatus = nil
}

// Status returns the value of the "status" field in the mutation.
func (m *AccountWalletMutation) Status() (r int8, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldStatus(ctx context.Context) (v int8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// AddStatus adds i to the "status" field.
func (m *AccountWalletMutation) AddStatus(i int8) {
	if m.addstatus != nil {
		*m.addstatus += i
	} else {
		m.addstatus = &i
	}
}

// AddedStatus returns the value that was added to the "status" field in this mutation.
func (m *AccountWalletMutation) AddedStatus() (r int8, exists bool) {
	v := m.addstatus
	if v == nil {
		return
	}
	return *v, true
}

// ClearStatus clears the value of the "status" field.
func (m *AccountWalletMutation) ClearStatus() {
	m.status = nil
	m.addstatus = nil
	m.clearedFields[accountwallet.FieldStatus] = struct{}{}
}

// StatusCleared returns if the "status" field was cleared in this mutation.
func (m *AccountWalletMutation) StatusCleared() bool {
	_, ok := m.clearedFields[accountwallet.FieldStatus]
	return ok
}

// ResetStatus resets all changes to the "status" field.
func (m *AccountWalletMutation) ResetStatus() {
	m.status = nil
	m.addstatus = nil
	delete(m.clearedFields, accountwallet.FieldStatus)
}

// SetState sets the "state" field.
func (m *AccountWalletMutation) SetState(i int8) {
	m.state = &i
	m.addstate = nil
}

// State returns the value of the "state" field in the mutation.
func (m *AccountWalletMutation) State() (r int8, exists bool) {
	v := m.state
	if v == nil {
		return
	}
	return *v, true
}

// OldState returns the old "state" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldState(ctx context.Context) (v int8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldState: %w", err)
	}
	return oldValue.State, nil
}

// AddState adds i to the "state" field.
func (m *AccountWalletMutation) AddState(i int8) {
	if m.addstate != nil {
		*m.addstate += i
	} else {
		m.addstate = &i
	}
}

// AddedState returns the value that was added to the "state" field in this mutation.
func (m *AccountWalletMutation) AddedState() (r int8, exists bool) {
	v := m.addstate
	if v == nil {
		return
	}
	return *v, true
}

// ClearState clears the value of the "state" field.
func (m *AccountWalletMutation) ClearState() {
	m.state = nil
	m.addstate = nil
	m.clearedFields[accountwallet.FieldState] = struct{}{}
}

// StateCleared returns if the "state" field was cleared in this mutation.
func (m *AccountWalletMutation) StateCleared() bool {
	_, ok := m.clearedFields[accountwallet.FieldState]
	return ok
}

// ResetState resets all changes to the "state" field.
func (m *AccountWalletMutation) ResetState() {
	m.state = nil
	m.addstate = nil
	delete(m.clearedFields, accountwallet.FieldState)
}

// SetCreatedAt sets the "created_at" field.
func (m *AccountWalletMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AccountWalletMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ClearCreatedAt clears the value of the "created_at" field.
func (m *AccountWalletMutation) ClearCreatedAt() {
	m.created_at = nil
	m.clearedFields[accountwallet.FieldCreatedAt] = struct{}{}
}

// CreatedAtCleared returns if the "created_at" field was cleared in this mutation.
func (m *AccountWalletMutation) CreatedAtCleared() bool {
	_, ok := m.clearedFields[accountwallet.FieldCreatedAt]
	return ok
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AccountWalletMutation) ResetCreatedAt() {
	m.created_at = nil
	delete(m.clearedFields, accountwallet.FieldCreatedAt)
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AccountWalletMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AccountWalletMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the AccountWallet entity.
// If the AccountWallet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountWalletMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (m *AccountWalletMutation) ClearUpdatedAt() {
	m.updated_at = nil
	m.clearedFields[accountwallet.FieldUpdatedAt] = struct{}{}
}

// UpdatedAtCleared returns if the "updated_at" field was cleared in this mutation.
func (m *AccountWalletMutation) UpdatedAtCleared() bool {
	_, ok := m.clearedFields[accountwallet.FieldUpdatedAt]
	return ok
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AccountWalletMutation) ResetUpdatedAt() {
	m.updated_at = nil
	delete(m.clearedFields, accountwallet.FieldUpdatedAt)
}

// Where appends a list predicates to the AccountWalletMutation builder.
func (m *AccountWalletMutation) Where(ps ...predicate.AccountWallet) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AccountWalletMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AccountWalletMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AccountWallet, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AccountWalletMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AccountWalletMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AccountWallet).
func (m *AccountWalletMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AccountWalletMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.tenant_id != nil {
		fields = append(fields, accountwallet.FieldTenantID)
	}
	if m.account_id != nil {
		fields = append(fields, accountwallet.FieldAccountID)
	}
	if m.account_integral != nil {
		fields = append(fields, accountwallet.FieldAccountIntegral)
	}
	if m.account_balance != nil {
		fields = append(fields, accountwallet.FieldAccountBalance)
	}
	if m.freeze_balance != nil {
		fields = append(fields, accountwallet.FieldFreezeBalance)
	}
	if m.freeze_integral != nil {
		fields = append(fields, accountwallet.FieldFreezeIntegral)
	}
	if m.open_installment != nil {
		fields = append(fields, accountwallet.FieldOpenInstallment)
	}
	if m.status != nil {
		fields = append(fields, accountwallet.FieldStatus)
	}
	if m.state != nil {
		fields = append(fields, accountwallet.FieldState)
	}
	if m.created_at != nil {
		fields = append(fields, accountwallet.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, accountwallet.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AccountWalletMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case accountwallet.FieldTenantID:
		return m.TenantID()
	case accountwallet.FieldAccountID:
		return m.AccountID()
	case accountwallet.FieldAccountIntegral:
		return m.AccountIntegral()
	case accountwallet.FieldAccountBalance:
		return m.AccountBalance()
	case accountwallet.FieldFreezeBalance:
		return m.FreezeBalance()
	case accountwallet.FieldFreezeIntegral:
		return m.FreezeIntegral()
	case accountwallet.FieldOpenInstallment:
		return m.OpenInstallment()
	case accountwallet.FieldStatus:
		return m.Status()
	case accountwallet.FieldState:
		return m.State()
	case accountwallet.FieldCreatedAt:
		return m.CreatedAt()
	case accountwallet.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AccountWalletMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case accountwallet.FieldTenantID:
		return m.OldTenantID(ctx)
	case accountwallet.FieldAccountID:
		return m.OldAccountID(ctx)
	case accountwallet.FieldAccountIntegral:
		return m.OldAccountIntegral(ctx)
	case accountwallet.FieldAccountBalance:
		return m.OldAccountBalance(ctx)
	case accountwallet.FieldFreezeBalance:
		return m.OldFreezeBalance(ctx)
	case accountwallet.FieldFreezeIntegral:
		return m.OldFreezeIntegral(ctx)
	case accountwallet.FieldOpenInstallment:
		return m.OldOpenInstallment(ctx)
	case accountwallet.FieldStatus:
		return m.OldStatus(ctx)
	case accountwallet.FieldState:
		return m.OldState(ctx)
	case accountwallet.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case accountwallet.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown AccountWallet field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AccountWalletMutation) SetField(name string, value ent.Value) error {
	switch name {
	case accountwallet.FieldTenantID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case accountwallet.FieldAccountID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountID(v)
		return nil
	case accountwallet.FieldAccountIntegral:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountIntegral(v)
		return nil
	case accountwallet.FieldAccountBalance:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountBalance(v)
		return nil
	case accountwallet.FieldFreezeBalance:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFreezeBalance(v)
		return nil
	case accountwallet.FieldFreezeIntegral:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFreezeIntegral(v)
		return nil
	case accountwallet.FieldOpenInstallment:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOpenInstallment(v)
		return nil
	case accountwallet.FieldStatus:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case accountwallet.FieldState:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetState(v)
		return nil
	case accountwallet.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case accountwallet.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown AccountWallet field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AccountWalletMutation) AddedFields() []string {
	var fields []string
	if m.addtenant_id != nil {
		fields = append(fields, accountwallet.FieldTenantID)
	}
	if m.addaccount_id != nil {
		fields = append(fields, accountwallet.FieldAccountID)
	}
	if m.addaccount_integral != nil {
		fields = append(fields, accountwallet.FieldAccountIntegral)
	}
	if m.addaccount_balance != nil {
		fields = append(fields, accountwallet.FieldAccountBalance)
	}
	if m.addfreeze_balance != nil {
		fields = append(fields, accountwallet.FieldFreezeBalance)
	}
	if m.addfreeze_integral != nil {
		fields = append(fields, accountwallet.FieldFreezeIntegral)
	}
	if m.addopen_installment != nil {
		fields = append(fields, accountwallet.FieldOpenInstallment)
	}
	if m.addstatus != nil {
		fields = append(fields, accountwallet.FieldStatus)
	}
	if m.addstate != nil {
		fields = append(fields, accountwallet.FieldState)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AccountWalletMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case accountwallet.FieldTenantID:
		return m.AddedTenantID()
	case accountwallet.FieldAccountID:
		return m.AddedAccountID()
	case accountwallet.FieldAccountIntegral:
		return m.AddedAccountIntegral()
	case accountwallet.FieldAccountBalance:
		return m.AddedAccountBalance()
	case accountwallet.FieldFreezeBalance:
		return m.AddedFreezeBalance()
	case accountwallet.FieldFreezeIntegral:
		return m.AddedFreezeIntegral()
	case accountwallet.FieldOpenInstallment:
		return m.AddedOpenInstallment()
	case accountwallet.FieldStatus:
		return m.AddedStatus()
	case accountwallet.FieldState:
		return m.AddedState()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AccountWalletMutation) AddField(name string, value ent.Value) error {
	switch name {
	case accountwallet.FieldTenantID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTenantID(v)
		return nil
	case accountwallet.FieldAccountID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAccountID(v)
		return nil
	case accountwallet.FieldAccountIntegral:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAccountIntegral(v)
		return nil
	case accountwallet.FieldAccountBalance:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAccountBalance(v)
		return nil
	case accountwallet.FieldFreezeBalance:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFreezeBalance(v)
		return nil
	case accountwallet.FieldFreezeIntegral:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFreezeIntegral(v)
		return nil
	case accountwallet.FieldOpenInstallment:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOpenInstallment(v)
		return nil
	case accountwallet.FieldStatus:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatus(v)
		return nil
	case accountwallet.FieldState:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddState(v)
		return nil
	}
	return fmt.Errorf("unknown AccountWallet numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AccountWalletMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(accountwallet.FieldAccountID) {
		fields = append(fields, accountwallet.FieldAccountID)
	}
	if m.FieldCleared(accountwallet.FieldAccountIntegral) {
		fields = append(fields, accountwallet.FieldAccountIntegral)
	}
	if m.FieldCleared(accountwallet.FieldAccountBalance) {
		fields = append(fields, accountwallet.FieldAccountBalance)
	}
	if m.FieldCleared(accountwallet.FieldFreezeIntegral) {
		fields = append(fields, accountwallet.FieldFreezeIntegral)
	}
	if m.FieldCleared(accountwallet.FieldStatus) {
		fields = append(fields, accountwallet.FieldStatus)
	}
	if m.FieldCleared(accountwallet.FieldState) {
		fields = append(fields, accountwallet.FieldState)
	}
	if m.FieldCleared(accountwallet.FieldCreatedAt) {
		fields = append(fields, accountwallet.FieldCreatedAt)
	}
	if m.FieldCleared(accountwallet.FieldUpdatedAt) {
		fields = append(fields, accountwallet.FieldUpdatedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AccountWalletMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AccountWalletMutation) ClearField(name string) error {
	switch name {
	case accountwallet.FieldAccountID:
		m.ClearAccountID()
		return nil
	case accountwallet.FieldAccountIntegral:
		m.ClearAccountIntegral()
		return nil
	case accountwallet.FieldAccountBalance:
		m.ClearAccountBalance()
		return nil
	case accountwallet.FieldFreezeIntegral:
		m.ClearFreezeIntegral()
		return nil
	case accountwallet.FieldStatus:
		m.ClearStatus()
		return nil
	case accountwallet.FieldState:
		m.ClearState()
		return nil
	case accountwallet.FieldCreatedAt:
		m.ClearCreatedAt()
		return nil
	case accountwallet.FieldUpdatedAt:
		m.ClearUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown AccountWallet nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AccountWalletMutation) ResetField(name string) error {
	switch name {
	case accountwallet.FieldTenantID:
		m.ResetTenantID()
		return nil
	case accountwallet.FieldAccountID:
		m.ResetAccountID()
		return nil
	case accountwallet.FieldAccountIntegral:
		m.ResetAccountIntegral()
		return nil
	case accountwallet.FieldAccountBalance:
		m.ResetAccountBalance()
		return nil
	case accountwallet.FieldFreezeBalance:
		m.ResetFreezeBalance()
		return nil
	case accountwallet.FieldFreezeIntegral:
		m.ResetFreezeIntegral()
		return nil
	case accountwallet.FieldOpenInstallment:
		m.ResetOpenInstallment()
		return nil
	case accountwallet.FieldStatus:
		m.ResetStatus()
		return nil
	case accountwallet.FieldState:
		m.ResetState()
		return nil
	case accountwallet.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case accountwallet.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown AccountWallet field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AccountWalletMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AccountWalletMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AccountWalletMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AccountWalletMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AccountWalletMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AccountWalletMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AccountWalletMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AccountWallet unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AccountWalletMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AccountWallet edge %s", name)
}
