// Code generated by ent, DO NOT EDIT.

package account

import (
	"go-study/app/database/account/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int32) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int32) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int32) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int32) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int32) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int32) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int32) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int32) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int32) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int32) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldTenantID, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// AccountIntegral applies equality check predicate on the "account_integral" field. It's identical to AccountIntegralEQ.
func AccountIntegral(v int32) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAccountIntegral, v))
}

// AccountBalance applies equality check predicate on the "account_balance" field. It's identical to AccountBalanceEQ.
func AccountBalance(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAccountBalance, v))
}

// UserIdentity applies equality check predicate on the "user_identity" field. It's identical to UserIdentityEQ.
func UserIdentity(v int8) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUserIdentity, v))
}

// FreezeBalance applies equality check predicate on the "freeze_balance" field. It's identical to FreezeBalanceEQ.
func FreezeBalance(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldFreezeBalance, v))
}

// FreezeIntegral applies equality check predicate on the "freeze_integral" field. It's identical to FreezeIntegralEQ.
func FreezeIntegral(v int32) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldFreezeIntegral, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int32) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int32) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int32) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int32) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int32) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int32) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int32) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int32) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldTenantID, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldUpdatedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldCreatedAt))
}

// AccountIntegralEQ applies the EQ predicate on the "account_integral" field.
func AccountIntegralEQ(v int32) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAccountIntegral, v))
}

// AccountIntegralNEQ applies the NEQ predicate on the "account_integral" field.
func AccountIntegralNEQ(v int32) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldAccountIntegral, v))
}

// AccountIntegralIn applies the In predicate on the "account_integral" field.
func AccountIntegralIn(vs ...int32) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldAccountIntegral, vs...))
}

// AccountIntegralNotIn applies the NotIn predicate on the "account_integral" field.
func AccountIntegralNotIn(vs ...int32) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldAccountIntegral, vs...))
}

// AccountIntegralGT applies the GT predicate on the "account_integral" field.
func AccountIntegralGT(v int32) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldAccountIntegral, v))
}

// AccountIntegralGTE applies the GTE predicate on the "account_integral" field.
func AccountIntegralGTE(v int32) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldAccountIntegral, v))
}

// AccountIntegralLT applies the LT predicate on the "account_integral" field.
func AccountIntegralLT(v int32) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldAccountIntegral, v))
}

// AccountIntegralLTE applies the LTE predicate on the "account_integral" field.
func AccountIntegralLTE(v int32) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldAccountIntegral, v))
}

// AccountIntegralIsNil applies the IsNil predicate on the "account_integral" field.
func AccountIntegralIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldAccountIntegral))
}

// AccountIntegralNotNil applies the NotNil predicate on the "account_integral" field.
func AccountIntegralNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldAccountIntegral))
}

// AccountBalanceEQ applies the EQ predicate on the "account_balance" field.
func AccountBalanceEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAccountBalance, v))
}

// AccountBalanceNEQ applies the NEQ predicate on the "account_balance" field.
func AccountBalanceNEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldAccountBalance, v))
}

// AccountBalanceIn applies the In predicate on the "account_balance" field.
func AccountBalanceIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldAccountBalance, vs...))
}

// AccountBalanceNotIn applies the NotIn predicate on the "account_balance" field.
func AccountBalanceNotIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldAccountBalance, vs...))
}

// AccountBalanceGT applies the GT predicate on the "account_balance" field.
func AccountBalanceGT(v float64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldAccountBalance, v))
}

// AccountBalanceGTE applies the GTE predicate on the "account_balance" field.
func AccountBalanceGTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldAccountBalance, v))
}

// AccountBalanceLT applies the LT predicate on the "account_balance" field.
func AccountBalanceLT(v float64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldAccountBalance, v))
}

// AccountBalanceLTE applies the LTE predicate on the "account_balance" field.
func AccountBalanceLTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldAccountBalance, v))
}

// AccountBalanceIsNil applies the IsNil predicate on the "account_balance" field.
func AccountBalanceIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldAccountBalance))
}

// AccountBalanceNotNil applies the NotNil predicate on the "account_balance" field.
func AccountBalanceNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldAccountBalance))
}

// UserIdentityEQ applies the EQ predicate on the "user_identity" field.
func UserIdentityEQ(v int8) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUserIdentity, v))
}

// UserIdentityNEQ applies the NEQ predicate on the "user_identity" field.
func UserIdentityNEQ(v int8) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUserIdentity, v))
}

// UserIdentityIn applies the In predicate on the "user_identity" field.
func UserIdentityIn(vs ...int8) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUserIdentity, vs...))
}

// UserIdentityNotIn applies the NotIn predicate on the "user_identity" field.
func UserIdentityNotIn(vs ...int8) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUserIdentity, vs...))
}

// UserIdentityGT applies the GT predicate on the "user_identity" field.
func UserIdentityGT(v int8) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUserIdentity, v))
}

// UserIdentityGTE applies the GTE predicate on the "user_identity" field.
func UserIdentityGTE(v int8) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUserIdentity, v))
}

// UserIdentityLT applies the LT predicate on the "user_identity" field.
func UserIdentityLT(v int8) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUserIdentity, v))
}

// UserIdentityLTE applies the LTE predicate on the "user_identity" field.
func UserIdentityLTE(v int8) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUserIdentity, v))
}

// FreezeBalanceEQ applies the EQ predicate on the "freeze_balance" field.
func FreezeBalanceEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldFreezeBalance, v))
}

// FreezeBalanceNEQ applies the NEQ predicate on the "freeze_balance" field.
func FreezeBalanceNEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldFreezeBalance, v))
}

// FreezeBalanceIn applies the In predicate on the "freeze_balance" field.
func FreezeBalanceIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldFreezeBalance, vs...))
}

// FreezeBalanceNotIn applies the NotIn predicate on the "freeze_balance" field.
func FreezeBalanceNotIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldFreezeBalance, vs...))
}

// FreezeBalanceGT applies the GT predicate on the "freeze_balance" field.
func FreezeBalanceGT(v float64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldFreezeBalance, v))
}

// FreezeBalanceGTE applies the GTE predicate on the "freeze_balance" field.
func FreezeBalanceGTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldFreezeBalance, v))
}

// FreezeBalanceLT applies the LT predicate on the "freeze_balance" field.
func FreezeBalanceLT(v float64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldFreezeBalance, v))
}

// FreezeBalanceLTE applies the LTE predicate on the "freeze_balance" field.
func FreezeBalanceLTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldFreezeBalance, v))
}

// FreezeBalanceIsNil applies the IsNil predicate on the "freeze_balance" field.
func FreezeBalanceIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldFreezeBalance))
}

// FreezeBalanceNotNil applies the NotNil predicate on the "freeze_balance" field.
func FreezeBalanceNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldFreezeBalance))
}

// FreezeIntegralEQ applies the EQ predicate on the "freeze_integral" field.
func FreezeIntegralEQ(v int32) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldFreezeIntegral, v))
}

// FreezeIntegralNEQ applies the NEQ predicate on the "freeze_integral" field.
func FreezeIntegralNEQ(v int32) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldFreezeIntegral, v))
}

// FreezeIntegralIn applies the In predicate on the "freeze_integral" field.
func FreezeIntegralIn(vs ...int32) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldFreezeIntegral, vs...))
}

// FreezeIntegralNotIn applies the NotIn predicate on the "freeze_integral" field.
func FreezeIntegralNotIn(vs ...int32) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldFreezeIntegral, vs...))
}

// FreezeIntegralGT applies the GT predicate on the "freeze_integral" field.
func FreezeIntegralGT(v int32) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldFreezeIntegral, v))
}

// FreezeIntegralGTE applies the GTE predicate on the "freeze_integral" field.
func FreezeIntegralGTE(v int32) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldFreezeIntegral, v))
}

// FreezeIntegralLT applies the LT predicate on the "freeze_integral" field.
func FreezeIntegralLT(v int32) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldFreezeIntegral, v))
}

// FreezeIntegralLTE applies the LTE predicate on the "freeze_integral" field.
func FreezeIntegralLTE(v int32) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldFreezeIntegral, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(sql.NotPredicates(p))
}
