// Code generated by ent, DO NOT EDIT.

package projectactionrecord

import (
	"go-study/app/database/tabtaba/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldTenantID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldProjectID, v))
}

// ActionPlat applies equality check predicate on the "action_plat" field. It's identical to ActionPlatEQ.
func ActionPlat(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldActionPlat, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldAction, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldAccountID, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldAccountName, v))
}

// ProjectStatus applies equality check predicate on the "project_status" field. It's identical to ProjectStatusEQ.
func ProjectStatus(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldProjectStatus, v))
}

// ProjectStatusText applies equality check predicate on the "project_status_text" field. It's identical to ProjectStatusTextEQ.
func ProjectStatusText(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldProjectStatusText, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldTenantID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldProjectID, v))
}

// ActionPlatEQ applies the EQ predicate on the "action_plat" field.
func ActionPlatEQ(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldActionPlat, v))
}

// ActionPlatNEQ applies the NEQ predicate on the "action_plat" field.
func ActionPlatNEQ(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldActionPlat, v))
}

// ActionPlatIn applies the In predicate on the "action_plat" field.
func ActionPlatIn(vs ...int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldActionPlat, vs...))
}

// ActionPlatNotIn applies the NotIn predicate on the "action_plat" field.
func ActionPlatNotIn(vs ...int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldActionPlat, vs...))
}

// ActionPlatGT applies the GT predicate on the "action_plat" field.
func ActionPlatGT(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldActionPlat, v))
}

// ActionPlatGTE applies the GTE predicate on the "action_plat" field.
func ActionPlatGTE(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldActionPlat, v))
}

// ActionPlatLT applies the LT predicate on the "action_plat" field.
func ActionPlatLT(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldActionPlat, v))
}

// ActionPlatLTE applies the LTE predicate on the "action_plat" field.
func ActionPlatLTE(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldActionPlat, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldContainsFold(FieldAction, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotNull(FieldAccountID))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameIsNil applies the IsNil predicate on the "account_name" field.
func AccountNameIsNil() predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIsNull(FieldAccountName))
}

// AccountNameNotNil applies the NotNil predicate on the "account_name" field.
func AccountNameNotNil() predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotNull(FieldAccountName))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldContainsFold(FieldAccountName, v))
}

// ProjectStatusEQ applies the EQ predicate on the "project_status" field.
func ProjectStatusEQ(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldProjectStatus, v))
}

// ProjectStatusNEQ applies the NEQ predicate on the "project_status" field.
func ProjectStatusNEQ(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldProjectStatus, v))
}

// ProjectStatusIn applies the In predicate on the "project_status" field.
func ProjectStatusIn(vs ...int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldProjectStatus, vs...))
}

// ProjectStatusNotIn applies the NotIn predicate on the "project_status" field.
func ProjectStatusNotIn(vs ...int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldProjectStatus, vs...))
}

// ProjectStatusGT applies the GT predicate on the "project_status" field.
func ProjectStatusGT(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldProjectStatus, v))
}

// ProjectStatusGTE applies the GTE predicate on the "project_status" field.
func ProjectStatusGTE(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldProjectStatus, v))
}

// ProjectStatusLT applies the LT predicate on the "project_status" field.
func ProjectStatusLT(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldProjectStatus, v))
}

// ProjectStatusLTE applies the LTE predicate on the "project_status" field.
func ProjectStatusLTE(v int32) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldProjectStatus, v))
}

// ProjectStatusTextEQ applies the EQ predicate on the "project_status_text" field.
func ProjectStatusTextEQ(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldProjectStatusText, v))
}

// ProjectStatusTextNEQ applies the NEQ predicate on the "project_status_text" field.
func ProjectStatusTextNEQ(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldProjectStatusText, v))
}

// ProjectStatusTextIn applies the In predicate on the "project_status_text" field.
func ProjectStatusTextIn(vs ...string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldProjectStatusText, vs...))
}

// ProjectStatusTextNotIn applies the NotIn predicate on the "project_status_text" field.
func ProjectStatusTextNotIn(vs ...string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldProjectStatusText, vs...))
}

// ProjectStatusTextGT applies the GT predicate on the "project_status_text" field.
func ProjectStatusTextGT(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldProjectStatusText, v))
}

// ProjectStatusTextGTE applies the GTE predicate on the "project_status_text" field.
func ProjectStatusTextGTE(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldProjectStatusText, v))
}

// ProjectStatusTextLT applies the LT predicate on the "project_status_text" field.
func ProjectStatusTextLT(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldProjectStatusText, v))
}

// ProjectStatusTextLTE applies the LTE predicate on the "project_status_text" field.
func ProjectStatusTextLTE(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldProjectStatusText, v))
}

// ProjectStatusTextContains applies the Contains predicate on the "project_status_text" field.
func ProjectStatusTextContains(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldContains(FieldProjectStatusText, v))
}

// ProjectStatusTextHasPrefix applies the HasPrefix predicate on the "project_status_text" field.
func ProjectStatusTextHasPrefix(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldHasPrefix(FieldProjectStatusText, v))
}

// ProjectStatusTextHasSuffix applies the HasSuffix predicate on the "project_status_text" field.
func ProjectStatusTextHasSuffix(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldHasSuffix(FieldProjectStatusText, v))
}

// ProjectStatusTextEqualFold applies the EqualFold predicate on the "project_status_text" field.
func ProjectStatusTextEqualFold(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEqualFold(FieldProjectStatusText, v))
}

// ProjectStatusTextContainsFold applies the ContainsFold predicate on the "project_status_text" field.
func ProjectStatusTextContainsFold(v string) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldContainsFold(FieldProjectStatusText, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotNull(FieldStatus))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectActionRecord) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectActionRecord) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectActionRecord) predicate.ProjectActionRecord {
	return predicate.ProjectActionRecord(sql.NotPredicates(p))
}
