// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"go-study/app/database/tabtaba/internal/data/ent/migrate"

	"go-study/app/database/tabtaba/internal/data/ent/finance"
	"go-study/app/database/tabtaba/internal/data/ent/project"
	"go-study/app/database/tabtaba/internal/data/ent/projectactionrecord"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Finance is the client for interacting with the Finance builders.
	Finance *FinanceClient
	// Project is the client for interacting with the Project builders.
	Project *ProjectClient
	// ProjectActionRecord is the client for interacting with the ProjectActionRecord builders.
	ProjectActionRecord *ProjectActionRecordClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Finance = NewFinanceClient(c.config)
	c.Project = NewProjectClient(c.config)
	c.ProjectActionRecord = NewProjectActionRecordClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		Finance:             NewFinanceClient(cfg),
		Project:             NewProjectClient(cfg),
		ProjectActionRecord: NewProjectActionRecordClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		Finance:             NewFinanceClient(cfg),
		Project:             NewProjectClient(cfg),
		ProjectActionRecord: NewProjectActionRecordClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Finance.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Finance.Use(hooks...)
	c.Project.Use(hooks...)
	c.ProjectActionRecord.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Finance.Intercept(interceptors...)
	c.Project.Intercept(interceptors...)
	c.ProjectActionRecord.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *FinanceMutation:
		return c.Finance.mutate(ctx, m)
	case *ProjectMutation:
		return c.Project.mutate(ctx, m)
	case *ProjectActionRecordMutation:
		return c.ProjectActionRecord.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// FinanceClient is a client for the Finance schema.
type FinanceClient struct {
	config
}

// NewFinanceClient returns a client for the Finance from the given config.
func NewFinanceClient(c config) *FinanceClient {
	return &FinanceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `finance.Hooks(f(g(h())))`.
func (c *FinanceClient) Use(hooks ...Hook) {
	c.hooks.Finance = append(c.hooks.Finance, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `finance.Intercept(f(g(h())))`.
func (c *FinanceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Finance = append(c.inters.Finance, interceptors...)
}

// Create returns a builder for creating a Finance entity.
func (c *FinanceClient) Create() *FinanceCreate {
	mutation := newFinanceMutation(c.config, OpCreate)
	return &FinanceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Finance entities.
func (c *FinanceClient) CreateBulk(builders ...*FinanceCreate) *FinanceCreateBulk {
	return &FinanceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FinanceClient) MapCreateBulk(slice any, setFunc func(*FinanceCreate, int)) *FinanceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FinanceCreateBulk{err: fmt.Errorf("calling to FinanceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FinanceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FinanceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Finance.
func (c *FinanceClient) Update() *FinanceUpdate {
	mutation := newFinanceMutation(c.config, OpUpdate)
	return &FinanceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FinanceClient) UpdateOne(f *Finance) *FinanceUpdateOne {
	mutation := newFinanceMutation(c.config, OpUpdateOne, withFinance(f))
	return &FinanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FinanceClient) UpdateOneID(id int32) *FinanceUpdateOne {
	mutation := newFinanceMutation(c.config, OpUpdateOne, withFinanceID(id))
	return &FinanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Finance.
func (c *FinanceClient) Delete() *FinanceDelete {
	mutation := newFinanceMutation(c.config, OpDelete)
	return &FinanceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FinanceClient) DeleteOne(f *Finance) *FinanceDeleteOne {
	return c.DeleteOneID(f.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FinanceClient) DeleteOneID(id int32) *FinanceDeleteOne {
	builder := c.Delete().Where(finance.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FinanceDeleteOne{builder}
}

// Query returns a query builder for Finance.
func (c *FinanceClient) Query() *FinanceQuery {
	return &FinanceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFinance},
		inters: c.Interceptors(),
	}
}

// Get returns a Finance entity by its id.
func (c *FinanceClient) Get(ctx context.Context, id int32) (*Finance, error) {
	return c.Query().Where(finance.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FinanceClient) GetX(ctx context.Context, id int32) *Finance {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FinanceClient) Hooks() []Hook {
	return c.hooks.Finance
}

// Interceptors returns the client interceptors.
func (c *FinanceClient) Interceptors() []Interceptor {
	return c.inters.Finance
}

func (c *FinanceClient) mutate(ctx context.Context, m *FinanceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FinanceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FinanceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FinanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FinanceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Finance mutation op: %q", m.Op())
	}
}

// ProjectClient is a client for the Project schema.
type ProjectClient struct {
	config
}

// NewProjectClient returns a client for the Project from the given config.
func NewProjectClient(c config) *ProjectClient {
	return &ProjectClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `project.Hooks(f(g(h())))`.
func (c *ProjectClient) Use(hooks ...Hook) {
	c.hooks.Project = append(c.hooks.Project, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `project.Intercept(f(g(h())))`.
func (c *ProjectClient) Intercept(interceptors ...Interceptor) {
	c.inters.Project = append(c.inters.Project, interceptors...)
}

// Create returns a builder for creating a Project entity.
func (c *ProjectClient) Create() *ProjectCreate {
	mutation := newProjectMutation(c.config, OpCreate)
	return &ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Project entities.
func (c *ProjectClient) CreateBulk(builders ...*ProjectCreate) *ProjectCreateBulk {
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectClient) MapCreateBulk(slice any, setFunc func(*ProjectCreate, int)) *ProjectCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectCreateBulk{err: fmt.Errorf("calling to ProjectClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Project.
func (c *ProjectClient) Update() *ProjectUpdate {
	mutation := newProjectMutation(c.config, OpUpdate)
	return &ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectClient) UpdateOne(pr *Project) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProject(pr))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectClient) UpdateOneID(id int32) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProjectID(id))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Project.
func (c *ProjectClient) Delete() *ProjectDelete {
	mutation := newProjectMutation(c.config, OpDelete)
	return &ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectClient) DeleteOne(pr *Project) *ProjectDeleteOne {
	return c.DeleteOneID(pr.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectClient) DeleteOneID(id int32) *ProjectDeleteOne {
	builder := c.Delete().Where(project.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectDeleteOne{builder}
}

// Query returns a query builder for Project.
func (c *ProjectClient) Query() *ProjectQuery {
	return &ProjectQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProject},
		inters: c.Interceptors(),
	}
}

// Get returns a Project entity by its id.
func (c *ProjectClient) Get(ctx context.Context, id int32) (*Project, error) {
	return c.Query().Where(project.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectClient) GetX(ctx context.Context, id int32) *Project {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ProjectClient) Hooks() []Hook {
	return c.hooks.Project
}

// Interceptors returns the client interceptors.
func (c *ProjectClient) Interceptors() []Interceptor {
	return c.inters.Project
}

func (c *ProjectClient) mutate(ctx context.Context, m *ProjectMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Project mutation op: %q", m.Op())
	}
}

// ProjectActionRecordClient is a client for the ProjectActionRecord schema.
type ProjectActionRecordClient struct {
	config
}

// NewProjectActionRecordClient returns a client for the ProjectActionRecord from the given config.
func NewProjectActionRecordClient(c config) *ProjectActionRecordClient {
	return &ProjectActionRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `projectactionrecord.Hooks(f(g(h())))`.
func (c *ProjectActionRecordClient) Use(hooks ...Hook) {
	c.hooks.ProjectActionRecord = append(c.hooks.ProjectActionRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `projectactionrecord.Intercept(f(g(h())))`.
func (c *ProjectActionRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProjectActionRecord = append(c.inters.ProjectActionRecord, interceptors...)
}

// Create returns a builder for creating a ProjectActionRecord entity.
func (c *ProjectActionRecordClient) Create() *ProjectActionRecordCreate {
	mutation := newProjectActionRecordMutation(c.config, OpCreate)
	return &ProjectActionRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProjectActionRecord entities.
func (c *ProjectActionRecordClient) CreateBulk(builders ...*ProjectActionRecordCreate) *ProjectActionRecordCreateBulk {
	return &ProjectActionRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectActionRecordClient) MapCreateBulk(slice any, setFunc func(*ProjectActionRecordCreate, int)) *ProjectActionRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectActionRecordCreateBulk{err: fmt.Errorf("calling to ProjectActionRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectActionRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectActionRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProjectActionRecord.
func (c *ProjectActionRecordClient) Update() *ProjectActionRecordUpdate {
	mutation := newProjectActionRecordMutation(c.config, OpUpdate)
	return &ProjectActionRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectActionRecordClient) UpdateOne(par *ProjectActionRecord) *ProjectActionRecordUpdateOne {
	mutation := newProjectActionRecordMutation(c.config, OpUpdateOne, withProjectActionRecord(par))
	return &ProjectActionRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectActionRecordClient) UpdateOneID(id int32) *ProjectActionRecordUpdateOne {
	mutation := newProjectActionRecordMutation(c.config, OpUpdateOne, withProjectActionRecordID(id))
	return &ProjectActionRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProjectActionRecord.
func (c *ProjectActionRecordClient) Delete() *ProjectActionRecordDelete {
	mutation := newProjectActionRecordMutation(c.config, OpDelete)
	return &ProjectActionRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectActionRecordClient) DeleteOne(par *ProjectActionRecord) *ProjectActionRecordDeleteOne {
	return c.DeleteOneID(par.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectActionRecordClient) DeleteOneID(id int32) *ProjectActionRecordDeleteOne {
	builder := c.Delete().Where(projectactionrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectActionRecordDeleteOne{builder}
}

// Query returns a query builder for ProjectActionRecord.
func (c *ProjectActionRecordClient) Query() *ProjectActionRecordQuery {
	return &ProjectActionRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProjectActionRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a ProjectActionRecord entity by its id.
func (c *ProjectActionRecordClient) Get(ctx context.Context, id int32) (*ProjectActionRecord, error) {
	return c.Query().Where(projectactionrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectActionRecordClient) GetX(ctx context.Context, id int32) *ProjectActionRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ProjectActionRecordClient) Hooks() []Hook {
	return c.hooks.ProjectActionRecord
}

// Interceptors returns the client interceptors.
func (c *ProjectActionRecordClient) Interceptors() []Interceptor {
	return c.inters.ProjectActionRecord
}

func (c *ProjectActionRecordClient) mutate(ctx context.Context, m *ProjectActionRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectActionRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectActionRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectActionRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectActionRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ProjectActionRecord mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Finance, Project, ProjectActionRecord []ent.Hook
	}
	inters struct {
		Finance, Project, ProjectActionRecord []ent.Interceptor
	}
)
