// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-study/app/database/tabtaba/internal/data/ent/finance"
	"go-study/app/database/tabtaba/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FinanceUpdate is the builder for updating Finance entities.
type FinanceUpdate struct {
	config
	hooks     []Hook
	mutation  *FinanceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the FinanceUpdate builder.
func (fu *FinanceUpdate) Where(ps ...predicate.Finance) *FinanceUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetTenantID sets the "tenant_id" field.
func (fu *FinanceUpdate) SetTenantID(i int32) *FinanceUpdate {
	fu.mutation.ResetTenantID()
	fu.mutation.SetTenantID(i)
	return fu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableTenantID(i *int32) *FinanceUpdate {
	if i != nil {
		fu.SetTenantID(*i)
	}
	return fu
}

// AddTenantID adds i to the "tenant_id" field.
func (fu *FinanceUpdate) AddTenantID(i int32) *FinanceUpdate {
	fu.mutation.AddTenantID(i)
	return fu
}

// SetTransactNo sets the "transact_no" field.
func (fu *FinanceUpdate) SetTransactNo(s string) *FinanceUpdate {
	fu.mutation.SetTransactNo(s)
	return fu
}

// SetNillableTransactNo sets the "transact_no" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableTransactNo(s *string) *FinanceUpdate {
	if s != nil {
		fu.SetTransactNo(*s)
	}
	return fu
}

// SetOrderNo sets the "order_no" field.
func (fu *FinanceUpdate) SetOrderNo(s string) *FinanceUpdate {
	fu.mutation.SetOrderNo(s)
	return fu
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableOrderNo(s *string) *FinanceUpdate {
	if s != nil {
		fu.SetOrderNo(*s)
	}
	return fu
}

// SetProjectID sets the "project_id" field.
func (fu *FinanceUpdate) SetProjectID(i int32) *FinanceUpdate {
	fu.mutation.ResetProjectID()
	fu.mutation.SetProjectID(i)
	return fu
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableProjectID(i *int32) *FinanceUpdate {
	if i != nil {
		fu.SetProjectID(*i)
	}
	return fu
}

// AddProjectID adds i to the "project_id" field.
func (fu *FinanceUpdate) AddProjectID(i int32) *FinanceUpdate {
	fu.mutation.AddProjectID(i)
	return fu
}

// ClearProjectID clears the value of the "project_id" field.
func (fu *FinanceUpdate) ClearProjectID() *FinanceUpdate {
	fu.mutation.ClearProjectID()
	return fu
}

// SetAccountID sets the "account_id" field.
func (fu *FinanceUpdate) SetAccountID(i int32) *FinanceUpdate {
	fu.mutation.ResetAccountID()
	fu.mutation.SetAccountID(i)
	return fu
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableAccountID(i *int32) *FinanceUpdate {
	if i != nil {
		fu.SetAccountID(*i)
	}
	return fu
}

// AddAccountID adds i to the "account_id" field.
func (fu *FinanceUpdate) AddAccountID(i int32) *FinanceUpdate {
	fu.mutation.AddAccountID(i)
	return fu
}

// SetTheirAccountID sets the "their_account_id" field.
func (fu *FinanceUpdate) SetTheirAccountID(i int32) *FinanceUpdate {
	fu.mutation.ResetTheirAccountID()
	fu.mutation.SetTheirAccountID(i)
	return fu
}

// SetNillableTheirAccountID sets the "their_account_id" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableTheirAccountID(i *int32) *FinanceUpdate {
	if i != nil {
		fu.SetTheirAccountID(*i)
	}
	return fu
}

// AddTheirAccountID adds i to the "their_account_id" field.
func (fu *FinanceUpdate) AddTheirAccountID(i int32) *FinanceUpdate {
	fu.mutation.AddTheirAccountID(i)
	return fu
}

// SetTransactAt sets the "transact_at" field.
func (fu *FinanceUpdate) SetTransactAt(t time.Time) *FinanceUpdate {
	fu.mutation.SetTransactAt(t)
	return fu
}

// SetNillableTransactAt sets the "transact_at" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableTransactAt(t *time.Time) *FinanceUpdate {
	if t != nil {
		fu.SetTransactAt(*t)
	}
	return fu
}

// ClearTransactAt clears the value of the "transact_at" field.
func (fu *FinanceUpdate) ClearTransactAt() *FinanceUpdate {
	fu.mutation.ClearTransactAt()
	return fu
}

// SetWriteOffAt sets the "write_off_at" field.
func (fu *FinanceUpdate) SetWriteOffAt(t time.Time) *FinanceUpdate {
	fu.mutation.SetWriteOffAt(t)
	return fu
}

// SetNillableWriteOffAt sets the "write_off_at" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableWriteOffAt(t *time.Time) *FinanceUpdate {
	if t != nil {
		fu.SetWriteOffAt(*t)
	}
	return fu
}

// ClearWriteOffAt clears the value of the "write_off_at" field.
func (fu *FinanceUpdate) ClearWriteOffAt() *FinanceUpdate {
	fu.mutation.ClearWriteOffAt()
	return fu
}

// SetSummary sets the "summary" field.
func (fu *FinanceUpdate) SetSummary(s string) *FinanceUpdate {
	fu.mutation.SetSummary(s)
	return fu
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableSummary(s *string) *FinanceUpdate {
	if s != nil {
		fu.SetSummary(*s)
	}
	return fu
}

// ClearSummary clears the value of the "summary" field.
func (fu *FinanceUpdate) ClearSummary() *FinanceUpdate {
	fu.mutation.ClearSummary()
	return fu
}

// SetPayModeType sets the "pay_mode_type" field.
func (fu *FinanceUpdate) SetPayModeType(i int8) *FinanceUpdate {
	fu.mutation.ResetPayModeType()
	fu.mutation.SetPayModeType(i)
	return fu
}

// SetNillablePayModeType sets the "pay_mode_type" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillablePayModeType(i *int8) *FinanceUpdate {
	if i != nil {
		fu.SetPayModeType(*i)
	}
	return fu
}

// AddPayModeType adds i to the "pay_mode_type" field.
func (fu *FinanceUpdate) AddPayModeType(i int8) *FinanceUpdate {
	fu.mutation.AddPayModeType(i)
	return fu
}

// ClearPayModeType clears the value of the "pay_mode_type" field.
func (fu *FinanceUpdate) ClearPayModeType() *FinanceUpdate {
	fu.mutation.ClearPayModeType()
	return fu
}

// SetPayInfo sets the "pay_info" field.
func (fu *FinanceUpdate) SetPayInfo(s string) *FinanceUpdate {
	fu.mutation.SetPayInfo(s)
	return fu
}

// SetNillablePayInfo sets the "pay_info" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillablePayInfo(s *string) *FinanceUpdate {
	if s != nil {
		fu.SetPayInfo(*s)
	}
	return fu
}

// ClearPayInfo clears the value of the "pay_info" field.
func (fu *FinanceUpdate) ClearPayInfo() *FinanceUpdate {
	fu.mutation.ClearPayInfo()
	return fu
}

// SetRemark sets the "remark" field.
func (fu *FinanceUpdate) SetRemark(s string) *FinanceUpdate {
	fu.mutation.SetRemark(s)
	return fu
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableRemark(s *string) *FinanceUpdate {
	if s != nil {
		fu.SetRemark(*s)
	}
	return fu
}

// ClearRemark clears the value of the "remark" field.
func (fu *FinanceUpdate) ClearRemark() *FinanceUpdate {
	fu.mutation.ClearRemark()
	return fu
}

// SetPayStatus sets the "pay_status" field.
func (fu *FinanceUpdate) SetPayStatus(i int8) *FinanceUpdate {
	fu.mutation.ResetPayStatus()
	fu.mutation.SetPayStatus(i)
	return fu
}

// SetNillablePayStatus sets the "pay_status" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillablePayStatus(i *int8) *FinanceUpdate {
	if i != nil {
		fu.SetPayStatus(*i)
	}
	return fu
}

// AddPayStatus adds i to the "pay_status" field.
func (fu *FinanceUpdate) AddPayStatus(i int8) *FinanceUpdate {
	fu.mutation.AddPayStatus(i)
	return fu
}

// ClearPayStatus clears the value of the "pay_status" field.
func (fu *FinanceUpdate) ClearPayStatus() *FinanceUpdate {
	fu.mutation.ClearPayStatus()
	return fu
}

// SetAmount sets the "amount" field.
func (fu *FinanceUpdate) SetAmount(f float64) *FinanceUpdate {
	fu.mutation.ResetAmount()
	fu.mutation.SetAmount(f)
	return fu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableAmount(f *float64) *FinanceUpdate {
	if f != nil {
		fu.SetAmount(*f)
	}
	return fu
}

// AddAmount adds f to the "amount" field.
func (fu *FinanceUpdate) AddAmount(f float64) *FinanceUpdate {
	fu.mutation.AddAmount(f)
	return fu
}

// ClearAmount clears the value of the "amount" field.
func (fu *FinanceUpdate) ClearAmount() *FinanceUpdate {
	fu.mutation.ClearAmount()
	return fu
}

// SetChangeType sets the "change_type" field.
func (fu *FinanceUpdate) SetChangeType(i int8) *FinanceUpdate {
	fu.mutation.ResetChangeType()
	fu.mutation.SetChangeType(i)
	return fu
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableChangeType(i *int8) *FinanceUpdate {
	if i != nil {
		fu.SetChangeType(*i)
	}
	return fu
}

// AddChangeType adds i to the "change_type" field.
func (fu *FinanceUpdate) AddChangeType(i int8) *FinanceUpdate {
	fu.mutation.AddChangeType(i)
	return fu
}

// ClearChangeType clears the value of the "change_type" field.
func (fu *FinanceUpdate) ClearChangeType() *FinanceUpdate {
	fu.mutation.ClearChangeType()
	return fu
}

// SetCreatedAt sets the "created_at" field.
func (fu *FinanceUpdate) SetCreatedAt(t time.Time) *FinanceUpdate {
	fu.mutation.SetCreatedAt(t)
	return fu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableCreatedAt(t *time.Time) *FinanceUpdate {
	if t != nil {
		fu.SetCreatedAt(*t)
	}
	return fu
}

// ClearCreatedAt clears the value of the "created_at" field.
func (fu *FinanceUpdate) ClearCreatedAt() *FinanceUpdate {
	fu.mutation.ClearCreatedAt()
	return fu
}

// SetUpdatedAt sets the "updated_at" field.
func (fu *FinanceUpdate) SetUpdatedAt(t time.Time) *FinanceUpdate {
	fu.mutation.SetUpdatedAt(t)
	return fu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fu *FinanceUpdate) SetNillableUpdatedAt(t *time.Time) *FinanceUpdate {
	if t != nil {
		fu.SetUpdatedAt(*t)
	}
	return fu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (fu *FinanceUpdate) ClearUpdatedAt() *FinanceUpdate {
	fu.mutation.ClearUpdatedAt()
	return fu
}

// Mutation returns the FinanceMutation object of the builder.
func (fu *FinanceUpdate) Mutation() *FinanceMutation {
	return fu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FinanceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FinanceUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FinanceUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FinanceUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (fu *FinanceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FinanceUpdate {
	fu.modifiers = append(fu.modifiers, modifiers...)
	return fu
}

func (fu *FinanceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(finance.Table, finance.Columns, sqlgraph.NewFieldSpec(finance.FieldID, field.TypeInt32))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.TenantID(); ok {
		_spec.SetField(finance.FieldTenantID, field.TypeInt32, value)
	}
	if value, ok := fu.mutation.AddedTenantID(); ok {
		_spec.AddField(finance.FieldTenantID, field.TypeInt32, value)
	}
	if value, ok := fu.mutation.TransactNo(); ok {
		_spec.SetField(finance.FieldTransactNo, field.TypeString, value)
	}
	if value, ok := fu.mutation.OrderNo(); ok {
		_spec.SetField(finance.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := fu.mutation.ProjectID(); ok {
		_spec.SetField(finance.FieldProjectID, field.TypeInt32, value)
	}
	if value, ok := fu.mutation.AddedProjectID(); ok {
		_spec.AddField(finance.FieldProjectID, field.TypeInt32, value)
	}
	if fu.mutation.ProjectIDCleared() {
		_spec.ClearField(finance.FieldProjectID, field.TypeInt32)
	}
	if value, ok := fu.mutation.AccountID(); ok {
		_spec.SetField(finance.FieldAccountID, field.TypeInt32, value)
	}
	if value, ok := fu.mutation.AddedAccountID(); ok {
		_spec.AddField(finance.FieldAccountID, field.TypeInt32, value)
	}
	if value, ok := fu.mutation.TheirAccountID(); ok {
		_spec.SetField(finance.FieldTheirAccountID, field.TypeInt32, value)
	}
	if value, ok := fu.mutation.AddedTheirAccountID(); ok {
		_spec.AddField(finance.FieldTheirAccountID, field.TypeInt32, value)
	}
	if value, ok := fu.mutation.TransactAt(); ok {
		_spec.SetField(finance.FieldTransactAt, field.TypeTime, value)
	}
	if fu.mutation.TransactAtCleared() {
		_spec.ClearField(finance.FieldTransactAt, field.TypeTime)
	}
	if value, ok := fu.mutation.WriteOffAt(); ok {
		_spec.SetField(finance.FieldWriteOffAt, field.TypeTime, value)
	}
	if fu.mutation.WriteOffAtCleared() {
		_spec.ClearField(finance.FieldWriteOffAt, field.TypeTime)
	}
	if value, ok := fu.mutation.Summary(); ok {
		_spec.SetField(finance.FieldSummary, field.TypeString, value)
	}
	if fu.mutation.SummaryCleared() {
		_spec.ClearField(finance.FieldSummary, field.TypeString)
	}
	if value, ok := fu.mutation.PayModeType(); ok {
		_spec.SetField(finance.FieldPayModeType, field.TypeInt8, value)
	}
	if value, ok := fu.mutation.AddedPayModeType(); ok {
		_spec.AddField(finance.FieldPayModeType, field.TypeInt8, value)
	}
	if fu.mutation.PayModeTypeCleared() {
		_spec.ClearField(finance.FieldPayModeType, field.TypeInt8)
	}
	if value, ok := fu.mutation.PayInfo(); ok {
		_spec.SetField(finance.FieldPayInfo, field.TypeString, value)
	}
	if fu.mutation.PayInfoCleared() {
		_spec.ClearField(finance.FieldPayInfo, field.TypeString)
	}
	if value, ok := fu.mutation.Remark(); ok {
		_spec.SetField(finance.FieldRemark, field.TypeString, value)
	}
	if fu.mutation.RemarkCleared() {
		_spec.ClearField(finance.FieldRemark, field.TypeString)
	}
	if value, ok := fu.mutation.PayStatus(); ok {
		_spec.SetField(finance.FieldPayStatus, field.TypeInt8, value)
	}
	if value, ok := fu.mutation.AddedPayStatus(); ok {
		_spec.AddField(finance.FieldPayStatus, field.TypeInt8, value)
	}
	if fu.mutation.PayStatusCleared() {
		_spec.ClearField(finance.FieldPayStatus, field.TypeInt8)
	}
	if value, ok := fu.mutation.Amount(); ok {
		_spec.SetField(finance.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := fu.mutation.AddedAmount(); ok {
		_spec.AddField(finance.FieldAmount, field.TypeFloat64, value)
	}
	if fu.mutation.AmountCleared() {
		_spec.ClearField(finance.FieldAmount, field.TypeFloat64)
	}
	if value, ok := fu.mutation.ChangeType(); ok {
		_spec.SetField(finance.FieldChangeType, field.TypeInt8, value)
	}
	if value, ok := fu.mutation.AddedChangeType(); ok {
		_spec.AddField(finance.FieldChangeType, field.TypeInt8, value)
	}
	if fu.mutation.ChangeTypeCleared() {
		_spec.ClearField(finance.FieldChangeType, field.TypeInt8)
	}
	if value, ok := fu.mutation.CreatedAt(); ok {
		_spec.SetField(finance.FieldCreatedAt, field.TypeTime, value)
	}
	if fu.mutation.CreatedAtCleared() {
		_spec.ClearField(finance.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := fu.mutation.UpdatedAt(); ok {
		_spec.SetField(finance.FieldUpdatedAt, field.TypeTime, value)
	}
	if fu.mutation.UpdatedAtCleared() {
		_spec.ClearField(finance.FieldUpdatedAt, field.TypeTime)
	}
	_spec.AddModifiers(fu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{finance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FinanceUpdateOne is the builder for updating a single Finance entity.
type FinanceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *FinanceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTenantID sets the "tenant_id" field.
func (fuo *FinanceUpdateOne) SetTenantID(i int32) *FinanceUpdateOne {
	fuo.mutation.ResetTenantID()
	fuo.mutation.SetTenantID(i)
	return fuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableTenantID(i *int32) *FinanceUpdateOne {
	if i != nil {
		fuo.SetTenantID(*i)
	}
	return fuo
}

// AddTenantID adds i to the "tenant_id" field.
func (fuo *FinanceUpdateOne) AddTenantID(i int32) *FinanceUpdateOne {
	fuo.mutation.AddTenantID(i)
	return fuo
}

// SetTransactNo sets the "transact_no" field.
func (fuo *FinanceUpdateOne) SetTransactNo(s string) *FinanceUpdateOne {
	fuo.mutation.SetTransactNo(s)
	return fuo
}

// SetNillableTransactNo sets the "transact_no" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableTransactNo(s *string) *FinanceUpdateOne {
	if s != nil {
		fuo.SetTransactNo(*s)
	}
	return fuo
}

// SetOrderNo sets the "order_no" field.
func (fuo *FinanceUpdateOne) SetOrderNo(s string) *FinanceUpdateOne {
	fuo.mutation.SetOrderNo(s)
	return fuo
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableOrderNo(s *string) *FinanceUpdateOne {
	if s != nil {
		fuo.SetOrderNo(*s)
	}
	return fuo
}

// SetProjectID sets the "project_id" field.
func (fuo *FinanceUpdateOne) SetProjectID(i int32) *FinanceUpdateOne {
	fuo.mutation.ResetProjectID()
	fuo.mutation.SetProjectID(i)
	return fuo
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableProjectID(i *int32) *FinanceUpdateOne {
	if i != nil {
		fuo.SetProjectID(*i)
	}
	return fuo
}

// AddProjectID adds i to the "project_id" field.
func (fuo *FinanceUpdateOne) AddProjectID(i int32) *FinanceUpdateOne {
	fuo.mutation.AddProjectID(i)
	return fuo
}

// ClearProjectID clears the value of the "project_id" field.
func (fuo *FinanceUpdateOne) ClearProjectID() *FinanceUpdateOne {
	fuo.mutation.ClearProjectID()
	return fuo
}

// SetAccountID sets the "account_id" field.
func (fuo *FinanceUpdateOne) SetAccountID(i int32) *FinanceUpdateOne {
	fuo.mutation.ResetAccountID()
	fuo.mutation.SetAccountID(i)
	return fuo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableAccountID(i *int32) *FinanceUpdateOne {
	if i != nil {
		fuo.SetAccountID(*i)
	}
	return fuo
}

// AddAccountID adds i to the "account_id" field.
func (fuo *FinanceUpdateOne) AddAccountID(i int32) *FinanceUpdateOne {
	fuo.mutation.AddAccountID(i)
	return fuo
}

// SetTheirAccountID sets the "their_account_id" field.
func (fuo *FinanceUpdateOne) SetTheirAccountID(i int32) *FinanceUpdateOne {
	fuo.mutation.ResetTheirAccountID()
	fuo.mutation.SetTheirAccountID(i)
	return fuo
}

// SetNillableTheirAccountID sets the "their_account_id" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableTheirAccountID(i *int32) *FinanceUpdateOne {
	if i != nil {
		fuo.SetTheirAccountID(*i)
	}
	return fuo
}

// AddTheirAccountID adds i to the "their_account_id" field.
func (fuo *FinanceUpdateOne) AddTheirAccountID(i int32) *FinanceUpdateOne {
	fuo.mutation.AddTheirAccountID(i)
	return fuo
}

// SetTransactAt sets the "transact_at" field.
func (fuo *FinanceUpdateOne) SetTransactAt(t time.Time) *FinanceUpdateOne {
	fuo.mutation.SetTransactAt(t)
	return fuo
}

// SetNillableTransactAt sets the "transact_at" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableTransactAt(t *time.Time) *FinanceUpdateOne {
	if t != nil {
		fuo.SetTransactAt(*t)
	}
	return fuo
}

// ClearTransactAt clears the value of the "transact_at" field.
func (fuo *FinanceUpdateOne) ClearTransactAt() *FinanceUpdateOne {
	fuo.mutation.ClearTransactAt()
	return fuo
}

// SetWriteOffAt sets the "write_off_at" field.
func (fuo *FinanceUpdateOne) SetWriteOffAt(t time.Time) *FinanceUpdateOne {
	fuo.mutation.SetWriteOffAt(t)
	return fuo
}

// SetNillableWriteOffAt sets the "write_off_at" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableWriteOffAt(t *time.Time) *FinanceUpdateOne {
	if t != nil {
		fuo.SetWriteOffAt(*t)
	}
	return fuo
}

// ClearWriteOffAt clears the value of the "write_off_at" field.
func (fuo *FinanceUpdateOne) ClearWriteOffAt() *FinanceUpdateOne {
	fuo.mutation.ClearWriteOffAt()
	return fuo
}

// SetSummary sets the "summary" field.
func (fuo *FinanceUpdateOne) SetSummary(s string) *FinanceUpdateOne {
	fuo.mutation.SetSummary(s)
	return fuo
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableSummary(s *string) *FinanceUpdateOne {
	if s != nil {
		fuo.SetSummary(*s)
	}
	return fuo
}

// ClearSummary clears the value of the "summary" field.
func (fuo *FinanceUpdateOne) ClearSummary() *FinanceUpdateOne {
	fuo.mutation.ClearSummary()
	return fuo
}

// SetPayModeType sets the "pay_mode_type" field.
func (fuo *FinanceUpdateOne) SetPayModeType(i int8) *FinanceUpdateOne {
	fuo.mutation.ResetPayModeType()
	fuo.mutation.SetPayModeType(i)
	return fuo
}

// SetNillablePayModeType sets the "pay_mode_type" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillablePayModeType(i *int8) *FinanceUpdateOne {
	if i != nil {
		fuo.SetPayModeType(*i)
	}
	return fuo
}

// AddPayModeType adds i to the "pay_mode_type" field.
func (fuo *FinanceUpdateOne) AddPayModeType(i int8) *FinanceUpdateOne {
	fuo.mutation.AddPayModeType(i)
	return fuo
}

// ClearPayModeType clears the value of the "pay_mode_type" field.
func (fuo *FinanceUpdateOne) ClearPayModeType() *FinanceUpdateOne {
	fuo.mutation.ClearPayModeType()
	return fuo
}

// SetPayInfo sets the "pay_info" field.
func (fuo *FinanceUpdateOne) SetPayInfo(s string) *FinanceUpdateOne {
	fuo.mutation.SetPayInfo(s)
	return fuo
}

// SetNillablePayInfo sets the "pay_info" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillablePayInfo(s *string) *FinanceUpdateOne {
	if s != nil {
		fuo.SetPayInfo(*s)
	}
	return fuo
}

// ClearPayInfo clears the value of the "pay_info" field.
func (fuo *FinanceUpdateOne) ClearPayInfo() *FinanceUpdateOne {
	fuo.mutation.ClearPayInfo()
	return fuo
}

// SetRemark sets the "remark" field.
func (fuo *FinanceUpdateOne) SetRemark(s string) *FinanceUpdateOne {
	fuo.mutation.SetRemark(s)
	return fuo
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableRemark(s *string) *FinanceUpdateOne {
	if s != nil {
		fuo.SetRemark(*s)
	}
	return fuo
}

// ClearRemark clears the value of the "remark" field.
func (fuo *FinanceUpdateOne) ClearRemark() *FinanceUpdateOne {
	fuo.mutation.ClearRemark()
	return fuo
}

// SetPayStatus sets the "pay_status" field.
func (fuo *FinanceUpdateOne) SetPayStatus(i int8) *FinanceUpdateOne {
	fuo.mutation.ResetPayStatus()
	fuo.mutation.SetPayStatus(i)
	return fuo
}

// SetNillablePayStatus sets the "pay_status" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillablePayStatus(i *int8) *FinanceUpdateOne {
	if i != nil {
		fuo.SetPayStatus(*i)
	}
	return fuo
}

// AddPayStatus adds i to the "pay_status" field.
func (fuo *FinanceUpdateOne) AddPayStatus(i int8) *FinanceUpdateOne {
	fuo.mutation.AddPayStatus(i)
	return fuo
}

// ClearPayStatus clears the value of the "pay_status" field.
func (fuo *FinanceUpdateOne) ClearPayStatus() *FinanceUpdateOne {
	fuo.mutation.ClearPayStatus()
	return fuo
}

// SetAmount sets the "amount" field.
func (fuo *FinanceUpdateOne) SetAmount(f float64) *FinanceUpdateOne {
	fuo.mutation.ResetAmount()
	fuo.mutation.SetAmount(f)
	return fuo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableAmount(f *float64) *FinanceUpdateOne {
	if f != nil {
		fuo.SetAmount(*f)
	}
	return fuo
}

// AddAmount adds f to the "amount" field.
func (fuo *FinanceUpdateOne) AddAmount(f float64) *FinanceUpdateOne {
	fuo.mutation.AddAmount(f)
	return fuo
}

// ClearAmount clears the value of the "amount" field.
func (fuo *FinanceUpdateOne) ClearAmount() *FinanceUpdateOne {
	fuo.mutation.ClearAmount()
	return fuo
}

// SetChangeType sets the "change_type" field.
func (fuo *FinanceUpdateOne) SetChangeType(i int8) *FinanceUpdateOne {
	fuo.mutation.ResetChangeType()
	fuo.mutation.SetChangeType(i)
	return fuo
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableChangeType(i *int8) *FinanceUpdateOne {
	if i != nil {
		fuo.SetChangeType(*i)
	}
	return fuo
}

// AddChangeType adds i to the "change_type" field.
func (fuo *FinanceUpdateOne) AddChangeType(i int8) *FinanceUpdateOne {
	fuo.mutation.AddChangeType(i)
	return fuo
}

// ClearChangeType clears the value of the "change_type" field.
func (fuo *FinanceUpdateOne) ClearChangeType() *FinanceUpdateOne {
	fuo.mutation.ClearChangeType()
	return fuo
}

// SetCreatedAt sets the "created_at" field.
func (fuo *FinanceUpdateOne) SetCreatedAt(t time.Time) *FinanceUpdateOne {
	fuo.mutation.SetCreatedAt(t)
	return fuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableCreatedAt(t *time.Time) *FinanceUpdateOne {
	if t != nil {
		fuo.SetCreatedAt(*t)
	}
	return fuo
}

// ClearCreatedAt clears the value of the "created_at" field.
func (fuo *FinanceUpdateOne) ClearCreatedAt() *FinanceUpdateOne {
	fuo.mutation.ClearCreatedAt()
	return fuo
}

// SetUpdatedAt sets the "updated_at" field.
func (fuo *FinanceUpdateOne) SetUpdatedAt(t time.Time) *FinanceUpdateOne {
	fuo.mutation.SetUpdatedAt(t)
	return fuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fuo *FinanceUpdateOne) SetNillableUpdatedAt(t *time.Time) *FinanceUpdateOne {
	if t != nil {
		fuo.SetUpdatedAt(*t)
	}
	return fuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (fuo *FinanceUpdateOne) ClearUpdatedAt() *FinanceUpdateOne {
	fuo.mutation.ClearUpdatedAt()
	return fuo
}

// Mutation returns the FinanceMutation object of the builder.
func (fuo *FinanceUpdateOne) Mutation() *FinanceMutation {
	return fuo.mutation
}

// Where appends a list predicates to the FinanceUpdate builder.
func (fuo *FinanceUpdateOne) Where(ps ...predicate.Finance) *FinanceUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FinanceUpdateOne) Select(field string, fields ...string) *FinanceUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Finance entity.
func (fuo *FinanceUpdateOne) Save(ctx context.Context) (*Finance, error) {
	return withHooks(ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FinanceUpdateOne) SaveX(ctx context.Context) *Finance {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FinanceUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FinanceUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (fuo *FinanceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FinanceUpdateOne {
	fuo.modifiers = append(fuo.modifiers, modifiers...)
	return fuo
}

func (fuo *FinanceUpdateOne) sqlSave(ctx context.Context) (_node *Finance, err error) {
	_spec := sqlgraph.NewUpdateSpec(finance.Table, finance.Columns, sqlgraph.NewFieldSpec(finance.FieldID, field.TypeInt32))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Finance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, finance.FieldID)
		for _, f := range fields {
			if !finance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != finance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.TenantID(); ok {
		_spec.SetField(finance.FieldTenantID, field.TypeInt32, value)
	}
	if value, ok := fuo.mutation.AddedTenantID(); ok {
		_spec.AddField(finance.FieldTenantID, field.TypeInt32, value)
	}
	if value, ok := fuo.mutation.TransactNo(); ok {
		_spec.SetField(finance.FieldTransactNo, field.TypeString, value)
	}
	if value, ok := fuo.mutation.OrderNo(); ok {
		_spec.SetField(finance.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := fuo.mutation.ProjectID(); ok {
		_spec.SetField(finance.FieldProjectID, field.TypeInt32, value)
	}
	if value, ok := fuo.mutation.AddedProjectID(); ok {
		_spec.AddField(finance.FieldProjectID, field.TypeInt32, value)
	}
	if fuo.mutation.ProjectIDCleared() {
		_spec.ClearField(finance.FieldProjectID, field.TypeInt32)
	}
	if value, ok := fuo.mutation.AccountID(); ok {
		_spec.SetField(finance.FieldAccountID, field.TypeInt32, value)
	}
	if value, ok := fuo.mutation.AddedAccountID(); ok {
		_spec.AddField(finance.FieldAccountID, field.TypeInt32, value)
	}
	if value, ok := fuo.mutation.TheirAccountID(); ok {
		_spec.SetField(finance.FieldTheirAccountID, field.TypeInt32, value)
	}
	if value, ok := fuo.mutation.AddedTheirAccountID(); ok {
		_spec.AddField(finance.FieldTheirAccountID, field.TypeInt32, value)
	}
	if value, ok := fuo.mutation.TransactAt(); ok {
		_spec.SetField(finance.FieldTransactAt, field.TypeTime, value)
	}
	if fuo.mutation.TransactAtCleared() {
		_spec.ClearField(finance.FieldTransactAt, field.TypeTime)
	}
	if value, ok := fuo.mutation.WriteOffAt(); ok {
		_spec.SetField(finance.FieldWriteOffAt, field.TypeTime, value)
	}
	if fuo.mutation.WriteOffAtCleared() {
		_spec.ClearField(finance.FieldWriteOffAt, field.TypeTime)
	}
	if value, ok := fuo.mutation.Summary(); ok {
		_spec.SetField(finance.FieldSummary, field.TypeString, value)
	}
	if fuo.mutation.SummaryCleared() {
		_spec.ClearField(finance.FieldSummary, field.TypeString)
	}
	if value, ok := fuo.mutation.PayModeType(); ok {
		_spec.SetField(finance.FieldPayModeType, field.TypeInt8, value)
	}
	if value, ok := fuo.mutation.AddedPayModeType(); ok {
		_spec.AddField(finance.FieldPayModeType, field.TypeInt8, value)
	}
	if fuo.mutation.PayModeTypeCleared() {
		_spec.ClearField(finance.FieldPayModeType, field.TypeInt8)
	}
	if value, ok := fuo.mutation.PayInfo(); ok {
		_spec.SetField(finance.FieldPayInfo, field.TypeString, value)
	}
	if fuo.mutation.PayInfoCleared() {
		_spec.ClearField(finance.FieldPayInfo, field.TypeString)
	}
	if value, ok := fuo.mutation.Remark(); ok {
		_spec.SetField(finance.FieldRemark, field.TypeString, value)
	}
	if fuo.mutation.RemarkCleared() {
		_spec.ClearField(finance.FieldRemark, field.TypeString)
	}
	if value, ok := fuo.mutation.PayStatus(); ok {
		_spec.SetField(finance.FieldPayStatus, field.TypeInt8, value)
	}
	if value, ok := fuo.mutation.AddedPayStatus(); ok {
		_spec.AddField(finance.FieldPayStatus, field.TypeInt8, value)
	}
	if fuo.mutation.PayStatusCleared() {
		_spec.ClearField(finance.FieldPayStatus, field.TypeInt8)
	}
	if value, ok := fuo.mutation.Amount(); ok {
		_spec.SetField(finance.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := fuo.mutation.AddedAmount(); ok {
		_spec.AddField(finance.FieldAmount, field.TypeFloat64, value)
	}
	if fuo.mutation.AmountCleared() {
		_spec.ClearField(finance.FieldAmount, field.TypeFloat64)
	}
	if value, ok := fuo.mutation.ChangeType(); ok {
		_spec.SetField(finance.FieldChangeType, field.TypeInt8, value)
	}
	if value, ok := fuo.mutation.AddedChangeType(); ok {
		_spec.AddField(finance.FieldChangeType, field.TypeInt8, value)
	}
	if fuo.mutation.ChangeTypeCleared() {
		_spec.ClearField(finance.FieldChangeType, field.TypeInt8)
	}
	if value, ok := fuo.mutation.CreatedAt(); ok {
		_spec.SetField(finance.FieldCreatedAt, field.TypeTime, value)
	}
	if fuo.mutation.CreatedAtCleared() {
		_spec.ClearField(finance.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := fuo.mutation.UpdatedAt(); ok {
		_spec.SetField(finance.FieldUpdatedAt, field.TypeTime, value)
	}
	if fuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(finance.FieldUpdatedAt, field.TypeTime)
	}
	_spec.AddModifiers(fuo.modifiers...)
	_node = &Finance{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{finance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
