// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-study/app/database/tabtaba/internal/data/ent/finance"
	"go-study/app/database/tabtaba/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FinanceDelete is the builder for deleting a Finance entity.
type FinanceDelete struct {
	config
	hooks    []Hook
	mutation *FinanceMutation
}

// Where appends a list predicates to the FinanceDelete builder.
func (fd *FinanceDelete) Where(ps ...predicate.Finance) *FinanceDelete {
	fd.mutation.Where(ps...)
	return fd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fd *FinanceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fd.sqlExec, fd.mutation, fd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fd *FinanceDelete) ExecX(ctx context.Context) int {
	n, err := fd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fd *FinanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(finance.Table, sqlgraph.NewFieldSpec(finance.FieldID, field.TypeInt32))
	if ps := fd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fd.mutation.done = true
	return affected, err
}

// FinanceDeleteOne is the builder for deleting a single Finance entity.
type FinanceDeleteOne struct {
	fd *FinanceDelete
}

// Where appends a list predicates to the FinanceDelete builder.
func (fdo *FinanceDeleteOne) Where(ps ...predicate.Finance) *FinanceDeleteOne {
	fdo.fd.mutation.Where(ps...)
	return fdo
}

// Exec executes the deletion query.
func (fdo *FinanceDeleteOne) Exec(ctx context.Context) error {
	n, err := fdo.fd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{finance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fdo *FinanceDeleteOne) ExecX(ctx context.Context) {
	if err := fdo.Exec(ctx); err != nil {
		panic(err)
	}
}
