// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-study/app/database/tabtaba/internal/data/ent/project"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Project is the model entity for the Project schema.
type Project struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID int32 `json:"id,omitempty"`
	// 租户id
	TenantID int32 `json:"tenant_id,omitempty"`
	// 发布账户ID
	AccountID int32 `json:"account_id,omitempty"`
	// 发布账户手机号
	AccountPhone string `json:"account_phone,omitempty"`
	// 接单镖师ID
	WorkerAccountID int32 `json:"worker_account_id,omitempty"`
	// 发布项目类型
	ProjectType int8 `json:"project_type,omitempty"`
	// 项目名称
	Title string `json:"title,omitempty"`
	// 预期交付时间
	ExpectDeliverTime time.Time `json:"expect_deliver_time,omitempty"`
	// 招标资料
	TenderFiles string `json:"tender_files,omitempty"`
	// 最终交付的标书
	DeliverBidFiles string `json:"deliver_bid_files,omitempty"`
	// 标书最终交付时间
	DeliverBidTime time.Time `json:"deliver_bid_time,omitempty"`
	// 备注(后台)
	Remark string `json:"remark,omitempty"`
	// 项目状态
	ProjectStatus int32 `json:"project_status,omitempty"`
	// 订单金额(选择镖师后报价反推金额)
	Amount float64 `json:"amount,omitempty"`
	// 已支付金额
	PaidAmount float64 `json:"paid_amount,omitempty"`
	// 未支付金额
	UnpaidAmount float64 `json:"unpaid_amount,omitempty"`
	// 佣金
	Commission float64 `json:"commission,omitempty"`
	// 镖师实际佣金
	WorkerCommission float64 `json:"worker_commission,omitempty"`
	// 财务开票状态 1未开票 2已开票 3开票失败 4开票中
	FinanceInvoiceStatus int8 `json:"finance_invoice_status,omitempty"`
	// e签宝 签署流程id
	ESignID string `json:"e_sign_id,omitempty"`
	// e签宝 状态
	ESignStatus int8 `json:"e_sign_status,omitempty"`
	// e签宝 流程结束回调
	ESignNotify string `json:"e_sign_notify,omitempty"`
	// 评分
	Score float64 `json:"score,omitempty"`
	// 评价
	Evaluate string `json:"evaluate,omitempty"`
	// 取消原因
	CancelReason string `json:"cancel_reason,omitempty"`
	// 超时关闭时间
	CloseAt time.Time `json:"close_at,omitempty"`
	// 渠道code
	ChannelCode string `json:"channel_code,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 订单实付金额
	PayMoney float64 `json:"pay_money,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Project) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case project.FieldAmount, project.FieldPaidAmount, project.FieldUnpaidAmount, project.FieldCommission, project.FieldWorkerCommission, project.FieldScore, project.FieldPayMoney:
			values[i] = new(sql.NullFloat64)
		case project.FieldID, project.FieldTenantID, project.FieldAccountID, project.FieldWorkerAccountID, project.FieldProjectType, project.FieldProjectStatus, project.FieldFinanceInvoiceStatus, project.FieldESignStatus:
			values[i] = new(sql.NullInt64)
		case project.FieldAccountPhone, project.FieldTitle, project.FieldTenderFiles, project.FieldDeliverBidFiles, project.FieldRemark, project.FieldESignID, project.FieldESignNotify, project.FieldEvaluate, project.FieldCancelReason, project.FieldChannelCode:
			values[i] = new(sql.NullString)
		case project.FieldExpectDeliverTime, project.FieldDeliverBidTime, project.FieldCloseAt, project.FieldCreatedAt, project.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Project fields.
func (pr *Project) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case project.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pr.ID = int32(value.Int64)
		case project.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				pr.TenantID = int32(value.Int64)
			}
		case project.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				pr.AccountID = int32(value.Int64)
			}
		case project.FieldAccountPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_phone", values[i])
			} else if value.Valid {
				pr.AccountPhone = value.String
			}
		case project.FieldWorkerAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field worker_account_id", values[i])
			} else if value.Valid {
				pr.WorkerAccountID = int32(value.Int64)
			}
		case project.FieldProjectType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_type", values[i])
			} else if value.Valid {
				pr.ProjectType = int8(value.Int64)
			}
		case project.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				pr.Title = value.String
			}
		case project.FieldExpectDeliverTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expect_deliver_time", values[i])
			} else if value.Valid {
				pr.ExpectDeliverTime = value.Time
			}
		case project.FieldTenderFiles:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tender_files", values[i])
			} else if value.Valid {
				pr.TenderFiles = value.String
			}
		case project.FieldDeliverBidFiles:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deliver_bid_files", values[i])
			} else if value.Valid {
				pr.DeliverBidFiles = value.String
			}
		case project.FieldDeliverBidTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deliver_bid_time", values[i])
			} else if value.Valid {
				pr.DeliverBidTime = value.Time
			}
		case project.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				pr.Remark = value.String
			}
		case project.FieldProjectStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_status", values[i])
			} else if value.Valid {
				pr.ProjectStatus = int32(value.Int64)
			}
		case project.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				pr.Amount = value.Float64
			}
		case project.FieldPaidAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_amount", values[i])
			} else if value.Valid {
				pr.PaidAmount = value.Float64
			}
		case project.FieldUnpaidAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unpaid_amount", values[i])
			} else if value.Valid {
				pr.UnpaidAmount = value.Float64
			}
		case project.FieldCommission:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field commission", values[i])
			} else if value.Valid {
				pr.Commission = value.Float64
			}
		case project.FieldWorkerCommission:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field worker_commission", values[i])
			} else if value.Valid {
				pr.WorkerCommission = value.Float64
			}
		case project.FieldFinanceInvoiceStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field finance_invoice_status", values[i])
			} else if value.Valid {
				pr.FinanceInvoiceStatus = int8(value.Int64)
			}
		case project.FieldESignID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field e_sign_id", values[i])
			} else if value.Valid {
				pr.ESignID = value.String
			}
		case project.FieldESignStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field e_sign_status", values[i])
			} else if value.Valid {
				pr.ESignStatus = int8(value.Int64)
			}
		case project.FieldESignNotify:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field e_sign_notify", values[i])
			} else if value.Valid {
				pr.ESignNotify = value.String
			}
		case project.FieldScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				pr.Score = value.Float64
			}
		case project.FieldEvaluate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field evaluate", values[i])
			} else if value.Valid {
				pr.Evaluate = value.String
			}
		case project.FieldCancelReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_reason", values[i])
			} else if value.Valid {
				pr.CancelReason = value.String
			}
		case project.FieldCloseAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field close_at", values[i])
			} else if value.Valid {
				pr.CloseAt = value.Time
			}
		case project.FieldChannelCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_code", values[i])
			} else if value.Valid {
				pr.ChannelCode = value.String
			}
		case project.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pr.CreatedAt = value.Time
			}
		case project.FieldPayMoney:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pay_money", values[i])
			} else if value.Valid {
				pr.PayMoney = value.Float64
			}
		case project.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pr.UpdatedAt = value.Time
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Project.
// This includes values selected through modifiers, order, etc.
func (pr *Project) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// Update returns a builder for updating this Project.
// Note that you need to call Project.Unwrap() before calling this method if this Project
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Project) Update() *ProjectUpdateOne {
	return NewProjectClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the Project entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Project) Unwrap() *Project {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Project is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Project) String() string {
	var builder strings.Builder
	builder.WriteString("Project(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", pr.TenantID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", pr.AccountID))
	builder.WriteString(", ")
	builder.WriteString("account_phone=")
	builder.WriteString(pr.AccountPhone)
	builder.WriteString(", ")
	builder.WriteString("worker_account_id=")
	builder.WriteString(fmt.Sprintf("%v", pr.WorkerAccountID))
	builder.WriteString(", ")
	builder.WriteString("project_type=")
	builder.WriteString(fmt.Sprintf("%v", pr.ProjectType))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(pr.Title)
	builder.WriteString(", ")
	builder.WriteString("expect_deliver_time=")
	builder.WriteString(pr.ExpectDeliverTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tender_files=")
	builder.WriteString(pr.TenderFiles)
	builder.WriteString(", ")
	builder.WriteString("deliver_bid_files=")
	builder.WriteString(pr.DeliverBidFiles)
	builder.WriteString(", ")
	builder.WriteString("deliver_bid_time=")
	builder.WriteString(pr.DeliverBidTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(pr.Remark)
	builder.WriteString(", ")
	builder.WriteString("project_status=")
	builder.WriteString(fmt.Sprintf("%v", pr.ProjectStatus))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", pr.Amount))
	builder.WriteString(", ")
	builder.WriteString("paid_amount=")
	builder.WriteString(fmt.Sprintf("%v", pr.PaidAmount))
	builder.WriteString(", ")
	builder.WriteString("unpaid_amount=")
	builder.WriteString(fmt.Sprintf("%v", pr.UnpaidAmount))
	builder.WriteString(", ")
	builder.WriteString("commission=")
	builder.WriteString(fmt.Sprintf("%v", pr.Commission))
	builder.WriteString(", ")
	builder.WriteString("worker_commission=")
	builder.WriteString(fmt.Sprintf("%v", pr.WorkerCommission))
	builder.WriteString(", ")
	builder.WriteString("finance_invoice_status=")
	builder.WriteString(fmt.Sprintf("%v", pr.FinanceInvoiceStatus))
	builder.WriteString(", ")
	builder.WriteString("e_sign_id=")
	builder.WriteString(pr.ESignID)
	builder.WriteString(", ")
	builder.WriteString("e_sign_status=")
	builder.WriteString(fmt.Sprintf("%v", pr.ESignStatus))
	builder.WriteString(", ")
	builder.WriteString("e_sign_notify=")
	builder.WriteString(pr.ESignNotify)
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", pr.Score))
	builder.WriteString(", ")
	builder.WriteString("evaluate=")
	builder.WriteString(pr.Evaluate)
	builder.WriteString(", ")
	builder.WriteString("cancel_reason=")
	builder.WriteString(pr.CancelReason)
	builder.WriteString(", ")
	builder.WriteString("close_at=")
	builder.WriteString(pr.CloseAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("channel_code=")
	builder.WriteString(pr.ChannelCode)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("pay_money=")
	builder.WriteString(fmt.Sprintf("%v", pr.PayMoney))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pr.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Projects is a parsable slice of Project.
type Projects []*Project
