// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-study/app/database/tabtaba/internal/data/ent/predicate"
	"go-study/app/database/tabtaba/internal/data/ent/projectactionrecord"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectActionRecordUpdate is the builder for updating ProjectActionRecord entities.
type ProjectActionRecordUpdate struct {
	config
	hooks     []Hook
	mutation  *ProjectActionRecordMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProjectActionRecordUpdate builder.
func (paru *ProjectActionRecordUpdate) Where(ps ...predicate.ProjectActionRecord) *ProjectActionRecordUpdate {
	paru.mutation.Where(ps...)
	return paru
}

// SetTenantID sets the "tenant_id" field.
func (paru *ProjectActionRecordUpdate) SetTenantID(i int32) *ProjectActionRecordUpdate {
	paru.mutation.ResetTenantID()
	paru.mutation.SetTenantID(i)
	return paru
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableTenantID(i *int32) *ProjectActionRecordUpdate {
	if i != nil {
		paru.SetTenantID(*i)
	}
	return paru
}

// AddTenantID adds i to the "tenant_id" field.
func (paru *ProjectActionRecordUpdate) AddTenantID(i int32) *ProjectActionRecordUpdate {
	paru.mutation.AddTenantID(i)
	return paru
}

// SetProjectID sets the "project_id" field.
func (paru *ProjectActionRecordUpdate) SetProjectID(i int32) *ProjectActionRecordUpdate {
	paru.mutation.ResetProjectID()
	paru.mutation.SetProjectID(i)
	return paru
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableProjectID(i *int32) *ProjectActionRecordUpdate {
	if i != nil {
		paru.SetProjectID(*i)
	}
	return paru
}

// AddProjectID adds i to the "project_id" field.
func (paru *ProjectActionRecordUpdate) AddProjectID(i int32) *ProjectActionRecordUpdate {
	paru.mutation.AddProjectID(i)
	return paru
}

// SetActionPlat sets the "action_plat" field.
func (paru *ProjectActionRecordUpdate) SetActionPlat(i int8) *ProjectActionRecordUpdate {
	paru.mutation.ResetActionPlat()
	paru.mutation.SetActionPlat(i)
	return paru
}

// SetNillableActionPlat sets the "action_plat" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableActionPlat(i *int8) *ProjectActionRecordUpdate {
	if i != nil {
		paru.SetActionPlat(*i)
	}
	return paru
}

// AddActionPlat adds i to the "action_plat" field.
func (paru *ProjectActionRecordUpdate) AddActionPlat(i int8) *ProjectActionRecordUpdate {
	paru.mutation.AddActionPlat(i)
	return paru
}

// SetAction sets the "action" field.
func (paru *ProjectActionRecordUpdate) SetAction(s string) *ProjectActionRecordUpdate {
	paru.mutation.SetAction(s)
	return paru
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableAction(s *string) *ProjectActionRecordUpdate {
	if s != nil {
		paru.SetAction(*s)
	}
	return paru
}

// SetAccountID sets the "account_id" field.
func (paru *ProjectActionRecordUpdate) SetAccountID(i int32) *ProjectActionRecordUpdate {
	paru.mutation.ResetAccountID()
	paru.mutation.SetAccountID(i)
	return paru
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableAccountID(i *int32) *ProjectActionRecordUpdate {
	if i != nil {
		paru.SetAccountID(*i)
	}
	return paru
}

// AddAccountID adds i to the "account_id" field.
func (paru *ProjectActionRecordUpdate) AddAccountID(i int32) *ProjectActionRecordUpdate {
	paru.mutation.AddAccountID(i)
	return paru
}

// ClearAccountID clears the value of the "account_id" field.
func (paru *ProjectActionRecordUpdate) ClearAccountID() *ProjectActionRecordUpdate {
	paru.mutation.ClearAccountID()
	return paru
}

// SetAccountName sets the "account_name" field.
func (paru *ProjectActionRecordUpdate) SetAccountName(s string) *ProjectActionRecordUpdate {
	paru.mutation.SetAccountName(s)
	return paru
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableAccountName(s *string) *ProjectActionRecordUpdate {
	if s != nil {
		paru.SetAccountName(*s)
	}
	return paru
}

// ClearAccountName clears the value of the "account_name" field.
func (paru *ProjectActionRecordUpdate) ClearAccountName() *ProjectActionRecordUpdate {
	paru.mutation.ClearAccountName()
	return paru
}

// SetProjectStatus sets the "project_status" field.
func (paru *ProjectActionRecordUpdate) SetProjectStatus(i int32) *ProjectActionRecordUpdate {
	paru.mutation.ResetProjectStatus()
	paru.mutation.SetProjectStatus(i)
	return paru
}

// SetNillableProjectStatus sets the "project_status" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableProjectStatus(i *int32) *ProjectActionRecordUpdate {
	if i != nil {
		paru.SetProjectStatus(*i)
	}
	return paru
}

// AddProjectStatus adds i to the "project_status" field.
func (paru *ProjectActionRecordUpdate) AddProjectStatus(i int32) *ProjectActionRecordUpdate {
	paru.mutation.AddProjectStatus(i)
	return paru
}

// SetProjectStatusText sets the "project_status_text" field.
func (paru *ProjectActionRecordUpdate) SetProjectStatusText(s string) *ProjectActionRecordUpdate {
	paru.mutation.SetProjectStatusText(s)
	return paru
}

// SetNillableProjectStatusText sets the "project_status_text" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableProjectStatusText(s *string) *ProjectActionRecordUpdate {
	if s != nil {
		paru.SetProjectStatusText(*s)
	}
	return paru
}

// SetStatus sets the "status" field.
func (paru *ProjectActionRecordUpdate) SetStatus(i int8) *ProjectActionRecordUpdate {
	paru.mutation.ResetStatus()
	paru.mutation.SetStatus(i)
	return paru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableStatus(i *int8) *ProjectActionRecordUpdate {
	if i != nil {
		paru.SetStatus(*i)
	}
	return paru
}

// AddStatus adds i to the "status" field.
func (paru *ProjectActionRecordUpdate) AddStatus(i int8) *ProjectActionRecordUpdate {
	paru.mutation.AddStatus(i)
	return paru
}

// ClearStatus clears the value of the "status" field.
func (paru *ProjectActionRecordUpdate) ClearStatus() *ProjectActionRecordUpdate {
	paru.mutation.ClearStatus()
	return paru
}

// SetCreatedAt sets the "created_at" field.
func (paru *ProjectActionRecordUpdate) SetCreatedAt(t time.Time) *ProjectActionRecordUpdate {
	paru.mutation.SetCreatedAt(t)
	return paru
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableCreatedAt(t *time.Time) *ProjectActionRecordUpdate {
	if t != nil {
		paru.SetCreatedAt(*t)
	}
	return paru
}

// SetUpdatedAt sets the "updated_at" field.
func (paru *ProjectActionRecordUpdate) SetUpdatedAt(t time.Time) *ProjectActionRecordUpdate {
	paru.mutation.SetUpdatedAt(t)
	return paru
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (paru *ProjectActionRecordUpdate) SetNillableUpdatedAt(t *time.Time) *ProjectActionRecordUpdate {
	if t != nil {
		paru.SetUpdatedAt(*t)
	}
	return paru
}

// Mutation returns the ProjectActionRecordMutation object of the builder.
func (paru *ProjectActionRecordUpdate) Mutation() *ProjectActionRecordMutation {
	return paru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (paru *ProjectActionRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, paru.sqlSave, paru.mutation, paru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (paru *ProjectActionRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := paru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (paru *ProjectActionRecordUpdate) Exec(ctx context.Context) error {
	_, err := paru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (paru *ProjectActionRecordUpdate) ExecX(ctx context.Context) {
	if err := paru.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (paru *ProjectActionRecordUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProjectActionRecordUpdate {
	paru.modifiers = append(paru.modifiers, modifiers...)
	return paru
}

func (paru *ProjectActionRecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(projectactionrecord.Table, projectactionrecord.Columns, sqlgraph.NewFieldSpec(projectactionrecord.FieldID, field.TypeInt32))
	if ps := paru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := paru.mutation.TenantID(); ok {
		_spec.SetField(projectactionrecord.FieldTenantID, field.TypeInt32, value)
	}
	if value, ok := paru.mutation.AddedTenantID(); ok {
		_spec.AddField(projectactionrecord.FieldTenantID, field.TypeInt32, value)
	}
	if value, ok := paru.mutation.ProjectID(); ok {
		_spec.SetField(projectactionrecord.FieldProjectID, field.TypeInt32, value)
	}
	if value, ok := paru.mutation.AddedProjectID(); ok {
		_spec.AddField(projectactionrecord.FieldProjectID, field.TypeInt32, value)
	}
	if value, ok := paru.mutation.ActionPlat(); ok {
		_spec.SetField(projectactionrecord.FieldActionPlat, field.TypeInt8, value)
	}
	if value, ok := paru.mutation.AddedActionPlat(); ok {
		_spec.AddField(projectactionrecord.FieldActionPlat, field.TypeInt8, value)
	}
	if value, ok := paru.mutation.Action(); ok {
		_spec.SetField(projectactionrecord.FieldAction, field.TypeString, value)
	}
	if value, ok := paru.mutation.AccountID(); ok {
		_spec.SetField(projectactionrecord.FieldAccountID, field.TypeInt32, value)
	}
	if value, ok := paru.mutation.AddedAccountID(); ok {
		_spec.AddField(projectactionrecord.FieldAccountID, field.TypeInt32, value)
	}
	if paru.mutation.AccountIDCleared() {
		_spec.ClearField(projectactionrecord.FieldAccountID, field.TypeInt32)
	}
	if value, ok := paru.mutation.AccountName(); ok {
		_spec.SetField(projectactionrecord.FieldAccountName, field.TypeString, value)
	}
	if paru.mutation.AccountNameCleared() {
		_spec.ClearField(projectactionrecord.FieldAccountName, field.TypeString)
	}
	if value, ok := paru.mutation.ProjectStatus(); ok {
		_spec.SetField(projectactionrecord.FieldProjectStatus, field.TypeInt32, value)
	}
	if value, ok := paru.mutation.AddedProjectStatus(); ok {
		_spec.AddField(projectactionrecord.FieldProjectStatus, field.TypeInt32, value)
	}
	if value, ok := paru.mutation.ProjectStatusText(); ok {
		_spec.SetField(projectactionrecord.FieldProjectStatusText, field.TypeString, value)
	}
	if value, ok := paru.mutation.Status(); ok {
		_spec.SetField(projectactionrecord.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := paru.mutation.AddedStatus(); ok {
		_spec.AddField(projectactionrecord.FieldStatus, field.TypeInt8, value)
	}
	if paru.mutation.StatusCleared() {
		_spec.ClearField(projectactionrecord.FieldStatus, field.TypeInt8)
	}
	if value, ok := paru.mutation.CreatedAt(); ok {
		_spec.SetField(projectactionrecord.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := paru.mutation.UpdatedAt(); ok {
		_spec.SetField(projectactionrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(paru.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, paru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectactionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	paru.mutation.done = true
	return n, nil
}

// ProjectActionRecordUpdateOne is the builder for updating a single ProjectActionRecord entity.
type ProjectActionRecordUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProjectActionRecordMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTenantID sets the "tenant_id" field.
func (paruo *ProjectActionRecordUpdateOne) SetTenantID(i int32) *ProjectActionRecordUpdateOne {
	paruo.mutation.ResetTenantID()
	paruo.mutation.SetTenantID(i)
	return paruo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableTenantID(i *int32) *ProjectActionRecordUpdateOne {
	if i != nil {
		paruo.SetTenantID(*i)
	}
	return paruo
}

// AddTenantID adds i to the "tenant_id" field.
func (paruo *ProjectActionRecordUpdateOne) AddTenantID(i int32) *ProjectActionRecordUpdateOne {
	paruo.mutation.AddTenantID(i)
	return paruo
}

// SetProjectID sets the "project_id" field.
func (paruo *ProjectActionRecordUpdateOne) SetProjectID(i int32) *ProjectActionRecordUpdateOne {
	paruo.mutation.ResetProjectID()
	paruo.mutation.SetProjectID(i)
	return paruo
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableProjectID(i *int32) *ProjectActionRecordUpdateOne {
	if i != nil {
		paruo.SetProjectID(*i)
	}
	return paruo
}

// AddProjectID adds i to the "project_id" field.
func (paruo *ProjectActionRecordUpdateOne) AddProjectID(i int32) *ProjectActionRecordUpdateOne {
	paruo.mutation.AddProjectID(i)
	return paruo
}

// SetActionPlat sets the "action_plat" field.
func (paruo *ProjectActionRecordUpdateOne) SetActionPlat(i int8) *ProjectActionRecordUpdateOne {
	paruo.mutation.ResetActionPlat()
	paruo.mutation.SetActionPlat(i)
	return paruo
}

// SetNillableActionPlat sets the "action_plat" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableActionPlat(i *int8) *ProjectActionRecordUpdateOne {
	if i != nil {
		paruo.SetActionPlat(*i)
	}
	return paruo
}

// AddActionPlat adds i to the "action_plat" field.
func (paruo *ProjectActionRecordUpdateOne) AddActionPlat(i int8) *ProjectActionRecordUpdateOne {
	paruo.mutation.AddActionPlat(i)
	return paruo
}

// SetAction sets the "action" field.
func (paruo *ProjectActionRecordUpdateOne) SetAction(s string) *ProjectActionRecordUpdateOne {
	paruo.mutation.SetAction(s)
	return paruo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableAction(s *string) *ProjectActionRecordUpdateOne {
	if s != nil {
		paruo.SetAction(*s)
	}
	return paruo
}

// SetAccountID sets the "account_id" field.
func (paruo *ProjectActionRecordUpdateOne) SetAccountID(i int32) *ProjectActionRecordUpdateOne {
	paruo.mutation.ResetAccountID()
	paruo.mutation.SetAccountID(i)
	return paruo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableAccountID(i *int32) *ProjectActionRecordUpdateOne {
	if i != nil {
		paruo.SetAccountID(*i)
	}
	return paruo
}

// AddAccountID adds i to the "account_id" field.
func (paruo *ProjectActionRecordUpdateOne) AddAccountID(i int32) *ProjectActionRecordUpdateOne {
	paruo.mutation.AddAccountID(i)
	return paruo
}

// ClearAccountID clears the value of the "account_id" field.
func (paruo *ProjectActionRecordUpdateOne) ClearAccountID() *ProjectActionRecordUpdateOne {
	paruo.mutation.ClearAccountID()
	return paruo
}

// SetAccountName sets the "account_name" field.
func (paruo *ProjectActionRecordUpdateOne) SetAccountName(s string) *ProjectActionRecordUpdateOne {
	paruo.mutation.SetAccountName(s)
	return paruo
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableAccountName(s *string) *ProjectActionRecordUpdateOne {
	if s != nil {
		paruo.SetAccountName(*s)
	}
	return paruo
}

// ClearAccountName clears the value of the "account_name" field.
func (paruo *ProjectActionRecordUpdateOne) ClearAccountName() *ProjectActionRecordUpdateOne {
	paruo.mutation.ClearAccountName()
	return paruo
}

// SetProjectStatus sets the "project_status" field.
func (paruo *ProjectActionRecordUpdateOne) SetProjectStatus(i int32) *ProjectActionRecordUpdateOne {
	paruo.mutation.ResetProjectStatus()
	paruo.mutation.SetProjectStatus(i)
	return paruo
}

// SetNillableProjectStatus sets the "project_status" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableProjectStatus(i *int32) *ProjectActionRecordUpdateOne {
	if i != nil {
		paruo.SetProjectStatus(*i)
	}
	return paruo
}

// AddProjectStatus adds i to the "project_status" field.
func (paruo *ProjectActionRecordUpdateOne) AddProjectStatus(i int32) *ProjectActionRecordUpdateOne {
	paruo.mutation.AddProjectStatus(i)
	return paruo
}

// SetProjectStatusText sets the "project_status_text" field.
func (paruo *ProjectActionRecordUpdateOne) SetProjectStatusText(s string) *ProjectActionRecordUpdateOne {
	paruo.mutation.SetProjectStatusText(s)
	return paruo
}

// SetNillableProjectStatusText sets the "project_status_text" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableProjectStatusText(s *string) *ProjectActionRecordUpdateOne {
	if s != nil {
		paruo.SetProjectStatusText(*s)
	}
	return paruo
}

// SetStatus sets the "status" field.
func (paruo *ProjectActionRecordUpdateOne) SetStatus(i int8) *ProjectActionRecordUpdateOne {
	paruo.mutation.ResetStatus()
	paruo.mutation.SetStatus(i)
	return paruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableStatus(i *int8) *ProjectActionRecordUpdateOne {
	if i != nil {
		paruo.SetStatus(*i)
	}
	return paruo
}

// AddStatus adds i to the "status" field.
func (paruo *ProjectActionRecordUpdateOne) AddStatus(i int8) *ProjectActionRecordUpdateOne {
	paruo.mutation.AddStatus(i)
	return paruo
}

// ClearStatus clears the value of the "status" field.
func (paruo *ProjectActionRecordUpdateOne) ClearStatus() *ProjectActionRecordUpdateOne {
	paruo.mutation.ClearStatus()
	return paruo
}

// SetCreatedAt sets the "created_at" field.
func (paruo *ProjectActionRecordUpdateOne) SetCreatedAt(t time.Time) *ProjectActionRecordUpdateOne {
	paruo.mutation.SetCreatedAt(t)
	return paruo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableCreatedAt(t *time.Time) *ProjectActionRecordUpdateOne {
	if t != nil {
		paruo.SetCreatedAt(*t)
	}
	return paruo
}

// SetUpdatedAt sets the "updated_at" field.
func (paruo *ProjectActionRecordUpdateOne) SetUpdatedAt(t time.Time) *ProjectActionRecordUpdateOne {
	paruo.mutation.SetUpdatedAt(t)
	return paruo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (paruo *ProjectActionRecordUpdateOne) SetNillableUpdatedAt(t *time.Time) *ProjectActionRecordUpdateOne {
	if t != nil {
		paruo.SetUpdatedAt(*t)
	}
	return paruo
}

// Mutation returns the ProjectActionRecordMutation object of the builder.
func (paruo *ProjectActionRecordUpdateOne) Mutation() *ProjectActionRecordMutation {
	return paruo.mutation
}

// Where appends a list predicates to the ProjectActionRecordUpdate builder.
func (paruo *ProjectActionRecordUpdateOne) Where(ps ...predicate.ProjectActionRecord) *ProjectActionRecordUpdateOne {
	paruo.mutation.Where(ps...)
	return paruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (paruo *ProjectActionRecordUpdateOne) Select(field string, fields ...string) *ProjectActionRecordUpdateOne {
	paruo.fields = append([]string{field}, fields...)
	return paruo
}

// Save executes the query and returns the updated ProjectActionRecord entity.
func (paruo *ProjectActionRecordUpdateOne) Save(ctx context.Context) (*ProjectActionRecord, error) {
	return withHooks(ctx, paruo.sqlSave, paruo.mutation, paruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (paruo *ProjectActionRecordUpdateOne) SaveX(ctx context.Context) *ProjectActionRecord {
	node, err := paruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (paruo *ProjectActionRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := paruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (paruo *ProjectActionRecordUpdateOne) ExecX(ctx context.Context) {
	if err := paruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (paruo *ProjectActionRecordUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProjectActionRecordUpdateOne {
	paruo.modifiers = append(paruo.modifiers, modifiers...)
	return paruo
}

func (paruo *ProjectActionRecordUpdateOne) sqlSave(ctx context.Context) (_node *ProjectActionRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(projectactionrecord.Table, projectactionrecord.Columns, sqlgraph.NewFieldSpec(projectactionrecord.FieldID, field.TypeInt32))
	id, ok := paruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectActionRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := paruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectactionrecord.FieldID)
		for _, f := range fields {
			if !projectactionrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectactionrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := paruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := paruo.mutation.TenantID(); ok {
		_spec.SetField(projectactionrecord.FieldTenantID, field.TypeInt32, value)
	}
	if value, ok := paruo.mutation.AddedTenantID(); ok {
		_spec.AddField(projectactionrecord.FieldTenantID, field.TypeInt32, value)
	}
	if value, ok := paruo.mutation.ProjectID(); ok {
		_spec.SetField(projectactionrecord.FieldProjectID, field.TypeInt32, value)
	}
	if value, ok := paruo.mutation.AddedProjectID(); ok {
		_spec.AddField(projectactionrecord.FieldProjectID, field.TypeInt32, value)
	}
	if value, ok := paruo.mutation.ActionPlat(); ok {
		_spec.SetField(projectactionrecord.FieldActionPlat, field.TypeInt8, value)
	}
	if value, ok := paruo.mutation.AddedActionPlat(); ok {
		_spec.AddField(projectactionrecord.FieldActionPlat, field.TypeInt8, value)
	}
	if value, ok := paruo.mutation.Action(); ok {
		_spec.SetField(projectactionrecord.FieldAction, field.TypeString, value)
	}
	if value, ok := paruo.mutation.AccountID(); ok {
		_spec.SetField(projectactionrecord.FieldAccountID, field.TypeInt32, value)
	}
	if value, ok := paruo.mutation.AddedAccountID(); ok {
		_spec.AddField(projectactionrecord.FieldAccountID, field.TypeInt32, value)
	}
	if paruo.mutation.AccountIDCleared() {
		_spec.ClearField(projectactionrecord.FieldAccountID, field.TypeInt32)
	}
	if value, ok := paruo.mutation.AccountName(); ok {
		_spec.SetField(projectactionrecord.FieldAccountName, field.TypeString, value)
	}
	if paruo.mutation.AccountNameCleared() {
		_spec.ClearField(projectactionrecord.FieldAccountName, field.TypeString)
	}
	if value, ok := paruo.mutation.ProjectStatus(); ok {
		_spec.SetField(projectactionrecord.FieldProjectStatus, field.TypeInt32, value)
	}
	if value, ok := paruo.mutation.AddedProjectStatus(); ok {
		_spec.AddField(projectactionrecord.FieldProjectStatus, field.TypeInt32, value)
	}
	if value, ok := paruo.mutation.ProjectStatusText(); ok {
		_spec.SetField(projectactionrecord.FieldProjectStatusText, field.TypeString, value)
	}
	if value, ok := paruo.mutation.Status(); ok {
		_spec.SetField(projectactionrecord.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := paruo.mutation.AddedStatus(); ok {
		_spec.AddField(projectactionrecord.FieldStatus, field.TypeInt8, value)
	}
	if paruo.mutation.StatusCleared() {
		_spec.ClearField(projectactionrecord.FieldStatus, field.TypeInt8)
	}
	if value, ok := paruo.mutation.CreatedAt(); ok {
		_spec.SetField(projectactionrecord.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := paruo.mutation.UpdatedAt(); ok {
		_spec.SetField(projectactionrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(paruo.modifiers...)
	_node = &ProjectActionRecord{config: paruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, paruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectactionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	paruo.mutation.done = true
	return _node, nil
}
