// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"go-study/app/database/tabtaba/internal/data/ent/predicate"
	"go-study/app/database/tabtaba/internal/data/ent/projectactionrecord"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectActionRecordQuery is the builder for querying ProjectActionRecord entities.
type ProjectActionRecordQuery struct {
	config
	ctx        *QueryContext
	order      []projectactionrecord.OrderOption
	inters     []Interceptor
	predicates []predicate.ProjectActionRecord
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProjectActionRecordQuery builder.
func (parq *ProjectActionRecordQuery) Where(ps ...predicate.ProjectActionRecord) *ProjectActionRecordQuery {
	parq.predicates = append(parq.predicates, ps...)
	return parq
}

// Limit the number of records to be returned by this query.
func (parq *ProjectActionRecordQuery) Limit(limit int) *ProjectActionRecordQuery {
	parq.ctx.Limit = &limit
	return parq
}

// Offset to start from.
func (parq *ProjectActionRecordQuery) Offset(offset int) *ProjectActionRecordQuery {
	parq.ctx.Offset = &offset
	return parq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (parq *ProjectActionRecordQuery) Unique(unique bool) *ProjectActionRecordQuery {
	parq.ctx.Unique = &unique
	return parq
}

// Order specifies how the records should be ordered.
func (parq *ProjectActionRecordQuery) Order(o ...projectactionrecord.OrderOption) *ProjectActionRecordQuery {
	parq.order = append(parq.order, o...)
	return parq
}

// First returns the first ProjectActionRecord entity from the query.
// Returns a *NotFoundError when no ProjectActionRecord was found.
func (parq *ProjectActionRecordQuery) First(ctx context.Context) (*ProjectActionRecord, error) {
	nodes, err := parq.Limit(1).All(setContextOp(ctx, parq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{projectactionrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (parq *ProjectActionRecordQuery) FirstX(ctx context.Context) *ProjectActionRecord {
	node, err := parq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProjectActionRecord ID from the query.
// Returns a *NotFoundError when no ProjectActionRecord ID was found.
func (parq *ProjectActionRecordQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = parq.Limit(1).IDs(setContextOp(ctx, parq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{projectactionrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (parq *ProjectActionRecordQuery) FirstIDX(ctx context.Context) int32 {
	id, err := parq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProjectActionRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProjectActionRecord entity is found.
// Returns a *NotFoundError when no ProjectActionRecord entities are found.
func (parq *ProjectActionRecordQuery) Only(ctx context.Context) (*ProjectActionRecord, error) {
	nodes, err := parq.Limit(2).All(setContextOp(ctx, parq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{projectactionrecord.Label}
	default:
		return nil, &NotSingularError{projectactionrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (parq *ProjectActionRecordQuery) OnlyX(ctx context.Context) *ProjectActionRecord {
	node, err := parq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProjectActionRecord ID in the query.
// Returns a *NotSingularError when more than one ProjectActionRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (parq *ProjectActionRecordQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = parq.Limit(2).IDs(setContextOp(ctx, parq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{projectactionrecord.Label}
	default:
		err = &NotSingularError{projectactionrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (parq *ProjectActionRecordQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := parq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProjectActionRecords.
func (parq *ProjectActionRecordQuery) All(ctx context.Context) ([]*ProjectActionRecord, error) {
	ctx = setContextOp(ctx, parq.ctx, ent.OpQueryAll)
	if err := parq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProjectActionRecord, *ProjectActionRecordQuery]()
	return withInterceptors[[]*ProjectActionRecord](ctx, parq, qr, parq.inters)
}

// AllX is like All, but panics if an error occurs.
func (parq *ProjectActionRecordQuery) AllX(ctx context.Context) []*ProjectActionRecord {
	nodes, err := parq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProjectActionRecord IDs.
func (parq *ProjectActionRecordQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if parq.ctx.Unique == nil && parq.path != nil {
		parq.Unique(true)
	}
	ctx = setContextOp(ctx, parq.ctx, ent.OpQueryIDs)
	if err = parq.Select(projectactionrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (parq *ProjectActionRecordQuery) IDsX(ctx context.Context) []int32 {
	ids, err := parq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (parq *ProjectActionRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, parq.ctx, ent.OpQueryCount)
	if err := parq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, parq, querierCount[*ProjectActionRecordQuery](), parq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (parq *ProjectActionRecordQuery) CountX(ctx context.Context) int {
	count, err := parq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (parq *ProjectActionRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, parq.ctx, ent.OpQueryExist)
	switch _, err := parq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (parq *ProjectActionRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := parq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProjectActionRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (parq *ProjectActionRecordQuery) Clone() *ProjectActionRecordQuery {
	if parq == nil {
		return nil
	}
	return &ProjectActionRecordQuery{
		config:     parq.config,
		ctx:        parq.ctx.Clone(),
		order:      append([]projectactionrecord.OrderOption{}, parq.order...),
		inters:     append([]Interceptor{}, parq.inters...),
		predicates: append([]predicate.ProjectActionRecord{}, parq.predicates...),
		// clone intermediate query.
		sql:       parq.sql.Clone(),
		path:      parq.path,
		modifiers: append([]func(*sql.Selector){}, parq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID int32 `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProjectActionRecord.Query().
//		GroupBy(projectactionrecord.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (parq *ProjectActionRecordQuery) GroupBy(field string, fields ...string) *ProjectActionRecordGroupBy {
	parq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProjectActionRecordGroupBy{build: parq}
	grbuild.flds = &parq.ctx.Fields
	grbuild.label = projectactionrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID int32 `json:"tenant_id,omitempty"`
//	}
//
//	client.ProjectActionRecord.Query().
//		Select(projectactionrecord.FieldTenantID).
//		Scan(ctx, &v)
func (parq *ProjectActionRecordQuery) Select(fields ...string) *ProjectActionRecordSelect {
	parq.ctx.Fields = append(parq.ctx.Fields, fields...)
	sbuild := &ProjectActionRecordSelect{ProjectActionRecordQuery: parq}
	sbuild.label = projectactionrecord.Label
	sbuild.flds, sbuild.scan = &parq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProjectActionRecordSelect configured with the given aggregations.
func (parq *ProjectActionRecordQuery) Aggregate(fns ...AggregateFunc) *ProjectActionRecordSelect {
	return parq.Select().Aggregate(fns...)
}

func (parq *ProjectActionRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range parq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, parq); err != nil {
				return err
			}
		}
	}
	for _, f := range parq.ctx.Fields {
		if !projectactionrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if parq.path != nil {
		prev, err := parq.path(ctx)
		if err != nil {
			return err
		}
		parq.sql = prev
	}
	return nil
}

func (parq *ProjectActionRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProjectActionRecord, error) {
	var (
		nodes = []*ProjectActionRecord{}
		_spec = parq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProjectActionRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProjectActionRecord{config: parq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(parq.modifiers) > 0 {
		_spec.Modifiers = parq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, parq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (parq *ProjectActionRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := parq.querySpec()
	if len(parq.modifiers) > 0 {
		_spec.Modifiers = parq.modifiers
	}
	_spec.Node.Columns = parq.ctx.Fields
	if len(parq.ctx.Fields) > 0 {
		_spec.Unique = parq.ctx.Unique != nil && *parq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, parq.driver, _spec)
}

func (parq *ProjectActionRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(projectactionrecord.Table, projectactionrecord.Columns, sqlgraph.NewFieldSpec(projectactionrecord.FieldID, field.TypeInt32))
	_spec.From = parq.sql
	if unique := parq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if parq.path != nil {
		_spec.Unique = true
	}
	if fields := parq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectactionrecord.FieldID)
		for i := range fields {
			if fields[i] != projectactionrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := parq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := parq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := parq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := parq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (parq *ProjectActionRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(parq.driver.Dialect())
	t1 := builder.Table(projectactionrecord.Table)
	columns := parq.ctx.Fields
	if len(columns) == 0 {
		columns = projectactionrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if parq.sql != nil {
		selector = parq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if parq.ctx.Unique != nil && *parq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range parq.modifiers {
		m(selector)
	}
	for _, p := range parq.predicates {
		p(selector)
	}
	for _, p := range parq.order {
		p(selector)
	}
	if offset := parq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := parq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (parq *ProjectActionRecordQuery) Modify(modifiers ...func(s *sql.Selector)) *ProjectActionRecordSelect {
	parq.modifiers = append(parq.modifiers, modifiers...)
	return parq.Select()
}

// ProjectActionRecordGroupBy is the group-by builder for ProjectActionRecord entities.
type ProjectActionRecordGroupBy struct {
	selector
	build *ProjectActionRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pargb *ProjectActionRecordGroupBy) Aggregate(fns ...AggregateFunc) *ProjectActionRecordGroupBy {
	pargb.fns = append(pargb.fns, fns...)
	return pargb
}

// Scan applies the selector query and scans the result into the given value.
func (pargb *ProjectActionRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pargb.build.ctx, ent.OpQueryGroupBy)
	if err := pargb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectActionRecordQuery, *ProjectActionRecordGroupBy](ctx, pargb.build, pargb, pargb.build.inters, v)
}

func (pargb *ProjectActionRecordGroupBy) sqlScan(ctx context.Context, root *ProjectActionRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pargb.fns))
	for _, fn := range pargb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pargb.flds)+len(pargb.fns))
		for _, f := range *pargb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pargb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pargb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProjectActionRecordSelect is the builder for selecting fields of ProjectActionRecord entities.
type ProjectActionRecordSelect struct {
	*ProjectActionRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pars *ProjectActionRecordSelect) Aggregate(fns ...AggregateFunc) *ProjectActionRecordSelect {
	pars.fns = append(pars.fns, fns...)
	return pars
}

// Scan applies the selector query and scans the result into the given value.
func (pars *ProjectActionRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pars.ctx, ent.OpQuerySelect)
	if err := pars.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectActionRecordQuery, *ProjectActionRecordSelect](ctx, pars.ProjectActionRecordQuery, pars, pars.inters, v)
}

func (pars *ProjectActionRecordSelect) sqlScan(ctx context.Context, root *ProjectActionRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pars.fns))
	for _, fn := range pars.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pars.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pars.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pars *ProjectActionRecordSelect) Modify(modifiers ...func(s *sql.Selector)) *ProjectActionRecordSelect {
	pars.modifiers = append(pars.modifiers, modifiers...)
	return pars
}
