// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-study/app/database/tabtaba/internal/data/ent/predicate"
	"go-study/app/database/tabtaba/internal/data/ent/projectactionrecord"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectActionRecordDelete is the builder for deleting a ProjectActionRecord entity.
type ProjectActionRecordDelete struct {
	config
	hooks    []Hook
	mutation *ProjectActionRecordMutation
}

// Where appends a list predicates to the ProjectActionRecordDelete builder.
func (pard *ProjectActionRecordDelete) Where(ps ...predicate.ProjectActionRecord) *ProjectActionRecordDelete {
	pard.mutation.Where(ps...)
	return pard
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pard *ProjectActionRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pard.sqlExec, pard.mutation, pard.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pard *ProjectActionRecordDelete) ExecX(ctx context.Context) int {
	n, err := pard.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pard *ProjectActionRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(projectactionrecord.Table, sqlgraph.NewFieldSpec(projectactionrecord.FieldID, field.TypeInt32))
	if ps := pard.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pard.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pard.mutation.done = true
	return affected, err
}

// ProjectActionRecordDeleteOne is the builder for deleting a single ProjectActionRecord entity.
type ProjectActionRecordDeleteOne struct {
	pard *ProjectActionRecordDelete
}

// Where appends a list predicates to the ProjectActionRecordDelete builder.
func (pardo *ProjectActionRecordDeleteOne) Where(ps ...predicate.ProjectActionRecord) *ProjectActionRecordDeleteOne {
	pardo.pard.mutation.Where(ps...)
	return pardo
}

// Exec executes the deletion query.
func (pardo *ProjectActionRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := pardo.pard.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projectactionrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pardo *ProjectActionRecordDeleteOne) ExecX(ctx context.Context) {
	if err := pardo.Exec(ctx); err != nil {
		panic(err)
	}
}
