// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-study/app/database/tabtaba/internal/data/ent/finance"
	"go-study/app/database/tabtaba/internal/data/ent/project"
	"go-study/app/database/tabtaba/internal/data/ent/projectactionrecord"
	"go-study/app/database/tabtaba/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	financeFields := schema.Finance{}.Fields()
	_ = financeFields
	// financeDescTenantID is the schema descriptor for tenant_id field.
	financeDescTenantID := financeFields[1].Descriptor()
	// finance.DefaultTenantID holds the default value on creation for the tenant_id field.
	finance.DefaultTenantID = financeDescTenantID.Default.(int32)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescTenantID is the schema descriptor for tenant_id field.
	projectDescTenantID := projectFields[1].Descriptor()
	// project.DefaultTenantID holds the default value on creation for the tenant_id field.
	project.DefaultTenantID = projectDescTenantID.Default.(int32)
	// projectDescAmount is the schema descriptor for amount field.
	projectDescAmount := projectFields[13].Descriptor()
	// project.DefaultAmount holds the default value on creation for the amount field.
	project.DefaultAmount = projectDescAmount.Default.(float64)
	// projectDescPaidAmount is the schema descriptor for paid_amount field.
	projectDescPaidAmount := projectFields[14].Descriptor()
	// project.DefaultPaidAmount holds the default value on creation for the paid_amount field.
	project.DefaultPaidAmount = projectDescPaidAmount.Default.(float64)
	// projectDescUnpaidAmount is the schema descriptor for unpaid_amount field.
	projectDescUnpaidAmount := projectFields[15].Descriptor()
	// project.DefaultUnpaidAmount holds the default value on creation for the unpaid_amount field.
	project.DefaultUnpaidAmount = projectDescUnpaidAmount.Default.(float64)
	// projectDescFinanceInvoiceStatus is the schema descriptor for finance_invoice_status field.
	projectDescFinanceInvoiceStatus := projectFields[18].Descriptor()
	// project.DefaultFinanceInvoiceStatus holds the default value on creation for the finance_invoice_status field.
	project.DefaultFinanceInvoiceStatus = projectDescFinanceInvoiceStatus.Default.(int8)
	// projectDescESignStatus is the schema descriptor for e_sign_status field.
	projectDescESignStatus := projectFields[20].Descriptor()
	// project.DefaultESignStatus holds the default value on creation for the e_sign_status field.
	project.DefaultESignStatus = projectDescESignStatus.Default.(int8)
	// projectDescScore is the schema descriptor for score field.
	projectDescScore := projectFields[22].Descriptor()
	// project.DefaultScore holds the default value on creation for the score field.
	project.DefaultScore = projectDescScore.Default.(float64)
	// projectDescPayMoney is the schema descriptor for pay_money field.
	projectDescPayMoney := projectFields[28].Descriptor()
	// project.DefaultPayMoney holds the default value on creation for the pay_money field.
	project.DefaultPayMoney = projectDescPayMoney.Default.(float64)
	projectactionrecordFields := schema.ProjectActionRecord{}.Fields()
	_ = projectactionrecordFields
	// projectactionrecordDescTenantID is the schema descriptor for tenant_id field.
	projectactionrecordDescTenantID := projectactionrecordFields[1].Descriptor()
	// projectactionrecord.DefaultTenantID holds the default value on creation for the tenant_id field.
	projectactionrecord.DefaultTenantID = projectactionrecordDescTenantID.Default.(int32)
	// projectactionrecordDescActionPlat is the schema descriptor for action_plat field.
	projectactionrecordDescActionPlat := projectactionrecordFields[3].Descriptor()
	// projectactionrecord.DefaultActionPlat holds the default value on creation for the action_plat field.
	projectactionrecord.DefaultActionPlat = projectactionrecordDescActionPlat.Default.(int8)
	// projectactionrecordDescAction is the schema descriptor for action field.
	projectactionrecordDescAction := projectactionrecordFields[4].Descriptor()
	// projectactionrecord.DefaultAction holds the default value on creation for the action field.
	projectactionrecord.DefaultAction = projectactionrecordDescAction.Default.(string)
	// projectactionrecordDescAccountID is the schema descriptor for account_id field.
	projectactionrecordDescAccountID := projectactionrecordFields[5].Descriptor()
	// projectactionrecord.DefaultAccountID holds the default value on creation for the account_id field.
	projectactionrecord.DefaultAccountID = projectactionrecordDescAccountID.Default.(int32)
	// projectactionrecordDescAccountName is the schema descriptor for account_name field.
	projectactionrecordDescAccountName := projectactionrecordFields[6].Descriptor()
	// projectactionrecord.DefaultAccountName holds the default value on creation for the account_name field.
	projectactionrecord.DefaultAccountName = projectactionrecordDescAccountName.Default.(string)
	// projectactionrecordDescProjectStatusText is the schema descriptor for project_status_text field.
	projectactionrecordDescProjectStatusText := projectactionrecordFields[8].Descriptor()
	// projectactionrecord.DefaultProjectStatusText holds the default value on creation for the project_status_text field.
	projectactionrecord.DefaultProjectStatusText = projectactionrecordDescProjectStatusText.Default.(string)
	// projectactionrecordDescStatus is the schema descriptor for status field.
	projectactionrecordDescStatus := projectactionrecordFields[9].Descriptor()
	// projectactionrecord.DefaultStatus holds the default value on creation for the status field.
	projectactionrecord.DefaultStatus = projectactionrecordDescStatus.Default.(int8)
}
