// Code generated by ent, DO NOT EDIT.

package project

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountPhone holds the string denoting the account_phone field in the database.
	FieldAccountPhone = "account_phone"
	// FieldWorkerAccountID holds the string denoting the worker_account_id field in the database.
	FieldWorkerAccountID = "worker_account_id"
	// FieldProjectType holds the string denoting the project_type field in the database.
	FieldProjectType = "project_type"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldExpectDeliverTime holds the string denoting the expect_deliver_time field in the database.
	FieldExpectDeliverTime = "expect_deliver_time"
	// FieldTenderFiles holds the string denoting the tender_files field in the database.
	FieldTenderFiles = "tender_files"
	// FieldDeliverBidFiles holds the string denoting the deliver_bid_files field in the database.
	FieldDeliverBidFiles = "deliver_bid_files"
	// FieldDeliverBidTime holds the string denoting the deliver_bid_time field in the database.
	FieldDeliverBidTime = "deliver_bid_time"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldProjectStatus holds the string denoting the project_status field in the database.
	FieldProjectStatus = "project_status"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPaidAmount holds the string denoting the paid_amount field in the database.
	FieldPaidAmount = "paid_amount"
	// FieldUnpaidAmount holds the string denoting the unpaid_amount field in the database.
	FieldUnpaidAmount = "unpaid_amount"
	// FieldCommission holds the string denoting the commission field in the database.
	FieldCommission = "commission"
	// FieldWorkerCommission holds the string denoting the worker_commission field in the database.
	FieldWorkerCommission = "worker_commission"
	// FieldFinanceInvoiceStatus holds the string denoting the finance_invoice_status field in the database.
	FieldFinanceInvoiceStatus = "finance_invoice_status"
	// FieldESignID holds the string denoting the e_sign_id field in the database.
	FieldESignID = "e_sign_id"
	// FieldESignStatus holds the string denoting the e_sign_status field in the database.
	FieldESignStatus = "e_sign_status"
	// FieldESignNotify holds the string denoting the e_sign_notify field in the database.
	FieldESignNotify = "e_sign_notify"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldEvaluate holds the string denoting the evaluate field in the database.
	FieldEvaluate = "evaluate"
	// FieldCancelReason holds the string denoting the cancel_reason field in the database.
	FieldCancelReason = "cancel_reason"
	// FieldCloseAt holds the string denoting the close_at field in the database.
	FieldCloseAt = "close_at"
	// FieldChannelCode holds the string denoting the channel_code field in the database.
	FieldChannelCode = "channel_code"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldPayMoney holds the string denoting the pay_money field in the database.
	FieldPayMoney = "pay_money"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the project in the database.
	Table = "project"
)

// Columns holds all SQL columns for project fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldAccountID,
	FieldAccountPhone,
	FieldWorkerAccountID,
	FieldProjectType,
	FieldTitle,
	FieldExpectDeliverTime,
	FieldTenderFiles,
	FieldDeliverBidFiles,
	FieldDeliverBidTime,
	FieldRemark,
	FieldProjectStatus,
	FieldAmount,
	FieldPaidAmount,
	FieldUnpaidAmount,
	FieldCommission,
	FieldWorkerCommission,
	FieldFinanceInvoiceStatus,
	FieldESignID,
	FieldESignStatus,
	FieldESignNotify,
	FieldScore,
	FieldEvaluate,
	FieldCancelReason,
	FieldCloseAt,
	FieldChannelCode,
	FieldCreatedAt,
	FieldPayMoney,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID int32
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultPaidAmount holds the default value on creation for the "paid_amount" field.
	DefaultPaidAmount float64
	// DefaultUnpaidAmount holds the default value on creation for the "unpaid_amount" field.
	DefaultUnpaidAmount float64
	// DefaultFinanceInvoiceStatus holds the default value on creation for the "finance_invoice_status" field.
	DefaultFinanceInvoiceStatus int8
	// DefaultESignStatus holds the default value on creation for the "e_sign_status" field.
	DefaultESignStatus int8
	// DefaultScore holds the default value on creation for the "score" field.
	DefaultScore float64
	// DefaultPayMoney holds the default value on creation for the "pay_money" field.
	DefaultPayMoney float64
)

// OrderOption defines the ordering options for the Project queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountPhone orders the results by the account_phone field.
func ByAccountPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountPhone, opts...).ToFunc()
}

// ByWorkerAccountID orders the results by the worker_account_id field.
func ByWorkerAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkerAccountID, opts...).ToFunc()
}

// ByProjectType orders the results by the project_type field.
func ByProjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectType, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByExpectDeliverTime orders the results by the expect_deliver_time field.
func ByExpectDeliverTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectDeliverTime, opts...).ToFunc()
}

// ByTenderFiles orders the results by the tender_files field.
func ByTenderFiles(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenderFiles, opts...).ToFunc()
}

// ByDeliverBidFiles orders the results by the deliver_bid_files field.
func ByDeliverBidFiles(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliverBidFiles, opts...).ToFunc()
}

// ByDeliverBidTime orders the results by the deliver_bid_time field.
func ByDeliverBidTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliverBidTime, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByProjectStatus orders the results by the project_status field.
func ByProjectStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectStatus, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByPaidAmount orders the results by the paid_amount field.
func ByPaidAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAmount, opts...).ToFunc()
}

// ByUnpaidAmount orders the results by the unpaid_amount field.
func ByUnpaidAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnpaidAmount, opts...).ToFunc()
}

// ByCommission orders the results by the commission field.
func ByCommission(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommission, opts...).ToFunc()
}

// ByWorkerCommission orders the results by the worker_commission field.
func ByWorkerCommission(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkerCommission, opts...).ToFunc()
}

// ByFinanceInvoiceStatus orders the results by the finance_invoice_status field.
func ByFinanceInvoiceStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinanceInvoiceStatus, opts...).ToFunc()
}

// ByESignID orders the results by the e_sign_id field.
func ByESignID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldESignID, opts...).ToFunc()
}

// ByESignStatus orders the results by the e_sign_status field.
func ByESignStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldESignStatus, opts...).ToFunc()
}

// ByESignNotify orders the results by the e_sign_notify field.
func ByESignNotify(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldESignNotify, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByEvaluate orders the results by the evaluate field.
func ByEvaluate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvaluate, opts...).ToFunc()
}

// ByCancelReason orders the results by the cancel_reason field.
func ByCancelReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelReason, opts...).ToFunc()
}

// ByCloseAt orders the results by the close_at field.
func ByCloseAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCloseAt, opts...).ToFunc()
}

// ByChannelCode orders the results by the channel_code field.
func ByChannelCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelCode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPayMoney orders the results by the pay_money field.
func ByPayMoney(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayMoney, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
