// Code generated by ent, DO NOT EDIT.

package project

import (
	"go-study/app/database/tabtaba/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int32) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int32) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int32) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int32) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int32) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int32) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int32) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int32) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int32) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int32) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTenantID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int32) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldAccountID, v))
}

// AccountPhone applies equality check predicate on the "account_phone" field. It's identical to AccountPhoneEQ.
func AccountPhone(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldAccountPhone, v))
}

// WorkerAccountID applies equality check predicate on the "worker_account_id" field. It's identical to WorkerAccountIDEQ.
func WorkerAccountID(v int32) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldWorkerAccountID, v))
}

// ProjectType applies equality check predicate on the "project_type" field. It's identical to ProjectTypeEQ.
func ProjectType(v int8) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldProjectType, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTitle, v))
}

// ExpectDeliverTime applies equality check predicate on the "expect_deliver_time" field. It's identical to ExpectDeliverTimeEQ.
func ExpectDeliverTime(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldExpectDeliverTime, v))
}

// TenderFiles applies equality check predicate on the "tender_files" field. It's identical to TenderFilesEQ.
func TenderFiles(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTenderFiles, v))
}

// DeliverBidFiles applies equality check predicate on the "deliver_bid_files" field. It's identical to DeliverBidFilesEQ.
func DeliverBidFiles(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldDeliverBidFiles, v))
}

// DeliverBidTime applies equality check predicate on the "deliver_bid_time" field. It's identical to DeliverBidTimeEQ.
func DeliverBidTime(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldDeliverBidTime, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldRemark, v))
}

// ProjectStatus applies equality check predicate on the "project_status" field. It's identical to ProjectStatusEQ.
func ProjectStatus(v int32) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldProjectStatus, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldAmount, v))
}

// PaidAmount applies equality check predicate on the "paid_amount" field. It's identical to PaidAmountEQ.
func PaidAmount(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldPaidAmount, v))
}

// UnpaidAmount applies equality check predicate on the "unpaid_amount" field. It's identical to UnpaidAmountEQ.
func UnpaidAmount(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldUnpaidAmount, v))
}

// Commission applies equality check predicate on the "commission" field. It's identical to CommissionEQ.
func Commission(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCommission, v))
}

// WorkerCommission applies equality check predicate on the "worker_commission" field. It's identical to WorkerCommissionEQ.
func WorkerCommission(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldWorkerCommission, v))
}

// FinanceInvoiceStatus applies equality check predicate on the "finance_invoice_status" field. It's identical to FinanceInvoiceStatusEQ.
func FinanceInvoiceStatus(v int8) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldFinanceInvoiceStatus, v))
}

// ESignID applies equality check predicate on the "e_sign_id" field. It's identical to ESignIDEQ.
func ESignID(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldESignID, v))
}

// ESignStatus applies equality check predicate on the "e_sign_status" field. It's identical to ESignStatusEQ.
func ESignStatus(v int8) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldESignStatus, v))
}

// ESignNotify applies equality check predicate on the "e_sign_notify" field. It's identical to ESignNotifyEQ.
func ESignNotify(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldESignNotify, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldScore, v))
}

// Evaluate applies equality check predicate on the "evaluate" field. It's identical to EvaluateEQ.
func Evaluate(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldEvaluate, v))
}

// CancelReason applies equality check predicate on the "cancel_reason" field. It's identical to CancelReasonEQ.
func CancelReason(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCancelReason, v))
}

// CloseAt applies equality check predicate on the "close_at" field. It's identical to CloseAtEQ.
func CloseAt(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCloseAt, v))
}

// ChannelCode applies equality check predicate on the "channel_code" field. It's identical to ChannelCodeEQ.
func ChannelCode(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldChannelCode, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedAt, v))
}

// PayMoney applies equality check predicate on the "pay_money" field. It's identical to PayMoneyEQ.
func PayMoney(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldPayMoney, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int32) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int32) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int32) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int32) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int32) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int32) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int32) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int32) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldTenantID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int32) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int32) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int32) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int32) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int32) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int32) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int32) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int32) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldAccountID, v))
}

// AccountPhoneEQ applies the EQ predicate on the "account_phone" field.
func AccountPhoneEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldAccountPhone, v))
}

// AccountPhoneNEQ applies the NEQ predicate on the "account_phone" field.
func AccountPhoneNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldAccountPhone, v))
}

// AccountPhoneIn applies the In predicate on the "account_phone" field.
func AccountPhoneIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldAccountPhone, vs...))
}

// AccountPhoneNotIn applies the NotIn predicate on the "account_phone" field.
func AccountPhoneNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldAccountPhone, vs...))
}

// AccountPhoneGT applies the GT predicate on the "account_phone" field.
func AccountPhoneGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldAccountPhone, v))
}

// AccountPhoneGTE applies the GTE predicate on the "account_phone" field.
func AccountPhoneGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldAccountPhone, v))
}

// AccountPhoneLT applies the LT predicate on the "account_phone" field.
func AccountPhoneLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldAccountPhone, v))
}

// AccountPhoneLTE applies the LTE predicate on the "account_phone" field.
func AccountPhoneLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldAccountPhone, v))
}

// AccountPhoneContains applies the Contains predicate on the "account_phone" field.
func AccountPhoneContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldAccountPhone, v))
}

// AccountPhoneHasPrefix applies the HasPrefix predicate on the "account_phone" field.
func AccountPhoneHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldAccountPhone, v))
}

// AccountPhoneHasSuffix applies the HasSuffix predicate on the "account_phone" field.
func AccountPhoneHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldAccountPhone, v))
}

// AccountPhoneIsNil applies the IsNil predicate on the "account_phone" field.
func AccountPhoneIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldAccountPhone))
}

// AccountPhoneNotNil applies the NotNil predicate on the "account_phone" field.
func AccountPhoneNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldAccountPhone))
}

// AccountPhoneEqualFold applies the EqualFold predicate on the "account_phone" field.
func AccountPhoneEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldAccountPhone, v))
}

// AccountPhoneContainsFold applies the ContainsFold predicate on the "account_phone" field.
func AccountPhoneContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldAccountPhone, v))
}

// WorkerAccountIDEQ applies the EQ predicate on the "worker_account_id" field.
func WorkerAccountIDEQ(v int32) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldWorkerAccountID, v))
}

// WorkerAccountIDNEQ applies the NEQ predicate on the "worker_account_id" field.
func WorkerAccountIDNEQ(v int32) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldWorkerAccountID, v))
}

// WorkerAccountIDIn applies the In predicate on the "worker_account_id" field.
func WorkerAccountIDIn(vs ...int32) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldWorkerAccountID, vs...))
}

// WorkerAccountIDNotIn applies the NotIn predicate on the "worker_account_id" field.
func WorkerAccountIDNotIn(vs ...int32) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldWorkerAccountID, vs...))
}

// WorkerAccountIDGT applies the GT predicate on the "worker_account_id" field.
func WorkerAccountIDGT(v int32) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldWorkerAccountID, v))
}

// WorkerAccountIDGTE applies the GTE predicate on the "worker_account_id" field.
func WorkerAccountIDGTE(v int32) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldWorkerAccountID, v))
}

// WorkerAccountIDLT applies the LT predicate on the "worker_account_id" field.
func WorkerAccountIDLT(v int32) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldWorkerAccountID, v))
}

// WorkerAccountIDLTE applies the LTE predicate on the "worker_account_id" field.
func WorkerAccountIDLTE(v int32) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldWorkerAccountID, v))
}

// WorkerAccountIDIsNil applies the IsNil predicate on the "worker_account_id" field.
func WorkerAccountIDIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldWorkerAccountID))
}

// WorkerAccountIDNotNil applies the NotNil predicate on the "worker_account_id" field.
func WorkerAccountIDNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldWorkerAccountID))
}

// ProjectTypeEQ applies the EQ predicate on the "project_type" field.
func ProjectTypeEQ(v int8) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldProjectType, v))
}

// ProjectTypeNEQ applies the NEQ predicate on the "project_type" field.
func ProjectTypeNEQ(v int8) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldProjectType, v))
}

// ProjectTypeIn applies the In predicate on the "project_type" field.
func ProjectTypeIn(vs ...int8) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldProjectType, vs...))
}

// ProjectTypeNotIn applies the NotIn predicate on the "project_type" field.
func ProjectTypeNotIn(vs ...int8) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldProjectType, vs...))
}

// ProjectTypeGT applies the GT predicate on the "project_type" field.
func ProjectTypeGT(v int8) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldProjectType, v))
}

// ProjectTypeGTE applies the GTE predicate on the "project_type" field.
func ProjectTypeGTE(v int8) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldProjectType, v))
}

// ProjectTypeLT applies the LT predicate on the "project_type" field.
func ProjectTypeLT(v int8) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldProjectType, v))
}

// ProjectTypeLTE applies the LTE predicate on the "project_type" field.
func ProjectTypeLTE(v int8) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldProjectType, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldTitle, v))
}

// ExpectDeliverTimeEQ applies the EQ predicate on the "expect_deliver_time" field.
func ExpectDeliverTimeEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldExpectDeliverTime, v))
}

// ExpectDeliverTimeNEQ applies the NEQ predicate on the "expect_deliver_time" field.
func ExpectDeliverTimeNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldExpectDeliverTime, v))
}

// ExpectDeliverTimeIn applies the In predicate on the "expect_deliver_time" field.
func ExpectDeliverTimeIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldExpectDeliverTime, vs...))
}

// ExpectDeliverTimeNotIn applies the NotIn predicate on the "expect_deliver_time" field.
func ExpectDeliverTimeNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldExpectDeliverTime, vs...))
}

// ExpectDeliverTimeGT applies the GT predicate on the "expect_deliver_time" field.
func ExpectDeliverTimeGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldExpectDeliverTime, v))
}

// ExpectDeliverTimeGTE applies the GTE predicate on the "expect_deliver_time" field.
func ExpectDeliverTimeGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldExpectDeliverTime, v))
}

// ExpectDeliverTimeLT applies the LT predicate on the "expect_deliver_time" field.
func ExpectDeliverTimeLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldExpectDeliverTime, v))
}

// ExpectDeliverTimeLTE applies the LTE predicate on the "expect_deliver_time" field.
func ExpectDeliverTimeLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldExpectDeliverTime, v))
}

// TenderFilesEQ applies the EQ predicate on the "tender_files" field.
func TenderFilesEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTenderFiles, v))
}

// TenderFilesNEQ applies the NEQ predicate on the "tender_files" field.
func TenderFilesNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldTenderFiles, v))
}

// TenderFilesIn applies the In predicate on the "tender_files" field.
func TenderFilesIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldTenderFiles, vs...))
}

// TenderFilesNotIn applies the NotIn predicate on the "tender_files" field.
func TenderFilesNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldTenderFiles, vs...))
}

// TenderFilesGT applies the GT predicate on the "tender_files" field.
func TenderFilesGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldTenderFiles, v))
}

// TenderFilesGTE applies the GTE predicate on the "tender_files" field.
func TenderFilesGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldTenderFiles, v))
}

// TenderFilesLT applies the LT predicate on the "tender_files" field.
func TenderFilesLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldTenderFiles, v))
}

// TenderFilesLTE applies the LTE predicate on the "tender_files" field.
func TenderFilesLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldTenderFiles, v))
}

// TenderFilesContains applies the Contains predicate on the "tender_files" field.
func TenderFilesContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldTenderFiles, v))
}

// TenderFilesHasPrefix applies the HasPrefix predicate on the "tender_files" field.
func TenderFilesHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldTenderFiles, v))
}

// TenderFilesHasSuffix applies the HasSuffix predicate on the "tender_files" field.
func TenderFilesHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldTenderFiles, v))
}

// TenderFilesIsNil applies the IsNil predicate on the "tender_files" field.
func TenderFilesIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldTenderFiles))
}

// TenderFilesNotNil applies the NotNil predicate on the "tender_files" field.
func TenderFilesNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldTenderFiles))
}

// TenderFilesEqualFold applies the EqualFold predicate on the "tender_files" field.
func TenderFilesEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldTenderFiles, v))
}

// TenderFilesContainsFold applies the ContainsFold predicate on the "tender_files" field.
func TenderFilesContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldTenderFiles, v))
}

// DeliverBidFilesEQ applies the EQ predicate on the "deliver_bid_files" field.
func DeliverBidFilesEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldDeliverBidFiles, v))
}

// DeliverBidFilesNEQ applies the NEQ predicate on the "deliver_bid_files" field.
func DeliverBidFilesNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldDeliverBidFiles, v))
}

// DeliverBidFilesIn applies the In predicate on the "deliver_bid_files" field.
func DeliverBidFilesIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldDeliverBidFiles, vs...))
}

// DeliverBidFilesNotIn applies the NotIn predicate on the "deliver_bid_files" field.
func DeliverBidFilesNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldDeliverBidFiles, vs...))
}

// DeliverBidFilesGT applies the GT predicate on the "deliver_bid_files" field.
func DeliverBidFilesGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldDeliverBidFiles, v))
}

// DeliverBidFilesGTE applies the GTE predicate on the "deliver_bid_files" field.
func DeliverBidFilesGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldDeliverBidFiles, v))
}

// DeliverBidFilesLT applies the LT predicate on the "deliver_bid_files" field.
func DeliverBidFilesLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldDeliverBidFiles, v))
}

// DeliverBidFilesLTE applies the LTE predicate on the "deliver_bid_files" field.
func DeliverBidFilesLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldDeliverBidFiles, v))
}

// DeliverBidFilesContains applies the Contains predicate on the "deliver_bid_files" field.
func DeliverBidFilesContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldDeliverBidFiles, v))
}

// DeliverBidFilesHasPrefix applies the HasPrefix predicate on the "deliver_bid_files" field.
func DeliverBidFilesHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldDeliverBidFiles, v))
}

// DeliverBidFilesHasSuffix applies the HasSuffix predicate on the "deliver_bid_files" field.
func DeliverBidFilesHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldDeliverBidFiles, v))
}

// DeliverBidFilesIsNil applies the IsNil predicate on the "deliver_bid_files" field.
func DeliverBidFilesIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldDeliverBidFiles))
}

// DeliverBidFilesNotNil applies the NotNil predicate on the "deliver_bid_files" field.
func DeliverBidFilesNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldDeliverBidFiles))
}

// DeliverBidFilesEqualFold applies the EqualFold predicate on the "deliver_bid_files" field.
func DeliverBidFilesEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldDeliverBidFiles, v))
}

// DeliverBidFilesContainsFold applies the ContainsFold predicate on the "deliver_bid_files" field.
func DeliverBidFilesContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldDeliverBidFiles, v))
}

// DeliverBidTimeEQ applies the EQ predicate on the "deliver_bid_time" field.
func DeliverBidTimeEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldDeliverBidTime, v))
}

// DeliverBidTimeNEQ applies the NEQ predicate on the "deliver_bid_time" field.
func DeliverBidTimeNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldDeliverBidTime, v))
}

// DeliverBidTimeIn applies the In predicate on the "deliver_bid_time" field.
func DeliverBidTimeIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldDeliverBidTime, vs...))
}

// DeliverBidTimeNotIn applies the NotIn predicate on the "deliver_bid_time" field.
func DeliverBidTimeNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldDeliverBidTime, vs...))
}

// DeliverBidTimeGT applies the GT predicate on the "deliver_bid_time" field.
func DeliverBidTimeGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldDeliverBidTime, v))
}

// DeliverBidTimeGTE applies the GTE predicate on the "deliver_bid_time" field.
func DeliverBidTimeGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldDeliverBidTime, v))
}

// DeliverBidTimeLT applies the LT predicate on the "deliver_bid_time" field.
func DeliverBidTimeLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldDeliverBidTime, v))
}

// DeliverBidTimeLTE applies the LTE predicate on the "deliver_bid_time" field.
func DeliverBidTimeLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldDeliverBidTime, v))
}

// DeliverBidTimeIsNil applies the IsNil predicate on the "deliver_bid_time" field.
func DeliverBidTimeIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldDeliverBidTime))
}

// DeliverBidTimeNotNil applies the NotNil predicate on the "deliver_bid_time" field.
func DeliverBidTimeNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldDeliverBidTime))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldRemark, v))
}

// ProjectStatusEQ applies the EQ predicate on the "project_status" field.
func ProjectStatusEQ(v int32) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldProjectStatus, v))
}

// ProjectStatusNEQ applies the NEQ predicate on the "project_status" field.
func ProjectStatusNEQ(v int32) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldProjectStatus, v))
}

// ProjectStatusIn applies the In predicate on the "project_status" field.
func ProjectStatusIn(vs ...int32) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldProjectStatus, vs...))
}

// ProjectStatusNotIn applies the NotIn predicate on the "project_status" field.
func ProjectStatusNotIn(vs ...int32) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldProjectStatus, vs...))
}

// ProjectStatusGT applies the GT predicate on the "project_status" field.
func ProjectStatusGT(v int32) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldProjectStatus, v))
}

// ProjectStatusGTE applies the GTE predicate on the "project_status" field.
func ProjectStatusGTE(v int32) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldProjectStatus, v))
}

// ProjectStatusLT applies the LT predicate on the "project_status" field.
func ProjectStatusLT(v int32) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldProjectStatus, v))
}

// ProjectStatusLTE applies the LTE predicate on the "project_status" field.
func ProjectStatusLTE(v int32) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldProjectStatus, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldAmount, v))
}

// PaidAmountEQ applies the EQ predicate on the "paid_amount" field.
func PaidAmountEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldPaidAmount, v))
}

// PaidAmountNEQ applies the NEQ predicate on the "paid_amount" field.
func PaidAmountNEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldPaidAmount, v))
}

// PaidAmountIn applies the In predicate on the "paid_amount" field.
func PaidAmountIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldPaidAmount, vs...))
}

// PaidAmountNotIn applies the NotIn predicate on the "paid_amount" field.
func PaidAmountNotIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldPaidAmount, vs...))
}

// PaidAmountGT applies the GT predicate on the "paid_amount" field.
func PaidAmountGT(v float64) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldPaidAmount, v))
}

// PaidAmountGTE applies the GTE predicate on the "paid_amount" field.
func PaidAmountGTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldPaidAmount, v))
}

// PaidAmountLT applies the LT predicate on the "paid_amount" field.
func PaidAmountLT(v float64) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldPaidAmount, v))
}

// PaidAmountLTE applies the LTE predicate on the "paid_amount" field.
func PaidAmountLTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldPaidAmount, v))
}

// UnpaidAmountEQ applies the EQ predicate on the "unpaid_amount" field.
func UnpaidAmountEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldUnpaidAmount, v))
}

// UnpaidAmountNEQ applies the NEQ predicate on the "unpaid_amount" field.
func UnpaidAmountNEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldUnpaidAmount, v))
}

// UnpaidAmountIn applies the In predicate on the "unpaid_amount" field.
func UnpaidAmountIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldUnpaidAmount, vs...))
}

// UnpaidAmountNotIn applies the NotIn predicate on the "unpaid_amount" field.
func UnpaidAmountNotIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldUnpaidAmount, vs...))
}

// UnpaidAmountGT applies the GT predicate on the "unpaid_amount" field.
func UnpaidAmountGT(v float64) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldUnpaidAmount, v))
}

// UnpaidAmountGTE applies the GTE predicate on the "unpaid_amount" field.
func UnpaidAmountGTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldUnpaidAmount, v))
}

// UnpaidAmountLT applies the LT predicate on the "unpaid_amount" field.
func UnpaidAmountLT(v float64) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldUnpaidAmount, v))
}

// UnpaidAmountLTE applies the LTE predicate on the "unpaid_amount" field.
func UnpaidAmountLTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldUnpaidAmount, v))
}

// CommissionEQ applies the EQ predicate on the "commission" field.
func CommissionEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCommission, v))
}

// CommissionNEQ applies the NEQ predicate on the "commission" field.
func CommissionNEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldCommission, v))
}

// CommissionIn applies the In predicate on the "commission" field.
func CommissionIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldCommission, vs...))
}

// CommissionNotIn applies the NotIn predicate on the "commission" field.
func CommissionNotIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldCommission, vs...))
}

// CommissionGT applies the GT predicate on the "commission" field.
func CommissionGT(v float64) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldCommission, v))
}

// CommissionGTE applies the GTE predicate on the "commission" field.
func CommissionGTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldCommission, v))
}

// CommissionLT applies the LT predicate on the "commission" field.
func CommissionLT(v float64) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldCommission, v))
}

// CommissionLTE applies the LTE predicate on the "commission" field.
func CommissionLTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldCommission, v))
}

// CommissionIsNil applies the IsNil predicate on the "commission" field.
func CommissionIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldCommission))
}

// CommissionNotNil applies the NotNil predicate on the "commission" field.
func CommissionNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldCommission))
}

// WorkerCommissionEQ applies the EQ predicate on the "worker_commission" field.
func WorkerCommissionEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldWorkerCommission, v))
}

// WorkerCommissionNEQ applies the NEQ predicate on the "worker_commission" field.
func WorkerCommissionNEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldWorkerCommission, v))
}

// WorkerCommissionIn applies the In predicate on the "worker_commission" field.
func WorkerCommissionIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldWorkerCommission, vs...))
}

// WorkerCommissionNotIn applies the NotIn predicate on the "worker_commission" field.
func WorkerCommissionNotIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldWorkerCommission, vs...))
}

// WorkerCommissionGT applies the GT predicate on the "worker_commission" field.
func WorkerCommissionGT(v float64) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldWorkerCommission, v))
}

// WorkerCommissionGTE applies the GTE predicate on the "worker_commission" field.
func WorkerCommissionGTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldWorkerCommission, v))
}

// WorkerCommissionLT applies the LT predicate on the "worker_commission" field.
func WorkerCommissionLT(v float64) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldWorkerCommission, v))
}

// WorkerCommissionLTE applies the LTE predicate on the "worker_commission" field.
func WorkerCommissionLTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldWorkerCommission, v))
}

// WorkerCommissionIsNil applies the IsNil predicate on the "worker_commission" field.
func WorkerCommissionIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldWorkerCommission))
}

// WorkerCommissionNotNil applies the NotNil predicate on the "worker_commission" field.
func WorkerCommissionNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldWorkerCommission))
}

// FinanceInvoiceStatusEQ applies the EQ predicate on the "finance_invoice_status" field.
func FinanceInvoiceStatusEQ(v int8) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldFinanceInvoiceStatus, v))
}

// FinanceInvoiceStatusNEQ applies the NEQ predicate on the "finance_invoice_status" field.
func FinanceInvoiceStatusNEQ(v int8) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldFinanceInvoiceStatus, v))
}

// FinanceInvoiceStatusIn applies the In predicate on the "finance_invoice_status" field.
func FinanceInvoiceStatusIn(vs ...int8) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldFinanceInvoiceStatus, vs...))
}

// FinanceInvoiceStatusNotIn applies the NotIn predicate on the "finance_invoice_status" field.
func FinanceInvoiceStatusNotIn(vs ...int8) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldFinanceInvoiceStatus, vs...))
}

// FinanceInvoiceStatusGT applies the GT predicate on the "finance_invoice_status" field.
func FinanceInvoiceStatusGT(v int8) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldFinanceInvoiceStatus, v))
}

// FinanceInvoiceStatusGTE applies the GTE predicate on the "finance_invoice_status" field.
func FinanceInvoiceStatusGTE(v int8) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldFinanceInvoiceStatus, v))
}

// FinanceInvoiceStatusLT applies the LT predicate on the "finance_invoice_status" field.
func FinanceInvoiceStatusLT(v int8) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldFinanceInvoiceStatus, v))
}

// FinanceInvoiceStatusLTE applies the LTE predicate on the "finance_invoice_status" field.
func FinanceInvoiceStatusLTE(v int8) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldFinanceInvoiceStatus, v))
}

// ESignIDEQ applies the EQ predicate on the "e_sign_id" field.
func ESignIDEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldESignID, v))
}

// ESignIDNEQ applies the NEQ predicate on the "e_sign_id" field.
func ESignIDNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldESignID, v))
}

// ESignIDIn applies the In predicate on the "e_sign_id" field.
func ESignIDIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldESignID, vs...))
}

// ESignIDNotIn applies the NotIn predicate on the "e_sign_id" field.
func ESignIDNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldESignID, vs...))
}

// ESignIDGT applies the GT predicate on the "e_sign_id" field.
func ESignIDGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldESignID, v))
}

// ESignIDGTE applies the GTE predicate on the "e_sign_id" field.
func ESignIDGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldESignID, v))
}

// ESignIDLT applies the LT predicate on the "e_sign_id" field.
func ESignIDLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldESignID, v))
}

// ESignIDLTE applies the LTE predicate on the "e_sign_id" field.
func ESignIDLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldESignID, v))
}

// ESignIDContains applies the Contains predicate on the "e_sign_id" field.
func ESignIDContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldESignID, v))
}

// ESignIDHasPrefix applies the HasPrefix predicate on the "e_sign_id" field.
func ESignIDHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldESignID, v))
}

// ESignIDHasSuffix applies the HasSuffix predicate on the "e_sign_id" field.
func ESignIDHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldESignID, v))
}

// ESignIDIsNil applies the IsNil predicate on the "e_sign_id" field.
func ESignIDIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldESignID))
}

// ESignIDNotNil applies the NotNil predicate on the "e_sign_id" field.
func ESignIDNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldESignID))
}

// ESignIDEqualFold applies the EqualFold predicate on the "e_sign_id" field.
func ESignIDEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldESignID, v))
}

// ESignIDContainsFold applies the ContainsFold predicate on the "e_sign_id" field.
func ESignIDContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldESignID, v))
}

// ESignStatusEQ applies the EQ predicate on the "e_sign_status" field.
func ESignStatusEQ(v int8) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldESignStatus, v))
}

// ESignStatusNEQ applies the NEQ predicate on the "e_sign_status" field.
func ESignStatusNEQ(v int8) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldESignStatus, v))
}

// ESignStatusIn applies the In predicate on the "e_sign_status" field.
func ESignStatusIn(vs ...int8) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldESignStatus, vs...))
}

// ESignStatusNotIn applies the NotIn predicate on the "e_sign_status" field.
func ESignStatusNotIn(vs ...int8) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldESignStatus, vs...))
}

// ESignStatusGT applies the GT predicate on the "e_sign_status" field.
func ESignStatusGT(v int8) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldESignStatus, v))
}

// ESignStatusGTE applies the GTE predicate on the "e_sign_status" field.
func ESignStatusGTE(v int8) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldESignStatus, v))
}

// ESignStatusLT applies the LT predicate on the "e_sign_status" field.
func ESignStatusLT(v int8) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldESignStatus, v))
}

// ESignStatusLTE applies the LTE predicate on the "e_sign_status" field.
func ESignStatusLTE(v int8) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldESignStatus, v))
}

// ESignStatusIsNil applies the IsNil predicate on the "e_sign_status" field.
func ESignStatusIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldESignStatus))
}

// ESignStatusNotNil applies the NotNil predicate on the "e_sign_status" field.
func ESignStatusNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldESignStatus))
}

// ESignNotifyEQ applies the EQ predicate on the "e_sign_notify" field.
func ESignNotifyEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldESignNotify, v))
}

// ESignNotifyNEQ applies the NEQ predicate on the "e_sign_notify" field.
func ESignNotifyNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldESignNotify, v))
}

// ESignNotifyIn applies the In predicate on the "e_sign_notify" field.
func ESignNotifyIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldESignNotify, vs...))
}

// ESignNotifyNotIn applies the NotIn predicate on the "e_sign_notify" field.
func ESignNotifyNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldESignNotify, vs...))
}

// ESignNotifyGT applies the GT predicate on the "e_sign_notify" field.
func ESignNotifyGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldESignNotify, v))
}

// ESignNotifyGTE applies the GTE predicate on the "e_sign_notify" field.
func ESignNotifyGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldESignNotify, v))
}

// ESignNotifyLT applies the LT predicate on the "e_sign_notify" field.
func ESignNotifyLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldESignNotify, v))
}

// ESignNotifyLTE applies the LTE predicate on the "e_sign_notify" field.
func ESignNotifyLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldESignNotify, v))
}

// ESignNotifyContains applies the Contains predicate on the "e_sign_notify" field.
func ESignNotifyContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldESignNotify, v))
}

// ESignNotifyHasPrefix applies the HasPrefix predicate on the "e_sign_notify" field.
func ESignNotifyHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldESignNotify, v))
}

// ESignNotifyHasSuffix applies the HasSuffix predicate on the "e_sign_notify" field.
func ESignNotifyHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldESignNotify, v))
}

// ESignNotifyIsNil applies the IsNil predicate on the "e_sign_notify" field.
func ESignNotifyIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldESignNotify))
}

// ESignNotifyNotNil applies the NotNil predicate on the "e_sign_notify" field.
func ESignNotifyNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldESignNotify))
}

// ESignNotifyEqualFold applies the EqualFold predicate on the "e_sign_notify" field.
func ESignNotifyEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldESignNotify, v))
}

// ESignNotifyContainsFold applies the ContainsFold predicate on the "e_sign_notify" field.
func ESignNotifyContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldESignNotify, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v float64) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v float64) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldScore, v))
}

// EvaluateEQ applies the EQ predicate on the "evaluate" field.
func EvaluateEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldEvaluate, v))
}

// EvaluateNEQ applies the NEQ predicate on the "evaluate" field.
func EvaluateNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldEvaluate, v))
}

// EvaluateIn applies the In predicate on the "evaluate" field.
func EvaluateIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldEvaluate, vs...))
}

// EvaluateNotIn applies the NotIn predicate on the "evaluate" field.
func EvaluateNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldEvaluate, vs...))
}

// EvaluateGT applies the GT predicate on the "evaluate" field.
func EvaluateGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldEvaluate, v))
}

// EvaluateGTE applies the GTE predicate on the "evaluate" field.
func EvaluateGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldEvaluate, v))
}

// EvaluateLT applies the LT predicate on the "evaluate" field.
func EvaluateLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldEvaluate, v))
}

// EvaluateLTE applies the LTE predicate on the "evaluate" field.
func EvaluateLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldEvaluate, v))
}

// EvaluateContains applies the Contains predicate on the "evaluate" field.
func EvaluateContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldEvaluate, v))
}

// EvaluateHasPrefix applies the HasPrefix predicate on the "evaluate" field.
func EvaluateHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldEvaluate, v))
}

// EvaluateHasSuffix applies the HasSuffix predicate on the "evaluate" field.
func EvaluateHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldEvaluate, v))
}

// EvaluateIsNil applies the IsNil predicate on the "evaluate" field.
func EvaluateIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldEvaluate))
}

// EvaluateNotNil applies the NotNil predicate on the "evaluate" field.
func EvaluateNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldEvaluate))
}

// EvaluateEqualFold applies the EqualFold predicate on the "evaluate" field.
func EvaluateEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldEvaluate, v))
}

// EvaluateContainsFold applies the ContainsFold predicate on the "evaluate" field.
func EvaluateContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldEvaluate, v))
}

// CancelReasonEQ applies the EQ predicate on the "cancel_reason" field.
func CancelReasonEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCancelReason, v))
}

// CancelReasonNEQ applies the NEQ predicate on the "cancel_reason" field.
func CancelReasonNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldCancelReason, v))
}

// CancelReasonIn applies the In predicate on the "cancel_reason" field.
func CancelReasonIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldCancelReason, vs...))
}

// CancelReasonNotIn applies the NotIn predicate on the "cancel_reason" field.
func CancelReasonNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldCancelReason, vs...))
}

// CancelReasonGT applies the GT predicate on the "cancel_reason" field.
func CancelReasonGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldCancelReason, v))
}

// CancelReasonGTE applies the GTE predicate on the "cancel_reason" field.
func CancelReasonGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldCancelReason, v))
}

// CancelReasonLT applies the LT predicate on the "cancel_reason" field.
func CancelReasonLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldCancelReason, v))
}

// CancelReasonLTE applies the LTE predicate on the "cancel_reason" field.
func CancelReasonLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldCancelReason, v))
}

// CancelReasonContains applies the Contains predicate on the "cancel_reason" field.
func CancelReasonContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldCancelReason, v))
}

// CancelReasonHasPrefix applies the HasPrefix predicate on the "cancel_reason" field.
func CancelReasonHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldCancelReason, v))
}

// CancelReasonHasSuffix applies the HasSuffix predicate on the "cancel_reason" field.
func CancelReasonHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldCancelReason, v))
}

// CancelReasonIsNil applies the IsNil predicate on the "cancel_reason" field.
func CancelReasonIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldCancelReason))
}

// CancelReasonNotNil applies the NotNil predicate on the "cancel_reason" field.
func CancelReasonNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldCancelReason))
}

// CancelReasonEqualFold applies the EqualFold predicate on the "cancel_reason" field.
func CancelReasonEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldCancelReason, v))
}

// CancelReasonContainsFold applies the ContainsFold predicate on the "cancel_reason" field.
func CancelReasonContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldCancelReason, v))
}

// CloseAtEQ applies the EQ predicate on the "close_at" field.
func CloseAtEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCloseAt, v))
}

// CloseAtNEQ applies the NEQ predicate on the "close_at" field.
func CloseAtNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldCloseAt, v))
}

// CloseAtIn applies the In predicate on the "close_at" field.
func CloseAtIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldCloseAt, vs...))
}

// CloseAtNotIn applies the NotIn predicate on the "close_at" field.
func CloseAtNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldCloseAt, vs...))
}

// CloseAtGT applies the GT predicate on the "close_at" field.
func CloseAtGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldCloseAt, v))
}

// CloseAtGTE applies the GTE predicate on the "close_at" field.
func CloseAtGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldCloseAt, v))
}

// CloseAtLT applies the LT predicate on the "close_at" field.
func CloseAtLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldCloseAt, v))
}

// CloseAtLTE applies the LTE predicate on the "close_at" field.
func CloseAtLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldCloseAt, v))
}

// CloseAtIsNil applies the IsNil predicate on the "close_at" field.
func CloseAtIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldCloseAt))
}

// CloseAtNotNil applies the NotNil predicate on the "close_at" field.
func CloseAtNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldCloseAt))
}

// ChannelCodeEQ applies the EQ predicate on the "channel_code" field.
func ChannelCodeEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldChannelCode, v))
}

// ChannelCodeNEQ applies the NEQ predicate on the "channel_code" field.
func ChannelCodeNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldChannelCode, v))
}

// ChannelCodeIn applies the In predicate on the "channel_code" field.
func ChannelCodeIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldChannelCode, vs...))
}

// ChannelCodeNotIn applies the NotIn predicate on the "channel_code" field.
func ChannelCodeNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldChannelCode, vs...))
}

// ChannelCodeGT applies the GT predicate on the "channel_code" field.
func ChannelCodeGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldChannelCode, v))
}

// ChannelCodeGTE applies the GTE predicate on the "channel_code" field.
func ChannelCodeGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldChannelCode, v))
}

// ChannelCodeLT applies the LT predicate on the "channel_code" field.
func ChannelCodeLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldChannelCode, v))
}

// ChannelCodeLTE applies the LTE predicate on the "channel_code" field.
func ChannelCodeLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldChannelCode, v))
}

// ChannelCodeContains applies the Contains predicate on the "channel_code" field.
func ChannelCodeContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldChannelCode, v))
}

// ChannelCodeHasPrefix applies the HasPrefix predicate on the "channel_code" field.
func ChannelCodeHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldChannelCode, v))
}

// ChannelCodeHasSuffix applies the HasSuffix predicate on the "channel_code" field.
func ChannelCodeHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldChannelCode, v))
}

// ChannelCodeIsNil applies the IsNil predicate on the "channel_code" field.
func ChannelCodeIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldChannelCode))
}

// ChannelCodeNotNil applies the NotNil predicate on the "channel_code" field.
func ChannelCodeNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldChannelCode))
}

// ChannelCodeEqualFold applies the EqualFold predicate on the "channel_code" field.
func ChannelCodeEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldChannelCode, v))
}

// ChannelCodeContainsFold applies the ContainsFold predicate on the "channel_code" field.
func ChannelCodeContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldChannelCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldCreatedAt))
}

// PayMoneyEQ applies the EQ predicate on the "pay_money" field.
func PayMoneyEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldPayMoney, v))
}

// PayMoneyNEQ applies the NEQ predicate on the "pay_money" field.
func PayMoneyNEQ(v float64) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldPayMoney, v))
}

// PayMoneyIn applies the In predicate on the "pay_money" field.
func PayMoneyIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldPayMoney, vs...))
}

// PayMoneyNotIn applies the NotIn predicate on the "pay_money" field.
func PayMoneyNotIn(vs ...float64) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldPayMoney, vs...))
}

// PayMoneyGT applies the GT predicate on the "pay_money" field.
func PayMoneyGT(v float64) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldPayMoney, v))
}

// PayMoneyGTE applies the GTE predicate on the "pay_money" field.
func PayMoneyGTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldPayMoney, v))
}

// PayMoneyLT applies the LT predicate on the "pay_money" field.
func PayMoneyLT(v float64) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldPayMoney, v))
}

// PayMoneyLTE applies the LTE predicate on the "pay_money" field.
func PayMoneyLTE(v float64) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldPayMoney, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldUpdatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Project) predicate.Project {
	return predicate.Project(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Project) predicate.Project {
	return predicate.Project(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Project) predicate.Project {
	return predicate.Project(sql.NotPredicates(p))
}
