// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Finance is the predicate function for finance builders.
type Finance func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectActionRecord is the predicate function for projectactionrecord builders.
type ProjectActionRecord func(*sql.Selector)
