// Code generated by ent, DO NOT EDIT.

package finance

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the finance type in the database.
	Label = "finance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldTransactNo holds the string denoting the transact_no field in the database.
	FieldTransactNo = "transact_no"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldTheirAccountID holds the string denoting the their_account_id field in the database.
	FieldTheirAccountID = "their_account_id"
	// FieldTransactAt holds the string denoting the transact_at field in the database.
	FieldTransactAt = "transact_at"
	// FieldWriteOffAt holds the string denoting the write_off_at field in the database.
	FieldWriteOffAt = "write_off_at"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldPayModeType holds the string denoting the pay_mode_type field in the database.
	FieldPayModeType = "pay_mode_type"
	// FieldPayInfo holds the string denoting the pay_info field in the database.
	FieldPayInfo = "pay_info"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldPayStatus holds the string denoting the pay_status field in the database.
	FieldPayStatus = "pay_status"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldChangeType holds the string denoting the change_type field in the database.
	FieldChangeType = "change_type"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the finance in the database.
	Table = "finance"
)

// Columns holds all SQL columns for finance fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldTransactNo,
	FieldOrderNo,
	FieldProjectID,
	FieldAccountID,
	FieldTheirAccountID,
	FieldTransactAt,
	FieldWriteOffAt,
	FieldSummary,
	FieldPayModeType,
	FieldPayInfo,
	FieldRemark,
	FieldPayStatus,
	FieldAmount,
	FieldChangeType,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID int32
)

// OrderOption defines the ordering options for the Finance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByTransactNo orders the results by the transact_no field.
func ByTransactNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactNo, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByTheirAccountID orders the results by the their_account_id field.
func ByTheirAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTheirAccountID, opts...).ToFunc()
}

// ByTransactAt orders the results by the transact_at field.
func ByTransactAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactAt, opts...).ToFunc()
}

// ByWriteOffAt orders the results by the write_off_at field.
func ByWriteOffAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWriteOffAt, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByPayModeType orders the results by the pay_mode_type field.
func ByPayModeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayModeType, opts...).ToFunc()
}

// ByPayInfo orders the results by the pay_info field.
func ByPayInfo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayInfo, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByPayStatus orders the results by the pay_status field.
func ByPayStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayStatus, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByChangeType orders the results by the change_type field.
func ByChangeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangeType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
