// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountColumns holds the columns for the "account" table.
	AccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true, SchemaType: map[string]string{"mysql": "int  "}},
		{Name: "tenant_id", Type: field.TypeInt32, Default: 1, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "account_integral", Type: field.TypeInt32, Nullable: true, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "account_balance", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"mysql": "decimal(10,2)"}},
		{Name: "user_identity", Type: field.TypeInt8, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "freeze_balance", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"mysql": "decimal(10,2) "}},
		{Name: "freeze_integral", Type: field.TypeInt32, Default: 0, SchemaType: map[string]string{"mysql": "int "}},
	}
	// AccountTable holds the schema information for the "account" table.
	AccountTable = &schema.Table{
		Name:       "account",
		Columns:    AccountColumns,
		PrimaryKey: []*schema.Column{AccountColumns[0]},
	}
	// AccountWalletColumns holds the columns for the "account_wallet" table.
	AccountWalletColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true, SchemaType: map[string]string{"mysql": "int unsigned"}},
		{Name: "tenant_id", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "account_id", Type: field.TypeInt32, Nullable: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "account_integral", Type: field.TypeInt32, Nullable: true, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "account_balance", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"mysql": "decimal(10,2)"}},
		{Name: "freeze_balance", Type: field.TypeFloat64, SchemaType: map[string]string{"mysql": "decimal(10,2)unsigned"}},
		{Name: "freeze_integral", Type: field.TypeInt32, Nullable: true, Default: 0, SchemaType: map[string]string{"mysql": "int unsigned"}},
		{Name: "open_installment", Type: field.TypeInt8, Default: 2, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "status", Type: field.TypeInt8, Nullable: true, SchemaType: map[string]string{"mysql": "tinyint(1)"}},
		{Name: "state", Type: field.TypeInt8, Nullable: true, SchemaType: map[string]string{"mysql": "tinyint(1)"}},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
	}
	// AccountWalletTable holds the schema information for the "account_wallet" table.
	AccountWalletTable = &schema.Table{
		Name:       "account_wallet",
		Columns:    AccountWalletColumns,
		PrimaryKey: []*schema.Column{AccountWalletColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountTable,
		AccountWalletTable,
	}
)

func init() {
	AccountTable.Annotation = &entsql.Annotation{
		Table: "account",
	}
	AccountWalletTable.Annotation = &entsql.Annotation{
		Table: "account_wallet",
	}
}
