// Code generated by ent, DO NOT EDIT.

package accountwallet

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountwallet type in the database.
	Label = "account_wallet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountIntegral holds the string denoting the account_integral field in the database.
	FieldAccountIntegral = "account_integral"
	// FieldAccountBalance holds the string denoting the account_balance field in the database.
	FieldAccountBalance = "account_balance"
	// FieldFreezeBalance holds the string denoting the freeze_balance field in the database.
	FieldFreezeBalance = "freeze_balance"
	// FieldFreezeIntegral holds the string denoting the freeze_integral field in the database.
	FieldFreezeIntegral = "freeze_integral"
	// FieldOpenInstallment holds the string denoting the open_installment field in the database.
	FieldOpenInstallment = "open_installment"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the accountwallet in the database.
	Table = "account_wallet"
)

// Columns holds all SQL columns for accountwallet fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldAccountID,
	FieldAccountIntegral,
	FieldAccountBalance,
	FieldFreezeBalance,
	FieldFreezeIntegral,
	FieldOpenInstallment,
	FieldStatus,
	FieldState,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAccountIntegral holds the default value on creation for the "account_integral" field.
	DefaultAccountIntegral int32
	// DefaultFreezeIntegral holds the default value on creation for the "freeze_integral" field.
	DefaultFreezeIntegral int32
	// DefaultOpenInstallment holds the default value on creation for the "open_installment" field.
	DefaultOpenInstallment int8
)

// OrderOption defines the ordering options for the AccountWallet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountIntegral orders the results by the account_integral field.
func ByAccountIntegral(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountIntegral, opts...).ToFunc()
}

// ByAccountBalance orders the results by the account_balance field.
func ByAccountBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountBalance, opts...).ToFunc()
}

// ByFreezeBalance orders the results by the freeze_balance field.
func ByFreezeBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFreezeBalance, opts...).ToFunc()
}

// ByFreezeIntegral orders the results by the freeze_integral field.
func ByFreezeIntegral(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFreezeIntegral, opts...).ToFunc()
}

// ByOpenInstallment orders the results by the open_installment field.
func ByOpenInstallment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenInstallment, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
