// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FinanceColumns holds the columns for the "finance" table.
	FinanceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "tenant_id", Type: field.TypeInt32, Default: 1, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "transact_no", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "order_no", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "project_id", Type: field.TypeInt32, Nullable: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "account_id", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "their_account_id", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "transact_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "write_off_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "summary", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "pay_mode_type", Type: field.TypeInt8, Nullable: true, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "pay_info", Type: field.TypeString, Nullable: true, Size: 2147483647, SchemaType: map[string]string{"mysql": "text"}},
		{Name: "remark", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "pay_status", Type: field.TypeInt8, Nullable: true, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "amount", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"mysql": "decimal(32,2)"}},
		{Name: "change_type", Type: field.TypeInt8, Nullable: true, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
	}
	// FinanceTable holds the schema information for the "finance" table.
	FinanceTable = &schema.Table{
		Name:       "finance",
		Columns:    FinanceColumns,
		PrimaryKey: []*schema.Column{FinanceColumns[0]},
	}
	// ProjectColumns holds the columns for the "project" table.
	ProjectColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "tenant_id", Type: field.TypeInt32, Default: 1, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "account_id", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "account_phone", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(15)"}},
		{Name: "worker_account_id", Type: field.TypeInt32, Nullable: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "project_type", Type: field.TypeInt8, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "title", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "expect_deliver_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "tender_files", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "deliver_bid_files", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "deliver_bid_time", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "remark", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "project_status", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"mysql": "decimal(10,2)unsigned"}},
		{Name: "paid_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"mysql": "decimal(10,2)unsigned"}},
		{Name: "unpaid_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"mysql": "decimal(10,2)unsigned"}},
		{Name: "commission", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"mysql": "decimal(10,2)"}},
		{Name: "worker_commission", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"mysql": "decimal(10,2)"}},
		{Name: "finance_invoice_status", Type: field.TypeInt8, Default: 1, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "e_sign_id", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "e_sign_status", Type: field.TypeInt8, Nullable: true, Default: 1, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "e_sign_notify", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "score", Type: field.TypeFloat64, Default: 5, SchemaType: map[string]string{"mysql": "decimal(2,1)unsigned"}},
		{Name: "evaluate", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "cancel_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "close_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "channel_code", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(255)"}},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "pay_money", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"mysql": "decimal(10,2)"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "timestamp"}},
	}
	// ProjectTable holds the schema information for the "project" table.
	ProjectTable = &schema.Table{
		Name:       "project",
		Columns:    ProjectColumns,
		PrimaryKey: []*schema.Column{ProjectColumns[0]},
	}
	// ProjectActionRecordColumns holds the columns for the "project_action_record" table.
	ProjectActionRecordColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "tenant_id", Type: field.TypeInt32, Default: 1, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "project_id", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "action_plat", Type: field.TypeInt8, Default: 1, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "action", Type: field.TypeString, Default: "", SchemaType: map[string]string{"mysql": "varchar(200)"}},
		{Name: "account_id", Type: field.TypeInt32, Nullable: true, Default: 0, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "account_name", Type: field.TypeString, Nullable: true, Default: "", SchemaType: map[string]string{"mysql": "varchar(50)"}},
		{Name: "project_status", Type: field.TypeInt32, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "project_status_text", Type: field.TypeString, Default: "", SchemaType: map[string]string{"mysql": "varchar(200)"}},
		{Name: "status", Type: field.TypeInt8, Nullable: true, Default: 1, SchemaType: map[string]string{"mysql": "tinyint"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp"}},
	}
	// ProjectActionRecordTable holds the schema information for the "project_action_record" table.
	ProjectActionRecordTable = &schema.Table{
		Name:       "project_action_record",
		Columns:    ProjectActionRecordColumns,
		PrimaryKey: []*schema.Column{ProjectActionRecordColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FinanceTable,
		ProjectTable,
		ProjectActionRecordTable,
	}
)

func init() {
	FinanceTable.Annotation = &entsql.Annotation{
		Table: "finance",
	}
	ProjectTable.Annotation = &entsql.Annotation{
		Table: "project",
	}
	ProjectActionRecordTable.Annotation = &entsql.Annotation{
		Table: "project_action_record",
	}
}
